package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * EntAdmin generated by hbm2java
 */
public class EntAdmin implements java.io.Serializable {

	private long id;
	private String name;
	private String password;
	private String email;
	private long rights;
	private boolean enabled;
	private Set tblOperationLogs = new HashSet(0);

	public EntAdmin() {
	}

	public EntAdmin(long id, String name, String password, String email,
			long rights, boolean enabled) {
		this.id = id;
		this.name = name;
		this.password = password;
		this.email = email;
		this.rights = rights;
		this.enabled = enabled;
	}

	public EntAdmin(long id, String name, String password, String email,
			long rights, boolean enabled, Set tblOperationLogs) {
		this.id = id;
		this.name = name;
		this.password = password;
		this.email = email;
		this.rights = rights;
		this.enabled = enabled;
		this.tblOperationLogs = tblOperationLogs;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public long getRights() {
		return this.rights;
	}

	public void setRights(long rights) {
		this.rights = rights;
	}

	public boolean isEnabled() {
		return this.enabled;
	}

	public void setEnabled(boolean enabled) {
		this.enabled = enabled;
	}

	public Set getTblOperationLogs() {
		return this.tblOperationLogs;
	}

	public void setTblOperationLogs(Set tblOperationLogs) {
		this.tblOperationLogs = tblOperationLogs;
	}

}
