package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * EntBizMenuEntry generated by hbm2java
 */
public class EntBizMenuEntry implements java.io.Serializable {

	private String name;
	private String label;
	private String description;

	public EntBizMenuEntry() {
	}

	public EntBizMenuEntry(String name, String label) {
		this.name = name;
		this.label = label;
	}

	public EntBizMenuEntry(String name, String label, String description) {
		this.name = name;
		this.label = label;
		this.description = description;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
