package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * EntConfigModuleBitMaskId generated by hbm2java
 */
public class EntConfigModuleBitMaskId implements java.io.Serializable {

	private String name;
	private long value;
	private boolean enabled;

	public EntConfigModuleBitMaskId() {
	}

	public EntConfigModuleBitMaskId(String name, long value, boolean enabled) {
		this.name = name;
		this.value = value;
		this.enabled = enabled;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public long getValue() {
		return this.value;
	}

	public void setValue(long value) {
		this.value = value;
	}

	public boolean isEnabled() {
		return this.enabled;
	}

	public void setEnabled(boolean enabled) {
		this.enabled = enabled;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EntConfigModuleBitMaskId))
			return false;
		EntConfigModuleBitMaskId castOther = (EntConfigModuleBitMaskId) other;

		return ((this.getName() == castOther.getName()) || (this.getName() != null
				&& castOther.getName() != null && this.getName().equals(
				castOther.getName())))
				&& (this.getValue() == castOther.getValue())
				&& (this.isEnabled() == castOther.isEnabled());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getName() == null ? 0 : this.getName().hashCode());
		result = 37 * result + (int) this.getValue();
		result = 37 * result + (this.isEnabled() ? 1 : 0);
		return result;
	}

}
