package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * EntConfig generated by hbm2java
 */
public class EntConfig implements java.io.Serializable {

	private String name;
	private long ownerId;
	private long ownerType;
	private String type;
	private String value;
	private long level;
	private String limitL;
	private String limitH;
	private String candidate;
	private String pattern;
	private String description;
	private long uiOrder;
	private Set tblCustomizedConfigForHwSpecs = new HashSet(0);
	private Set tblCustomizedConfigForIndustries = new HashSet(0);
	private Set tblCustomizedConfigForUserGroupScenes = new HashSet(0);
	private Set tblInheritConfigForUserGroups = new HashSet(0);
	private Set tblInheritConfigForRobots = new HashSet(0);
	private Set tblCustomizedConfigForRobots = new HashSet(0);
	private Set tblCustomizedConfigForUserGroups = new HashSet(0);

	public EntConfig() {
	}

	public EntConfig(String name, long ownerId, long ownerType, String type,
			String value, long level, String description, long uiOrder) {
		this.name = name;
		this.ownerId = ownerId;
		this.ownerType = ownerType;
		this.type = type;
		this.value = value;
		this.level = level;
		this.description = description;
		this.uiOrder = uiOrder;
	}

	public EntConfig(String name, long ownerId, long ownerType, String type,
			String value, long level, String limitL, String limitH,
			String candidate, String pattern, String description, long uiOrder,
			Set tblCustomizedConfigForHwSpecs,
			Set tblCustomizedConfigForIndustries,
			Set tblCustomizedConfigForUserGroupScenes,
			Set tblInheritConfigForUserGroups, Set tblInheritConfigForRobots,
			Set tblCustomizedConfigForRobots,
			Set tblCustomizedConfigForUserGroups) {
		this.name = name;
		this.ownerId = ownerId;
		this.ownerType = ownerType;
		this.type = type;
		this.value = value;
		this.level = level;
		this.limitL = limitL;
		this.limitH = limitH;
		this.candidate = candidate;
		this.pattern = pattern;
		this.description = description;
		this.uiOrder = uiOrder;
		this.tblCustomizedConfigForHwSpecs = tblCustomizedConfigForHwSpecs;
		this.tblCustomizedConfigForIndustries = tblCustomizedConfigForIndustries;
		this.tblCustomizedConfigForUserGroupScenes = tblCustomizedConfigForUserGroupScenes;
		this.tblInheritConfigForUserGroups = tblInheritConfigForUserGroups;
		this.tblInheritConfigForRobots = tblInheritConfigForRobots;
		this.tblCustomizedConfigForRobots = tblCustomizedConfigForRobots;
		this.tblCustomizedConfigForUserGroups = tblCustomizedConfigForUserGroups;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public long getOwnerId() {
		return this.ownerId;
	}

	public void setOwnerId(long ownerId) {
		this.ownerId = ownerId;
	}

	public long getOwnerType() {
		return this.ownerType;
	}

	public void setOwnerType(long ownerType) {
		this.ownerType = ownerType;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	public long getLevel() {
		return this.level;
	}

	public void setLevel(long level) {
		this.level = level;
	}

	public String getLimitL() {
		return this.limitL;
	}

	public void setLimitL(String limitL) {
		this.limitL = limitL;
	}

	public String getLimitH() {
		return this.limitH;
	}

	public void setLimitH(String limitH) {
		this.limitH = limitH;
	}

	public String getCandidate() {
		return this.candidate;
	}

	public void setCandidate(String candidate) {
		this.candidate = candidate;
	}

	public String getPattern() {
		return this.pattern;
	}

	public void setPattern(String pattern) {
		this.pattern = pattern;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public long getUiOrder() {
		return this.uiOrder;
	}

	public void setUiOrder(long uiOrder) {
		this.uiOrder = uiOrder;
	}

	public Set getTblCustomizedConfigForHwSpecs() {
		return this.tblCustomizedConfigForHwSpecs;
	}

	public void setTblCustomizedConfigForHwSpecs(
			Set tblCustomizedConfigForHwSpecs) {
		this.tblCustomizedConfigForHwSpecs = tblCustomizedConfigForHwSpecs;
	}

	public Set getTblCustomizedConfigForIndustries() {
		return this.tblCustomizedConfigForIndustries;
	}

	public void setTblCustomizedConfigForIndustries(
			Set tblCustomizedConfigForIndustries) {
		this.tblCustomizedConfigForIndustries = tblCustomizedConfigForIndustries;
	}

	public Set getTblCustomizedConfigForUserGroupScenes() {
		return this.tblCustomizedConfigForUserGroupScenes;
	}

	public void setTblCustomizedConfigForUserGroupScenes(
			Set tblCustomizedConfigForUserGroupScenes) {
		this.tblCustomizedConfigForUserGroupScenes = tblCustomizedConfigForUserGroupScenes;
	}

	public Set getTblInheritConfigForUserGroups() {
		return this.tblInheritConfigForUserGroups;
	}

	public void setTblInheritConfigForUserGroups(
			Set tblInheritConfigForUserGroups) {
		this.tblInheritConfigForUserGroups = tblInheritConfigForUserGroups;
	}

	public Set getTblInheritConfigForRobots() {
		return this.tblInheritConfigForRobots;
	}

	public void setTblInheritConfigForRobots(Set tblInheritConfigForRobots) {
		this.tblInheritConfigForRobots = tblInheritConfigForRobots;
	}

	public Set getTblCustomizedConfigForRobots() {
		return this.tblCustomizedConfigForRobots;
	}

	public void setTblCustomizedConfigForRobots(Set tblCustomizedConfigForRobots) {
		this.tblCustomizedConfigForRobots = tblCustomizedConfigForRobots;
	}

	public Set getTblCustomizedConfigForUserGroups() {
		return this.tblCustomizedConfigForUserGroups;
	}

	public void setTblCustomizedConfigForUserGroups(
			Set tblCustomizedConfigForUserGroups) {
		this.tblCustomizedConfigForUserGroups = tblCustomizedConfigForUserGroups;
	}

}
