package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * EntCustomer generated by hbm2java
 */
public class EntCustomer implements java.io.Serializable {

	private String id;
	private String name;
	private String nickName;
	private String englishName;
	private Boolean sex;
	private String customerGroupId;

	public EntCustomer() {
	}

	public EntCustomer(String id, String name, String customerGroupId) {
		this.id = id;
		this.name = name;
		this.customerGroupId = customerGroupId;
	}

	public EntCustomer(String id, String name, String nickName,
			String englishName, Boolean sex, String customerGroupId) {
		this.id = id;
		this.name = name;
		this.nickName = nickName;
		this.englishName = englishName;
		this.sex = sex;
		this.customerGroupId = customerGroupId;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getNickName() {
		return this.nickName;
	}

	public void setNickName(String nickName) {
		this.nickName = nickName;
	}

	public String getEnglishName() {
		return this.englishName;
	}

	public void setEnglishName(String englishName) {
		this.englishName = englishName;
	}

	public Boolean getSex() {
		return this.sex;
	}

	public void setSex(Boolean sex) {
		this.sex = sex;
	}

	public String getCustomerGroupId() {
		return this.customerGroupId;
	}

	public void setCustomerGroupId(String customerGroupId) {
		this.customerGroupId = customerGroupId;
	}

}
