package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * EntDialogBackup generated by hbm2java
 */
public class EntDialogBackup implements java.io.Serializable {

	private EntDialogBackupId id;

	public EntDialogBackup() {
	}

	public EntDialogBackup(EntDialogBackupId id) {
		this.id = id;
	}

	public EntDialogBackupId getId() {
		return this.id;
	}

	public void setId(EntDialogBackupId id) {
		this.id = id;
	}

}
