package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * EntEntity generated by hbm2java
 */
public class EntEntity implements java.io.Serializable {

	private EntEntityId id;

	public EntEntity() {
	}

	public EntEntity(EntEntityId id) {
		this.id = id;
	}

	public EntEntityId getId() {
		return this.id;
	}

	public void setId(EntEntityId id) {
		this.id = id;
	}

}
