package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * EntKeyWords generated by hbm2java
 */
public class EntKeyWords implements java.io.Serializable {

	private long id;
	private String kw;
	private long cat;
	private String sound;
	private Set tblWordGroups = new HashSet(0);

	public EntKeyWords() {
	}

	public EntKeyWords(long id, String kw, long cat, String sound) {
		this.id = id;
		this.kw = kw;
		this.cat = cat;
		this.sound = sound;
	}

	public EntKeyWords(long id, String kw, long cat, String sound,
			Set tblWordGroups) {
		this.id = id;
		this.kw = kw;
		this.cat = cat;
		this.sound = sound;
		this.tblWordGroups = tblWordGroups;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getKw() {
		return this.kw;
	}

	public void setKw(String kw) {
		this.kw = kw;
	}

	public long getCat() {
		return this.cat;
	}

	public void setCat(long cat) {
		this.cat = cat;
	}

	public String getSound() {
		return this.sound;
	}

	public void setSound(String sound) {
		this.sound = sound;
	}

	public Set getTblWordGroups() {
		return this.tblWordGroups;
	}

	public void setTblWordGroups(Set tblWordGroups) {
		this.tblWordGroups = tblWordGroups;
	}

}
