package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * EntOperation generated by hbm2java
 */
public class EntOperation implements java.io.Serializable {

	private String name;
	private short bitOrder;
	private String description;

	public EntOperation() {
	}

	public EntOperation(String name, short bitOrder, String description) {
		this.name = name;
		this.bitOrder = bitOrder;
		this.description = description;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public short getBitOrder() {
		return this.bitOrder;
	}

	public void setBitOrder(short bitOrder) {
		this.bitOrder = bitOrder;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
