package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * EntPinyin4Id generated by hbm2java
 */
public class EntPinyin4Id implements java.io.Serializable {

	private char ch;
	private String py;

	public EntPinyin4Id() {
	}

	public EntPinyin4Id(char ch, String py) {
		this.ch = ch;
		this.py = py;
	}

	public char getCh() {
		return this.ch;
	}

	public void setCh(char ch) {
		this.ch = ch;
	}

	public String getPy() {
		return this.py;
	}

	public void setPy(String py) {
		this.py = py;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EntPinyin4Id))
			return false;
		EntPinyin4Id castOther = (EntPinyin4Id) other;

		return (this.getCh() == castOther.getCh())
				&& ((this.getPy() == castOther.getPy()) || (this.getPy() != null
						&& castOther.getPy() != null && this.getPy().equals(
						castOther.getPy())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCh();
		result = 37 * result + (getPy() == null ? 0 : this.getPy().hashCode());
		return result;
	}

}
