package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * EntPinyin2 generated by hbm2java
 */
public class EntPinyin2 implements java.io.Serializable {

	private EntPinyin2Id id;

	public EntPinyin2() {
	}

	public EntPinyin2(EntPinyin2Id id) {
		this.id = id;
	}

	public EntPinyin2Id getId() {
		return this.id;
	}

	public void setId(EntPinyin2Id id) {
		this.id = id;
	}

}
