package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * EntPinyin3 generated by hbm2java
 */
public class EntPinyin3 implements java.io.Serializable {

	private EntPinyin3Id id;

	public EntPinyin3() {
	}

	public EntPinyin3(EntPinyin3Id id) {
		this.id = id;
	}

	public EntPinyin3Id getId() {
		return this.id;
	}

	public void setId(EntPinyin3Id id) {
		this.id = id;
	}

}
