package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * EntPinyin4 generated by hbm2java
 */
public class EntPinyin4 implements java.io.Serializable {

	private EntPinyin4Id id;

	public EntPinyin4() {
	}

	public EntPinyin4(EntPinyin4Id id) {
		this.id = id;
	}

	public EntPinyin4Id getId() {
		return this.id;
	}

	public void setId(EntPinyin4Id id) {
		this.id = id;
	}

}
