package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * EntPinyin3Id generated by hbm2java
 */
public class EntPinyin3Id implements java.io.Serializable {

	private String py;
	private Character chr;

	public EntPinyin3Id() {
	}

	public EntPinyin3Id(String py, Character chr) {
		this.py = py;
		this.chr = chr;
	}

	public String getPy() {
		return this.py;
	}

	public void setPy(String py) {
		this.py = py;
	}

	public Character getChr() {
		return this.chr;
	}

	public void setChr(Character chr) {
		this.chr = chr;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EntPinyin3Id))
			return false;
		EntPinyin3Id castOther = (EntPinyin3Id) other;

		return ((this.getPy() == castOther.getPy()) || (this.getPy() != null
				&& castOther.getPy() != null && this.getPy().equals(
				castOther.getPy())))
				&& ((this.getChr() == castOther.getChr()) || (this.getChr() != null
						&& castOther.getChr() != null && this.getChr().equals(
						castOther.getChr())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getPy() == null ? 0 : this.getPy().hashCode());
		result = 37 * result
				+ (getChr() == null ? 0 : this.getChr().hashCode());
		return result;
	}

}
