package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * EntResource generated by hbm2java
 */
public class EntResource implements java.io.Serializable {

	private long id;
	private String value;
	private String description;

	public EntResource() {
	}

	public EntResource(long id, String value) {
		this.id = id;
		this.value = value;
	}

	public EntResource(long id, String value, String description) {
		this.id = id;
		this.value = value;
		this.description = description;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
