package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * EntRoom generated by hbm2java
 */
public class EntRoom implements java.io.Serializable {

	private long id;
	private String name;
	private String poisition;
	private Set tblOrderRooms = new HashSet(0);

	public EntRoom() {
	}

	public EntRoom(long id, String name, String poisition) {
		this.id = id;
		this.name = name;
		this.poisition = poisition;
	}

	public EntRoom(long id, String name, String poisition, Set tblOrderRooms) {
		this.id = id;
		this.name = name;
		this.poisition = poisition;
		this.tblOrderRooms = tblOrderRooms;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPoisition() {
		return this.poisition;
	}

	public void setPoisition(String poisition) {
		this.poisition = poisition;
	}

	public Set getTblOrderRooms() {
		return this.tblOrderRooms;
	}

	public void setTblOrderRooms(Set tblOrderRooms) {
		this.tblOrderRooms = tblOrderRooms;
	}

}
