package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * EntThirdPartyApi generated by hbm2java
 */
public class EntThirdPartyApi implements java.io.Serializable {

	private long id;
	private String name;
	private boolean enable;
	private String url;
	private String method;
	private boolean runAtServer;
	private String resultType;
	private String description;
	private Set tblThirdPartyApiParamses = new HashSet(0);
	private Set entThirdPartyApiParamsValues = new HashSet(0);
	private Set tblThirdPartyApiParams = new HashSet(0);
	private Set entThirdPartyApiParamValues = new HashSet(0);
	private Set entVoices = new HashSet(0);

	public EntThirdPartyApi() {
	}

	public EntThirdPartyApi(long id, String name, boolean enable, String url,
			String method, boolean runAtServer) {
		this.id = id;
		this.name = name;
		this.enable = enable;
		this.url = url;
		this.method = method;
		this.runAtServer = runAtServer;
	}

	public EntThirdPartyApi(long id, String name, boolean enable, String url,
			String method, boolean runAtServer, String resultType,
			String description, Set tblThirdPartyApiParamses,
			Set entThirdPartyApiParamsValues, Set tblThirdPartyApiParams,
			Set entThirdPartyApiParamValues, Set entVoices) {
		this.id = id;
		this.name = name;
		this.enable = enable;
		this.url = url;
		this.method = method;
		this.runAtServer = runAtServer;
		this.resultType = resultType;
		this.description = description;
		this.tblThirdPartyApiParamses = tblThirdPartyApiParamses;
		this.entThirdPartyApiParamsValues = entThirdPartyApiParamsValues;
		this.tblThirdPartyApiParams = tblThirdPartyApiParams;
		this.entThirdPartyApiParamValues = entThirdPartyApiParamValues;
		this.entVoices = entVoices;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public boolean isEnable() {
		return this.enable;
	}

	public void setEnable(boolean enable) {
		this.enable = enable;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getMethod() {
		return this.method;
	}

	public void setMethod(String method) {
		this.method = method;
	}

	public boolean isRunAtServer() {
		return this.runAtServer;
	}

	public void setRunAtServer(boolean runAtServer) {
		this.runAtServer = runAtServer;
	}

	public String getResultType() {
		return this.resultType;
	}

	public void setResultType(String resultType) {
		this.resultType = resultType;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set getTblThirdPartyApiParamses() {
		return this.tblThirdPartyApiParamses;
	}

	public void setTblThirdPartyApiParamses(Set tblThirdPartyApiParamses) {
		this.tblThirdPartyApiParamses = tblThirdPartyApiParamses;
	}

	public Set getEntThirdPartyApiParamsValues() {
		return this.entThirdPartyApiParamsValues;
	}

	public void setEntThirdPartyApiParamsValues(Set entThirdPartyApiParamsValues) {
		this.entThirdPartyApiParamsValues = entThirdPartyApiParamsValues;
	}

	public Set getTblThirdPartyApiParams() {
		return this.tblThirdPartyApiParams;
	}

	public void setTblThirdPartyApiParams(Set tblThirdPartyApiParams) {
		this.tblThirdPartyApiParams = tblThirdPartyApiParams;
	}

	public Set getEntThirdPartyApiParamValues() {
		return this.entThirdPartyApiParamValues;
	}

	public void setEntThirdPartyApiParamValues(Set entThirdPartyApiParamValues) {
		this.entThirdPartyApiParamValues = entThirdPartyApiParamValues;
	}

	public Set getEntVoices() {
		return this.entVoices;
	}

	public void setEntVoices(Set entVoices) {
		this.entVoices = entVoices;
	}

}
