package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * EntThirdPartyApiParam generated by hbm2java
 */
public class EntThirdPartyApiParam implements java.io.Serializable {

	private long id;
	private String name;
	private boolean header0Body1;
	private boolean optional;
	private String defaultValue;
	private String description;
	private Set tblThirdPartyApiParamValues = new HashSet(0);
	private Set tblThirdPartyApiParams = new HashSet(0);

	public EntThirdPartyApiParam() {
	}

	public EntThirdPartyApiParam(long id, String name, boolean header0Body1,
			boolean optional, String description) {
		this.id = id;
		this.name = name;
		this.header0Body1 = header0Body1;
		this.optional = optional;
		this.description = description;
	}

	public EntThirdPartyApiParam(long id, String name, boolean header0Body1,
			boolean optional, String defaultValue, String description,
			Set tblThirdPartyApiParamValues, Set tblThirdPartyApiParams) {
		this.id = id;
		this.name = name;
		this.header0Body1 = header0Body1;
		this.optional = optional;
		this.defaultValue = defaultValue;
		this.description = description;
		this.tblThirdPartyApiParamValues = tblThirdPartyApiParamValues;
		this.tblThirdPartyApiParams = tblThirdPartyApiParams;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public boolean isHeader0Body1() {
		return this.header0Body1;
	}

	public void setHeader0Body1(boolean header0Body1) {
		this.header0Body1 = header0Body1;
	}

	public boolean isOptional() {
		return this.optional;
	}

	public void setOptional(boolean optional) {
		this.optional = optional;
	}

	public String getDefaultValue() {
		return this.defaultValue;
	}

	public void setDefaultValue(String defaultValue) {
		this.defaultValue = defaultValue;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set getTblThirdPartyApiParamValues() {
		return this.tblThirdPartyApiParamValues;
	}

	public void setTblThirdPartyApiParamValues(Set tblThirdPartyApiParamValues) {
		this.tblThirdPartyApiParamValues = tblThirdPartyApiParamValues;
	}

	public Set getTblThirdPartyApiParams() {
		return this.tblThirdPartyApiParams;
	}

	public void setTblThirdPartyApiParams(Set tblThirdPartyApiParams) {
		this.tblThirdPartyApiParams = tblThirdPartyApiParams;
	}

}
