package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * EntThirdPartyApiParamValue generated by hbm2java
 */
public class EntThirdPartyApiParamValue implements java.io.Serializable {

	private long id;
	private EntThirdPartyApi entThirdPartyApi;
	private String name;
	private boolean enabled;
	private String description;
	private Set tblThirdPartyApiParamValues = new HashSet(0);
	private Set entVoices = new HashSet(0);

	public EntThirdPartyApiParamValue() {
	}

	public EntThirdPartyApiParamValue(long id,
			EntThirdPartyApi entThirdPartyApi, String name, boolean enabled) {
		this.id = id;
		this.entThirdPartyApi = entThirdPartyApi;
		this.name = name;
		this.enabled = enabled;
	}

	public EntThirdPartyApiParamValue(long id,
			EntThirdPartyApi entThirdPartyApi, String name, boolean enabled,
			String description, Set tblThirdPartyApiParamValues, Set entVoices) {
		this.id = id;
		this.entThirdPartyApi = entThirdPartyApi;
		this.name = name;
		this.enabled = enabled;
		this.description = description;
		this.tblThirdPartyApiParamValues = tblThirdPartyApiParamValues;
		this.entVoices = entVoices;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public EntThirdPartyApi getEntThirdPartyApi() {
		return this.entThirdPartyApi;
	}

	public void setEntThirdPartyApi(EntThirdPartyApi entThirdPartyApi) {
		this.entThirdPartyApi = entThirdPartyApi;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public boolean isEnabled() {
		return this.enabled;
	}

	public void setEnabled(boolean enabled) {
		this.enabled = enabled;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set getTblThirdPartyApiParamValues() {
		return this.tblThirdPartyApiParamValues;
	}

	public void setTblThirdPartyApiParamValues(Set tblThirdPartyApiParamValues) {
		this.tblThirdPartyApiParamValues = tblThirdPartyApiParamValues;
	}

	public Set getEntVoices() {
		return this.entVoices;
	}

	public void setEntVoices(Set entVoices) {
		this.entVoices = entVoices;
	}

}
