package org.sgpro.db;

// Generated 2017-6-9 18:47:30 by Hibernate Tools 4.0.0

/**
 * EntThirdPartyApiParamValueId generated by hbm2java
 */
public class EntThirdPartyApiParamValueId implements java.io.Serializable {

	private long id;
	private long thirdPartyApiId;

	public EntThirdPartyApiParamValueId() {
	}

	public EntThirdPartyApiParamValueId(long id, long thirdPartyApiId) {
		this.id = id;
		this.thirdPartyApiId = thirdPartyApiId;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public long getThirdPartyApiId() {
		return this.thirdPartyApiId;
	}

	public void setThirdPartyApiId(long thirdPartyApiId) {
		this.thirdPartyApiId = thirdPartyApiId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EntThirdPartyApiParamValueId))
			return false;
		EntThirdPartyApiParamValueId castOther = (EntThirdPartyApiParamValueId) other;

		return (this.getId() == castOther.getId())
				&& (this.getThirdPartyApiId() == castOther.getThirdPartyApiId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getId();
		result = 37 * result + (int) this.getThirdPartyApiId();
		return result;
	}

}
