package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * EntThirdPartyApiParamsValue generated by hbm2java
 */
public class EntThirdPartyApiParamsValue implements java.io.Serializable {

	private EntThirdPartyApiParamsValueId id;
	private EntThirdPartyApi entThirdPartyApi;
	private boolean enabled;
	private String descirption;
	private Set tblThirdPartyApiParamsValues = new HashSet(0);

	public EntThirdPartyApiParamsValue() {
	}

	public EntThirdPartyApiParamsValue(EntThirdPartyApiParamsValueId id,
			EntThirdPartyApi entThirdPartyApi, boolean enabled) {
		this.id = id;
		this.entThirdPartyApi = entThirdPartyApi;
		this.enabled = enabled;
	}

	public EntThirdPartyApiParamsValue(EntThirdPartyApiParamsValueId id,
			EntThirdPartyApi entThirdPartyApi, boolean enabled,
			String descirption, Set tblThirdPartyApiParamsValues) {
		this.id = id;
		this.entThirdPartyApi = entThirdPartyApi;
		this.enabled = enabled;
		this.descirption = descirption;
		this.tblThirdPartyApiParamsValues = tblThirdPartyApiParamsValues;
	}

	public EntThirdPartyApiParamsValueId getId() {
		return this.id;
	}

	public void setId(EntThirdPartyApiParamsValueId id) {
		this.id = id;
	}

	public EntThirdPartyApi getEntThirdPartyApi() {
		return this.entThirdPartyApi;
	}

	public void setEntThirdPartyApi(EntThirdPartyApi entThirdPartyApi) {
		this.entThirdPartyApi = entThirdPartyApi;
	}

	public boolean isEnabled() {
		return this.enabled;
	}

	public void setEnabled(boolean enabled) {
		this.enabled = enabled;
	}

	public String getDescirption() {
		return this.descirption;
	}

	public void setDescirption(String descirption) {
		this.descirption = descirption;
	}

	public Set getTblThirdPartyApiParamsValues() {
		return this.tblThirdPartyApiParamsValues;
	}

	public void setTblThirdPartyApiParamsValues(Set tblThirdPartyApiParamsValues) {
		this.tblThirdPartyApiParamsValues = tblThirdPartyApiParamsValues;
	}

}
