package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * EntUser generated by hbm2java
 */
public class EntUser implements java.io.Serializable {

	private long id;
	private EntUserGroup entUserGroup;
	private String name;
	private String password;
	private String description;
	private String email;
	private Set tblWordGroupFlowToVoiceGroupRuleOrignalsForUpdateUserId = new HashSet(
			0);
	private Set tblWordGroupFlowToVoiceGroupRuleOrignalsForCreateUserId = new HashSet(
			0);

	public EntUser() {
	}

	public EntUser(long id, EntUserGroup entUserGroup, String name,
			String password, String description, String email) {
		this.id = id;
		this.entUserGroup = entUserGroup;
		this.name = name;
		this.password = password;
		this.description = description;
		this.email = email;
	}

	public EntUser(long id, EntUserGroup entUserGroup, String name,
			String password, String description, String email,
			Set tblWordGroupFlowToVoiceGroupRuleOrignalsForUpdateUserId,
			Set tblWordGroupFlowToVoiceGroupRuleOrignalsForCreateUserId) {
		this.id = id;
		this.entUserGroup = entUserGroup;
		this.name = name;
		this.password = password;
		this.description = description;
		this.email = email;
		this.tblWordGroupFlowToVoiceGroupRuleOrignalsForUpdateUserId = tblWordGroupFlowToVoiceGroupRuleOrignalsForUpdateUserId;
		this.tblWordGroupFlowToVoiceGroupRuleOrignalsForCreateUserId = tblWordGroupFlowToVoiceGroupRuleOrignalsForCreateUserId;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public EntUserGroup getEntUserGroup() {
		return this.entUserGroup;
	}

	public void setEntUserGroup(EntUserGroup entUserGroup) {
		this.entUserGroup = entUserGroup;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Set getTblWordGroupFlowToVoiceGroupRuleOrignalsForUpdateUserId() {
		return this.tblWordGroupFlowToVoiceGroupRuleOrignalsForUpdateUserId;
	}

	public void setTblWordGroupFlowToVoiceGroupRuleOrignalsForUpdateUserId(
			Set tblWordGroupFlowToVoiceGroupRuleOrignalsForUpdateUserId) {
		this.tblWordGroupFlowToVoiceGroupRuleOrignalsForUpdateUserId = tblWordGroupFlowToVoiceGroupRuleOrignalsForUpdateUserId;
	}

	public Set getTblWordGroupFlowToVoiceGroupRuleOrignalsForCreateUserId() {
		return this.tblWordGroupFlowToVoiceGroupRuleOrignalsForCreateUserId;
	}

	public void setTblWordGroupFlowToVoiceGroupRuleOrignalsForCreateUserId(
			Set tblWordGroupFlowToVoiceGroupRuleOrignalsForCreateUserId) {
		this.tblWordGroupFlowToVoiceGroupRuleOrignalsForCreateUserId = tblWordGroupFlowToVoiceGroupRuleOrignalsForCreateUserId;
	}

}
