package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * EntVoiceCommand generated by hbm2java
 */
public class EntVoiceCommand implements java.io.Serializable {

	private long id;
	private String name;
	private String description;
	private Set entVoices = new HashSet(0);

	public EntVoiceCommand() {
	}

	public EntVoiceCommand(long id, String name) {
		this.id = id;
		this.name = name;
	}

	public EntVoiceCommand(long id, String name, String description,
			Set entVoices) {
		this.id = id;
		this.name = name;
		this.description = description;
		this.entVoices = entVoices;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set getEntVoices() {
		return this.entVoices;
	}

	public void setEntVoices(Set entVoices) {
		this.entVoices = entVoices;
	}

}
