package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * EntVoice generated by hbm2java
 */
public class EntVoice implements java.io.Serializable {

	private long id;
	private EntThirdPartyApi entThirdPartyApi;
	private EntThirdPartyApiParamValue entThirdPartyApiParamValue;
	private EntVoiceCommand entVoiceCommand;
	private String name;
	private String path;
	private String emotion;
	private String text;
	private String commandParam;
	private String incProp;
	private String excProp;
	private String cat;
	private Long fixedParam1;
	private Long fixedParam2;
	private Long fixedParam3;
	private Long fixedParam4;
	private Long fixedParam5;
	private boolean enabled;
	private String description;
	private Set tblWordGroupFlowToVoiceGroupRuleOrignals = new HashSet(0);
	private Set tblVoiceTags = new HashSet(0);
	private Set tblVoiceGroups = new HashSet(0);

	public EntVoice() {
	}

	public EntVoice(long id, String name, String cat, boolean enabled,
			String description) {
		this.id = id;
		this.name = name;
		this.cat = cat;
		this.enabled = enabled;
		this.description = description;
	}

	public EntVoice(long id, EntThirdPartyApi entThirdPartyApi,
			EntThirdPartyApiParamValue entThirdPartyApiParamValue,
			EntVoiceCommand entVoiceCommand, String name, String path,
			String emotion, String text, String commandParam, String incProp,
			String excProp, String cat, Long fixedParam1, Long fixedParam2,
			Long fixedParam3, Long fixedParam4, Long fixedParam5,
			boolean enabled, String description,
			Set tblWordGroupFlowToVoiceGroupRuleOrignals, Set tblVoiceTags,
			Set tblVoiceGroups) {
		this.id = id;
		this.entThirdPartyApi = entThirdPartyApi;
		this.entThirdPartyApiParamValue = entThirdPartyApiParamValue;
		this.entVoiceCommand = entVoiceCommand;
		this.name = name;
		this.path = path;
		this.emotion = emotion;
		this.text = text;
		this.commandParam = commandParam;
		this.incProp = incProp;
		this.excProp = excProp;
		this.cat = cat;
		this.fixedParam1 = fixedParam1;
		this.fixedParam2 = fixedParam2;
		this.fixedParam3 = fixedParam3;
		this.fixedParam4 = fixedParam4;
		this.fixedParam5 = fixedParam5;
		this.enabled = enabled;
		this.description = description;
		this.tblWordGroupFlowToVoiceGroupRuleOrignals = tblWordGroupFlowToVoiceGroupRuleOrignals;
		this.tblVoiceTags = tblVoiceTags;
		this.tblVoiceGroups = tblVoiceGroups;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public EntThirdPartyApi getEntThirdPartyApi() {
		return this.entThirdPartyApi;
	}

	public void setEntThirdPartyApi(EntThirdPartyApi entThirdPartyApi) {
		this.entThirdPartyApi = entThirdPartyApi;
	}

	public EntThirdPartyApiParamValue getEntThirdPartyApiParamValue() {
		return this.entThirdPartyApiParamValue;
	}

	public void setEntThirdPartyApiParamValue(
			EntThirdPartyApiParamValue entThirdPartyApiParamValue) {
		this.entThirdPartyApiParamValue = entThirdPartyApiParamValue;
	}

	public EntVoiceCommand getEntVoiceCommand() {
		return this.entVoiceCommand;
	}

	public void setEntVoiceCommand(EntVoiceCommand entVoiceCommand) {
		this.entVoiceCommand = entVoiceCommand;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPath() {
		return this.path;
	}

	public void setPath(String path) {
		this.path = path;
	}

	public String getEmotion() {
		return this.emotion;
	}

	public void setEmotion(String emotion) {
		this.emotion = emotion;
	}

	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

	public String getCommandParam() {
		return this.commandParam;
	}

	public void setCommandParam(String commandParam) {
		this.commandParam = commandParam;
	}

	public String getIncProp() {
		return this.incProp;
	}

	public void setIncProp(String incProp) {
		this.incProp = incProp;
	}

	public String getExcProp() {
		return this.excProp;
	}

	public void setExcProp(String excProp) {
		this.excProp = excProp;
	}

	public String getCat() {
		return this.cat;
	}

	public void setCat(String cat) {
		this.cat = cat;
	}

	public Long getFixedParam1() {
		return this.fixedParam1;
	}

	public void setFixedParam1(Long fixedParam1) {
		this.fixedParam1 = fixedParam1;
	}

	public Long getFixedParam2() {
		return this.fixedParam2;
	}

	public void setFixedParam2(Long fixedParam2) {
		this.fixedParam2 = fixedParam2;
	}

	public Long getFixedParam3() {
		return this.fixedParam3;
	}

	public void setFixedParam3(Long fixedParam3) {
		this.fixedParam3 = fixedParam3;
	}

	public Long getFixedParam4() {
		return this.fixedParam4;
	}

	public void setFixedParam4(Long fixedParam4) {
		this.fixedParam4 = fixedParam4;
	}

	public Long getFixedParam5() {
		return this.fixedParam5;
	}

	public void setFixedParam5(Long fixedParam5) {
		this.fixedParam5 = fixedParam5;
	}

	public boolean isEnabled() {
		return this.enabled;
	}

	public void setEnabled(boolean enabled) {
		this.enabled = enabled;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set getTblWordGroupFlowToVoiceGroupRuleOrignals() {
		return this.tblWordGroupFlowToVoiceGroupRuleOrignals;
	}

	public void setTblWordGroupFlowToVoiceGroupRuleOrignals(
			Set tblWordGroupFlowToVoiceGroupRuleOrignals) {
		this.tblWordGroupFlowToVoiceGroupRuleOrignals = tblWordGroupFlowToVoiceGroupRuleOrignals;
	}

	public Set getTblVoiceTags() {
		return this.tblVoiceTags;
	}

	public void setTblVoiceTags(Set tblVoiceTags) {
		this.tblVoiceTags = tblVoiceTags;
	}

	public Set getTblVoiceGroups() {
		return this.tblVoiceGroups;
	}

	public void setTblVoiceGroups(Set tblVoiceGroups) {
		this.tblVoiceGroups = tblVoiceGroups;
	}

}
