package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * EntVisitors generated by hbm2java
 */
public class EntVisitors implements java.io.Serializable {

	private long id;
	private String name;
	private String phone;
	private String company;
	private String event;
	private String tareget;
	private Date dateTime;

	public EntVisitors() {
	}

	public EntVisitors(long id, String name, String phone, String company,
			String event, String tareget) {
		this.id = id;
		this.name = name;
		this.phone = phone;
		this.company = company;
		this.event = event;
		this.tareget = tareget;
	}

	public EntVisitors(long id, String name, String phone, String company,
			String event, String tareget, Date dateTime) {
		this.id = id;
		this.name = name;
		this.phone = phone;
		this.company = company;
		this.event = event;
		this.tareget = tareget;
		this.dateTime = dateTime;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getCompany() {
		return this.company;
	}

	public void setCompany(String company) {
		this.company = company;
	}

	public String getEvent() {
		return this.event;
	}

	public void setEvent(String event) {
		this.event = event;
	}

	public String getTareget() {
		return this.tareget;
	}

	public void setTareget(String tareget) {
		this.tareget = tareget;
	}

	public Date getDateTime() {
		return this.dateTime;
	}

	public void setDateTime(Date dateTime) {
		this.dateTime = dateTime;
	}

}
