package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * EntVoiceGroup generated by hbm2java
 */
public class EntVoiceGroup implements java.io.Serializable {

	private long id;
	private String name;
	private String description;
	private Set tblWordGroupFlowToVoiceGroupRules = new HashSet(0);
	private Set tblVoiceGroups = new HashSet(0);

	public EntVoiceGroup() {
	}

	public EntVoiceGroup(long id, String name) {
		this.id = id;
		this.name = name;
	}

	public EntVoiceGroup(long id, String name, String description,
			Set tblWordGroupFlowToVoiceGroupRules, Set tblVoiceGroups) {
		this.id = id;
		this.name = name;
		this.description = description;
		this.tblWordGroupFlowToVoiceGroupRules = tblWordGroupFlowToVoiceGroupRules;
		this.tblVoiceGroups = tblVoiceGroups;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set getTblWordGroupFlowToVoiceGroupRules() {
		return this.tblWordGroupFlowToVoiceGroupRules;
	}

	public void setTblWordGroupFlowToVoiceGroupRules(
			Set tblWordGroupFlowToVoiceGroupRules) {
		this.tblWordGroupFlowToVoiceGroupRules = tblWordGroupFlowToVoiceGroupRules;
	}

	public Set getTblVoiceGroups() {
		return this.tblVoiceGroups;
	}

	public void setTblVoiceGroups(Set tblVoiceGroups) {
		this.tblVoiceGroups = tblVoiceGroups;
	}

}
