package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * EntWordGroup generated by hbm2java
 */
public class EntWordGroup implements java.io.Serializable {

	private long id;
	private String name;
	private String description;
	private Set tblWordGroups = new HashSet(0);
	private Set tblWordGroupFlows = new HashSet(0);

	public EntWordGroup() {
	}

	public EntWordGroup(long id, String name) {
		this.id = id;
		this.name = name;
	}

	public EntWordGroup(long id, String name, String description,
			Set tblWordGroups, Set tblWordGroupFlows) {
		this.id = id;
		this.name = name;
		this.description = description;
		this.tblWordGroups = tblWordGroups;
		this.tblWordGroupFlows = tblWordGroupFlows;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set getTblWordGroups() {
		return this.tblWordGroups;
	}

	public void setTblWordGroups(Set tblWordGroups) {
		this.tblWordGroups = tblWordGroups;
	}

	public Set getTblWordGroupFlows() {
		return this.tblWordGroupFlows;
	}

	public void setTblWordGroupFlows(Set tblWordGroupFlows) {
		this.tblWordGroupFlows = tblWordGroupFlows;
	}

}
