package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * TblBizMenuitemAction generated by hbm2java
 */
public class TblBizMenuitemAction implements java.io.Serializable {

	private long id;
	private String action;
	private String uri;
	private String type;
	private String extra;
	private String packageName;
	private String className;
	private String description;
	private Set tblBizMenutrees = new HashSet(0);

	public TblBizMenuitemAction() {
	}

	public TblBizMenuitemAction(long id) {
		this.id = id;
	}

	public TblBizMenuitemAction(long id, String action, String uri,
			String type, String extra, String packageName, String className,
			String description, Set tblBizMenutrees) {
		this.id = id;
		this.action = action;
		this.uri = uri;
		this.type = type;
		this.extra = extra;
		this.packageName = packageName;
		this.className = className;
		this.description = description;
		this.tblBizMenutrees = tblBizMenutrees;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getAction() {
		return this.action;
	}

	public void setAction(String action) {
		this.action = action;
	}

	public String getUri() {
		return this.uri;
	}

	public void setUri(String uri) {
		this.uri = uri;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getExtra() {
		return this.extra;
	}

	public void setExtra(String extra) {
		this.extra = extra;
	}

	public String getPackageName() {
		return this.packageName;
	}

	public void setPackageName(String packageName) {
		this.packageName = packageName;
	}

	public String getClassName() {
		return this.className;
	}

	public void setClassName(String className) {
		this.className = className;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set getTblBizMenutrees() {
		return this.tblBizMenutrees;
	}

	public void setTblBizMenutrees(Set tblBizMenutrees) {
		this.tblBizMenutrees = tblBizMenutrees;
	}

}
