package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * TblCustomizedConfigForRobotId generated by hbm2java
 */
public class TblCustomizedConfigForRobotId implements java.io.Serializable {

	private long robotId;
	private String name;

	public TblCustomizedConfigForRobotId() {
	}

	public TblCustomizedConfigForRobotId(long robotId, String name) {
		this.robotId = robotId;
		this.name = name;
	}

	public long getRobotId() {
		return this.robotId;
	}

	public void setRobotId(long robotId) {
		this.robotId = robotId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TblCustomizedConfigForRobotId))
			return false;
		TblCustomizedConfigForRobotId castOther = (TblCustomizedConfigForRobotId) other;

		return (this.getRobotId() == castOther.getRobotId())
				&& ((this.getName() == castOther.getName()) || (this.getName() != null
						&& castOther.getName() != null && this.getName()
						.equals(castOther.getName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getRobotId();
		result = 37 * result
				+ (getName() == null ? 0 : this.getName().hashCode());
		return result;
	}

}
