package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * TblCustomizedConfigForUserGroupId generated by hbm2java
 */
public class TblCustomizedConfigForUserGroupId implements java.io.Serializable {

	private long userGroupId;
	private String name;

	public TblCustomizedConfigForUserGroupId() {
	}

	public TblCustomizedConfigForUserGroupId(long userGroupId, String name) {
		this.userGroupId = userGroupId;
		this.name = name;
	}

	public long getUserGroupId() {
		return this.userGroupId;
	}

	public void setUserGroupId(long userGroupId) {
		this.userGroupId = userGroupId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TblCustomizedConfigForUserGroupId))
			return false;
		TblCustomizedConfigForUserGroupId castOther = (TblCustomizedConfigForUserGroupId) other;

		return (this.getUserGroupId() == castOther.getUserGroupId())
				&& ((this.getName() == castOther.getName()) || (this.getName() != null
						&& castOther.getName() != null && this.getName()
						.equals(castOther.getName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getUserGroupId();
		result = 37 * result
				+ (getName() == null ? 0 : this.getName().hashCode());
		return result;
	}

}
