package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * TblCustomizedConfigForUserGroup generated by hbm2java
 */
public class TblCustomizedConfigForUserGroup implements java.io.Serializable {

	private TblCustomizedConfigForUserGroupId id;
	private EntConfig entConfig;
	private EntUserGroup entUserGroup;
	private String value;
	private String description;

	public TblCustomizedConfigForUserGroup() {
	}

	public TblCustomizedConfigForUserGroup(
			TblCustomizedConfigForUserGroupId id, EntConfig entConfig,
			EntUserGroup entUserGroup, String value, String description) {
		this.id = id;
		this.entConfig = entConfig;
		this.entUserGroup = entUserGroup;
		this.value = value;
		this.description = description;
	}

	public TblCustomizedConfigForUserGroupId getId() {
		return this.id;
	}

	public void setId(TblCustomizedConfigForUserGroupId id) {
		this.id = id;
	}

	public EntConfig getEntConfig() {
		return this.entConfig;
	}

	public void setEntConfig(EntConfig entConfig) {
		this.entConfig = entConfig;
	}

	public EntUserGroup getEntUserGroup() {
		return this.entUserGroup;
	}

	public void setEntUserGroup(EntUserGroup entUserGroup) {
		this.entUserGroup = entUserGroup;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
