package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * TblCustomizedConfigForHwSpec generated by hbm2java
 */
public class TblCustomizedConfigForHwSpec implements java.io.Serializable {

	private TblCustomizedConfigForHwSpecId id;
	private EntConfig entConfig;
	private EntHwSpec entHwSpec;
	private String value;
	private String description;

	public TblCustomizedConfigForHwSpec() {
	}

	public TblCustomizedConfigForHwSpec(TblCustomizedConfigForHwSpecId id,
			EntConfig entConfig, EntHwSpec entHwSpec, String value,
			String description) {
		this.id = id;
		this.entConfig = entConfig;
		this.entHwSpec = entHwSpec;
		this.value = value;
		this.description = description;
	}

	public TblCustomizedConfigForHwSpecId getId() {
		return this.id;
	}

	public void setId(TblCustomizedConfigForHwSpecId id) {
		this.id = id;
	}

	public EntConfig getEntConfig() {
		return this.entConfig;
	}

	public void setEntConfig(EntConfig entConfig) {
		this.entConfig = entConfig;
	}

	public EntHwSpec getEntHwSpec() {
		return this.entHwSpec;
	}

	public void setEntHwSpec(EntHwSpec entHwSpec) {
		this.entHwSpec = entHwSpec;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
