package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * TblCustomizedConfigForIndustryId generated by hbm2java
 */
public class TblCustomizedConfigForIndustryId implements java.io.Serializable {

	private long industryId;
	private String name;

	public TblCustomizedConfigForIndustryId() {
	}

	public TblCustomizedConfigForIndustryId(long industryId, String name) {
		this.industryId = industryId;
		this.name = name;
	}

	public long getIndustryId() {
		return this.industryId;
	}

	public void setIndustryId(long industryId) {
		this.industryId = industryId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TblCustomizedConfigForIndustryId))
			return false;
		TblCustomizedConfigForIndustryId castOther = (TblCustomizedConfigForIndustryId) other;

		return (this.getIndustryId() == castOther.getIndustryId())
				&& ((this.getName() == castOther.getName()) || (this.getName() != null
						&& castOther.getName() != null && this.getName()
						.equals(castOther.getName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getIndustryId();
		result = 37 * result
				+ (getName() == null ? 0 : this.getName().hashCode());
		return result;
	}

}
