package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * TblCustomizedConfigForUserGroupScene generated by hbm2java
 */
public class TblCustomizedConfigForUserGroupScene implements
		java.io.Serializable {

	private TblCustomizedConfigForUserGroupSceneId id;
	private EntConfig entConfig;
	private TblUserGroupScene tblUserGroupScene;
	private String value;
	private String description;

	public TblCustomizedConfigForUserGroupScene() {
	}

	public TblCustomizedConfigForUserGroupScene(
			TblCustomizedConfigForUserGroupSceneId id, EntConfig entConfig,
			TblUserGroupScene tblUserGroupScene, String value,
			String description) {
		this.id = id;
		this.entConfig = entConfig;
		this.tblUserGroupScene = tblUserGroupScene;
		this.value = value;
		this.description = description;
	}

	public TblCustomizedConfigForUserGroupSceneId getId() {
		return this.id;
	}

	public void setId(TblCustomizedConfigForUserGroupSceneId id) {
		this.id = id;
	}

	public EntConfig getEntConfig() {
		return this.entConfig;
	}

	public void setEntConfig(EntConfig entConfig) {
		this.entConfig = entConfig;
	}

	public TblUserGroupScene getTblUserGroupScene() {
		return this.tblUserGroupScene;
	}

	public void setTblUserGroupScene(TblUserGroupScene tblUserGroupScene) {
		this.tblUserGroupScene = tblUserGroupScene;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
