package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * TblHuaqin2016ProviderConfrencePaticipants generated by hbm2java
 */
public class TblHuaqin2016ProviderConfrencePaticipants implements
		java.io.Serializable {

	private String name;
	private EntHuaqin2016ProviderConfrenceCompany entHuaqin2016ProviderConfrenceCompany;
	private long id;
	private long mettingRowNum;
	private long mettingColNum;
	private String dinnerNo;
	private boolean enabled;

	public TblHuaqin2016ProviderConfrencePaticipants() {
	}

	public TblHuaqin2016ProviderConfrencePaticipants(
			String name,
			EntHuaqin2016ProviderConfrenceCompany entHuaqin2016ProviderConfrenceCompany,
			long id, long mettingRowNum, long mettingColNum, String dinnerNo,
			boolean enabled) {
		this.name = name;
		this.entHuaqin2016ProviderConfrenceCompany = entHuaqin2016ProviderConfrenceCompany;
		this.id = id;
		this.mettingRowNum = mettingRowNum;
		this.mettingColNum = mettingColNum;
		this.dinnerNo = dinnerNo;
		this.enabled = enabled;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public EntHuaqin2016ProviderConfrenceCompany getEntHuaqin2016ProviderConfrenceCompany() {
		return this.entHuaqin2016ProviderConfrenceCompany;
	}

	public void setEntHuaqin2016ProviderConfrenceCompany(
			EntHuaqin2016ProviderConfrenceCompany entHuaqin2016ProviderConfrenceCompany) {
		this.entHuaqin2016ProviderConfrenceCompany = entHuaqin2016ProviderConfrenceCompany;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public long getMettingRowNum() {
		return this.mettingRowNum;
	}

	public void setMettingRowNum(long mettingRowNum) {
		this.mettingRowNum = mettingRowNum;
	}

	public long getMettingColNum() {
		return this.mettingColNum;
	}

	public void setMettingColNum(long mettingColNum) {
		this.mettingColNum = mettingColNum;
	}

	public String getDinnerNo() {
		return this.dinnerNo;
	}

	public void setDinnerNo(String dinnerNo) {
		this.dinnerNo = dinnerNo;
	}

	public boolean isEnabled() {
		return this.enabled;
	}

	public void setEnabled(boolean enabled) {
		this.enabled = enabled;
	}

}
