package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * TblInheritConfigForUserGroup generated by hbm2java
 */
public class TblInheritConfigForUserGroup implements java.io.Serializable {

	private TblInheritConfigForUserGroupId id;
	private EntUserGroup entUserGroup;
	private EntConfig entConfig;
	private String value;

	public TblInheritConfigForUserGroup() {
	}

	public TblInheritConfigForUserGroup(TblInheritConfigForUserGroupId id,
			EntUserGroup entUserGroup, EntConfig entConfig, String value) {
		this.id = id;
		this.entUserGroup = entUserGroup;
		this.entConfig = entConfig;
		this.value = value;
	}

	public TblInheritConfigForUserGroupId getId() {
		return this.id;
	}

	public void setId(TblInheritConfigForUserGroupId id) {
		this.id = id;
	}

	public EntUserGroup getEntUserGroup() {
		return this.entUserGroup;
	}

	public void setEntUserGroup(EntUserGroup entUserGroup) {
		this.entUserGroup = entUserGroup;
	}

	public EntConfig getEntConfig() {
		return this.entConfig;
	}

	public void setEntConfig(EntConfig entConfig) {
		this.entConfig = entConfig;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
