package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * TblInheritConfigForUserGroupId generated by hbm2java
 */
public class TblInheritConfigForUserGroupId implements java.io.Serializable {

	private long userGroupId;
	private String configName;

	public TblInheritConfigForUserGroupId() {
	}

	public TblInheritConfigForUserGroupId(long userGroupId, String configName) {
		this.userGroupId = userGroupId;
		this.configName = configName;
	}

	public long getUserGroupId() {
		return this.userGroupId;
	}

	public void setUserGroupId(long userGroupId) {
		this.userGroupId = userGroupId;
	}

	public String getConfigName() {
		return this.configName;
	}

	public void setConfigName(String configName) {
		this.configName = configName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TblInheritConfigForUserGroupId))
			return false;
		TblInheritConfigForUserGroupId castOther = (TblInheritConfigForUserGroupId) other;

		return (this.getUserGroupId() == castOther.getUserGroupId())
				&& ((this.getConfigName() == castOther.getConfigName()) || (this
						.getConfigName() != null
						&& castOther.getConfigName() != null && this
						.getConfigName().equals(castOther.getConfigName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getUserGroupId();
		result = 37
				* result
				+ (getConfigName() == null ? 0 : this.getConfigName()
						.hashCode());
		return result;
	}

}
