package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * TblMlDialog generated by hbm2java
 */
public class TblMlDialog implements java.io.Serializable {

	private TblMlDialogId id;

	public TblMlDialog() {
	}

	public TblMlDialog(TblMlDialogId id) {
		this.id = id;
	}

	public TblMlDialogId getId() {
		return this.id;
	}

	public void setId(TblMlDialogId id) {
		this.id = id;
	}

}
