package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * TblNews generated by hbm2java
 */
public class TblNews implements java.io.Serializable {

	private long id;
	private Date newsTime;
	private byte[] pictures;
	private String title;
	private String content;

	public TblNews() {
	}

	public TblNews(long id, String title, String content) {
		this.id = id;
		this.title = title;
		this.content = content;
	}

	public TblNews(long id, Date newsTime, byte[] pictures, String title,
			String content) {
		this.id = id;
		this.newsTime = newsTime;
		this.pictures = pictures;
		this.title = title;
		this.content = content;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Date getNewsTime() {
		return this.newsTime;
	}

	public void setNewsTime(Date newsTime) {
		this.newsTime = newsTime;
	}

	public byte[] getPictures() {
		return this.pictures;
	}

	public void setPictures(byte[] pictures) {
		this.pictures = pictures;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

}
