package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * TblOrderRoom generated by hbm2java
 */
public class TblOrderRoom implements java.io.Serializable {

	private TblOrderRoomId id;
	private EntRoom entRoom;
	private String orderName;
	private String mobilePhone;
	private Date submitDatetime;

	public TblOrderRoom() {
	}

	public TblOrderRoom(TblOrderRoomId id, EntRoom entRoom, String orderName,
			String mobilePhone, Date submitDatetime) {
		this.id = id;
		this.entRoom = entRoom;
		this.orderName = orderName;
		this.mobilePhone = mobilePhone;
		this.submitDatetime = submitDatetime;
	}

	public TblOrderRoomId getId() {
		return this.id;
	}

	public void setId(TblOrderRoomId id) {
		this.id = id;
	}

	public EntRoom getEntRoom() {
		return this.entRoom;
	}

	public void setEntRoom(EntRoom entRoom) {
		this.entRoom = entRoom;
	}

	public String getOrderName() {
		return this.orderName;
	}

	public void setOrderName(String orderName) {
		this.orderName = orderName;
	}

	public String getMobilePhone() {
		return this.mobilePhone;
	}

	public void setMobilePhone(String mobilePhone) {
		this.mobilePhone = mobilePhone;
	}

	public Date getSubmitDatetime() {
		return this.submitDatetime;
	}

	public void setSubmitDatetime(Date submitDatetime) {
		this.submitDatetime = submitDatetime;
	}

}
