package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * TblQuestionAnswerCandidatesId generated by hbm2java
 */
public class TblQuestionAnswerCandidatesId implements java.io.Serializable {

	private long questionId;
	private String label;

	public TblQuestionAnswerCandidatesId() {
	}

	public TblQuestionAnswerCandidatesId(long questionId, String label) {
		this.questionId = questionId;
		this.label = label;
	}

	public long getQuestionId() {
		return this.questionId;
	}

	public void setQuestionId(long questionId) {
		this.questionId = questionId;
	}

	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TblQuestionAnswerCandidatesId))
			return false;
		TblQuestionAnswerCandidatesId castOther = (TblQuestionAnswerCandidatesId) other;

		return (this.getQuestionId() == castOther.getQuestionId())
				&& ((this.getLabel() == castOther.getLabel()) || (this
						.getLabel() != null && castOther.getLabel() != null && this
						.getLabel().equals(castOther.getLabel())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getQuestionId();
		result = 37 * result
				+ (getLabel() == null ? 0 : this.getLabel().hashCode());
		return result;
	}

}
