package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * TblQuestion generated by hbm2java
 */
public class TblQuestion implements java.io.Serializable {

	private long id;
	private EntExam entExam;
	private String title;
	private long QIndex;
	private String description;
	private Set tblQuestionAnswerCandidateses = new HashSet(0);

	public TblQuestion() {
	}

	public TblQuestion(long id, EntExam entExam, String title, long QIndex) {
		this.id = id;
		this.entExam = entExam;
		this.title = title;
		this.QIndex = QIndex;
	}

	public TblQuestion(long id, EntExam entExam, String title, long QIndex,
			String description, Set tblQuestionAnswerCandidateses) {
		this.id = id;
		this.entExam = entExam;
		this.title = title;
		this.QIndex = QIndex;
		this.description = description;
		this.tblQuestionAnswerCandidateses = tblQuestionAnswerCandidateses;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public EntExam getEntExam() {
		return this.entExam;
	}

	public void setEntExam(EntExam entExam) {
		this.entExam = entExam;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public long getQIndex() {
		return this.QIndex;
	}

	public void setQIndex(long QIndex) {
		this.QIndex = QIndex;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set getTblQuestionAnswerCandidateses() {
		return this.tblQuestionAnswerCandidateses;
	}

	public void setTblQuestionAnswerCandidateses(
			Set tblQuestionAnswerCandidateses) {
		this.tblQuestionAnswerCandidateses = tblQuestionAnswerCandidateses;
	}

}
