package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * TblQuestionAnswerCandidates generated by hbm2java
 */
public class TblQuestionAnswerCandidates implements java.io.Serializable {

	private TblQuestionAnswerCandidatesId id;
	private TblQuestion tblQuestion;
	private long CIndex;
	private String CContent;
	private boolean theAnswer;

	public TblQuestionAnswerCandidates() {
	}

	public TblQuestionAnswerCandidates(TblQuestionAnswerCandidatesId id,
			TblQuestion tblQuestion, long CIndex, String CContent,
			boolean theAnswer) {
		this.id = id;
		this.tblQuestion = tblQuestion;
		this.CIndex = CIndex;
		this.CContent = CContent;
		this.theAnswer = theAnswer;
	}

	public TblQuestionAnswerCandidatesId getId() {
		return this.id;
	}

	public void setId(TblQuestionAnswerCandidatesId id) {
		this.id = id;
	}

	public TblQuestion getTblQuestion() {
		return this.tblQuestion;
	}

	public void setTblQuestion(TblQuestion tblQuestion) {
		this.tblQuestion = tblQuestion;
	}

	public long getCIndex() {
		return this.CIndex;
	}

	public void setCIndex(long CIndex) {
		this.CIndex = CIndex;
	}

	public String getCContent() {
		return this.CContent;
	}

	public void setCContent(String CContent) {
		this.CContent = CContent;
	}

	public boolean isTheAnswer() {
		return this.theAnswer;
	}

	public void setTheAnswer(boolean theAnswer) {
		this.theAnswer = theAnswer;
	}

}
