package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * TblRobotSessionContextId generated by hbm2java
 */
public class TblRobotSessionContextId implements java.io.Serializable {

	private long robotId;
	private String ctxName;

	public TblRobotSessionContextId() {
	}

	public TblRobotSessionContextId(long robotId, String ctxName) {
		this.robotId = robotId;
		this.ctxName = ctxName;
	}

	public long getRobotId() {
		return this.robotId;
	}

	public void setRobotId(long robotId) {
		this.robotId = robotId;
	}

	public String getCtxName() {
		return this.ctxName;
	}

	public void setCtxName(String ctxName) {
		this.ctxName = ctxName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TblRobotSessionContextId))
			return false;
		TblRobotSessionContextId castOther = (TblRobotSessionContextId) other;

		return (this.getRobotId() == castOther.getRobotId())
				&& ((this.getCtxName() == castOther.getCtxName()) || (this
						.getCtxName() != null && castOther.getCtxName() != null && this
						.getCtxName().equals(castOther.getCtxName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getRobotId();
		result = 37 * result
				+ (getCtxName() == null ? 0 : this.getCtxName().hashCode());
		return result;
	}

}
