package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * TblRequestProperty generated by hbm2java
 */
public class TblRequestProperty implements java.io.Serializable {

	private TblRequestPropertyId id;
	private EntRequest entRequest;
	private String propertyValue;
	private boolean isNumeric;

	public TblRequestProperty() {
	}

	public TblRequestProperty(TblRequestPropertyId id, EntRequest entRequest,
			String propertyValue, boolean isNumeric) {
		this.id = id;
		this.entRequest = entRequest;
		this.propertyValue = propertyValue;
		this.isNumeric = isNumeric;
	}

	public TblRequestPropertyId getId() {
		return this.id;
	}

	public void setId(TblRequestPropertyId id) {
		this.id = id;
	}

	public EntRequest getEntRequest() {
		return this.entRequest;
	}

	public void setEntRequest(EntRequest entRequest) {
		this.entRequest = entRequest;
	}

	public String getPropertyValue() {
		return this.propertyValue;
	}

	public void setPropertyValue(String propertyValue) {
		this.propertyValue = propertyValue;
	}

	public boolean isIsNumeric() {
		return this.isNumeric;
	}

	public void setIsNumeric(boolean isNumeric) {
		this.isNumeric = isNumeric;
	}

}
