package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * TblRobotSessionContext generated by hbm2java
 */
public class TblRobotSessionContext implements java.io.Serializable {

	private TblRobotSessionContextId id;
	private EntRobot entRobot;
	private String ctxValue;
	private long exprSecs;
	private String description;
	private Date createDatetime;

	public TblRobotSessionContext() {
	}

	public TblRobotSessionContext(TblRobotSessionContextId id,
			EntRobot entRobot, long exprSecs, Date createDatetime) {
		this.id = id;
		this.entRobot = entRobot;
		this.exprSecs = exprSecs;
		this.createDatetime = createDatetime;
	}

	public TblRobotSessionContext(TblRobotSessionContextId id,
			EntRobot entRobot, String ctxValue, long exprSecs,
			String description, Date createDatetime) {
		this.id = id;
		this.entRobot = entRobot;
		this.ctxValue = ctxValue;
		this.exprSecs = exprSecs;
		this.description = description;
		this.createDatetime = createDatetime;
	}

	public TblRobotSessionContextId getId() {
		return this.id;
	}

	public void setId(TblRobotSessionContextId id) {
		this.id = id;
	}

	public EntRobot getEntRobot() {
		return this.entRobot;
	}

	public void setEntRobot(EntRobot entRobot) {
		this.entRobot = entRobot;
	}

	public String getCtxValue() {
		return this.ctxValue;
	}

	public void setCtxValue(String ctxValue) {
		this.ctxValue = ctxValue;
	}

	public long getExprSecs() {
		return this.exprSecs;
	}

	public void setExprSecs(long exprSecs) {
		this.exprSecs = exprSecs;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Date getCreateDatetime() {
		return this.createDatetime;
	}

	public void setCreateDatetime(Date createDatetime) {
		this.createDatetime = createDatetime;
	}

}
