package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * TblRuntime generated by hbm2java
 */
public class TblRuntime implements java.io.Serializable {

	private long id;
	private String robotImei;
	private String message;
	private String description;
	private String note;
	private Date dateTime;

	public TblRuntime() {
	}

	public TblRuntime(long id, String robotImei, String message,
			String description, String note) {
		this.id = id;
		this.robotImei = robotImei;
		this.message = message;
		this.description = description;
		this.note = note;
	}

	public TblRuntime(long id, String robotImei, String message,
			String description, String note, Date dateTime) {
		this.id = id;
		this.robotImei = robotImei;
		this.message = message;
		this.description = description;
		this.note = note;
		this.dateTime = dateTime;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getRobotImei() {
		return this.robotImei;
	}

	public void setRobotImei(String robotImei) {
		this.robotImei = robotImei;
	}

	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public Date getDateTime() {
		return this.dateTime;
	}

	public void setDateTime(Date dateTime) {
		this.dateTime = dateTime;
	}

}
