package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * TblRequestPropertyId generated by hbm2java
 */
public class TblRequestPropertyId implements java.io.Serializable {

	private String requestId;
	private String propertyName;

	public TblRequestPropertyId() {
	}

	public TblRequestPropertyId(String requestId, String propertyName) {
		this.requestId = requestId;
		this.propertyName = propertyName;
	}

	public String getRequestId() {
		return this.requestId;
	}

	public void setRequestId(String requestId) {
		this.requestId = requestId;
	}

	public String getPropertyName() {
		return this.propertyName;
	}

	public void setPropertyName(String propertyName) {
		this.propertyName = propertyName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TblRequestPropertyId))
			return false;
		TblRequestPropertyId castOther = (TblRequestPropertyId) other;

		return ((this.getRequestId() == castOther.getRequestId()) || (this
				.getRequestId() != null && castOther.getRequestId() != null && this
				.getRequestId().equals(castOther.getRequestId())))
				&& ((this.getPropertyName() == castOther.getPropertyName()) || (this
						.getPropertyName() != null
						&& castOther.getPropertyName() != null && this
						.getPropertyName().equals(castOther.getPropertyName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getRequestId() == null ? 0 : this.getRequestId().hashCode());
		result = 37
				* result
				+ (getPropertyName() == null ? 0 : this.getPropertyName()
						.hashCode());
		return result;
	}

}
