package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * TblRtcSession generated by hbm2java
 */
public class TblRtcSession implements java.io.Serializable {

	private long id;
	private long robotId;
	private long userId;
	private boolean robotInitiate;
	private Date createDatetime;

	public TblRtcSession() {
	}

	public TblRtcSession(long id, long robotId, long userId,
			boolean robotInitiate, Date createDatetime) {
		this.id = id;
		this.robotId = robotId;
		this.userId = userId;
		this.robotInitiate = robotInitiate;
		this.createDatetime = createDatetime;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public long getRobotId() {
		return this.robotId;
	}

	public void setRobotId(long robotId) {
		this.robotId = robotId;
	}

	public long getUserId() {
		return this.userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	public boolean isRobotInitiate() {
		return this.robotInitiate;
	}

	public void setRobotInitiate(boolean robotInitiate) {
		this.robotInitiate = robotInitiate;
	}

	public Date getCreateDatetime() {
		return this.createDatetime;
	}

	public void setCreateDatetime(Date createDatetime) {
		this.createDatetime = createDatetime;
	}

}
