package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * TblRuntimeData generated by hbm2java
 */
public class TblRuntimeData implements java.io.Serializable {

	private long id;
	private String robotId;
	private String app;
	private String type;
	private String msg;
	private String details;
	private Date dateTime;

	public TblRuntimeData() {
	}

	public TblRuntimeData(long id, String robotId, String app, String type,
			String msg, String details, Date dateTime) {
		this.id = id;
		this.robotId = robotId;
		this.app = app;
		this.type = type;
		this.msg = msg;
		this.details = details;
		this.dateTime = dateTime;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getRobotId() {
		return this.robotId;
	}

	public void setRobotId(String robotId) {
		this.robotId = robotId;
	}

	public String getApp() {
		return this.app;
	}

	public void setApp(String app) {
		this.app = app;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getMsg() {
		return this.msg;
	}

	public void setMsg(String msg) {
		this.msg = msg;
	}

	public String getDetails() {
		return this.details;
	}

	public void setDetails(String details) {
		this.details = details;
	}

	public Date getDateTime() {
		return this.dateTime;
	}

	public void setDateTime(Date dateTime) {
		this.dateTime = dateTime;
	}

}
