package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * TblRtcSessionStatusId generated by hbm2java
 */
public class TblRtcSessionStatusId implements java.io.Serializable {

	private long rtcSessionId;
	private Date updateDatetime;
	private String status;

	public TblRtcSessionStatusId() {
	}

	public TblRtcSessionStatusId(long rtcSessionId, Date updateDatetime,
			String status) {
		this.rtcSessionId = rtcSessionId;
		this.updateDatetime = updateDatetime;
		this.status = status;
	}

	public long getRtcSessionId() {
		return this.rtcSessionId;
	}

	public void setRtcSessionId(long rtcSessionId) {
		this.rtcSessionId = rtcSessionId;
	}

	public Date getUpdateDatetime() {
		return this.updateDatetime;
	}

	public void setUpdateDatetime(Date updateDatetime) {
		this.updateDatetime = updateDatetime;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TblRtcSessionStatusId))
			return false;
		TblRtcSessionStatusId castOther = (TblRtcSessionStatusId) other;

		return (this.getRtcSessionId() == castOther.getRtcSessionId())
				&& ((this.getUpdateDatetime() == castOther.getUpdateDatetime()) || (this
						.getUpdateDatetime() != null
						&& castOther.getUpdateDatetime() != null && this
						.getUpdateDatetime().equals(
								castOther.getUpdateDatetime())))
				&& ((this.getStatus() == castOther.getStatus()) || (this
						.getStatus() != null && castOther.getStatus() != null && this
						.getStatus().equals(castOther.getStatus())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getRtcSessionId();
		result = 37
				* result
				+ (getUpdateDatetime() == null ? 0 : this.getUpdateDatetime()
						.hashCode());
		result = 37 * result
				+ (getStatus() == null ? 0 : this.getStatus().hashCode());
		return result;
	}

}
