package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * TblRobotOfferSession generated by hbm2java
 */
public class TblRobotOfferSession implements java.io.Serializable {

	private TblRobotOfferSessionId id;

	public TblRobotOfferSession() {
	}

	public TblRobotOfferSession(TblRobotOfferSessionId id) {
		this.id = id;
	}

	public TblRobotOfferSessionId getId() {
		return this.id;
	}

	public void setId(TblRobotOfferSessionId id) {
		this.id = id;
	}

}
