package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * TblRequestPropertyBackupId generated by hbm2java
 */
public class TblRequestPropertyBackupId implements java.io.Serializable {

	private String requestId;
	private String propertyName;
	private String propertyValue;
	private boolean isNumeric;

	public TblRequestPropertyBackupId() {
	}

	public TblRequestPropertyBackupId(String requestId, String propertyName,
			String propertyValue, boolean isNumeric) {
		this.requestId = requestId;
		this.propertyName = propertyName;
		this.propertyValue = propertyValue;
		this.isNumeric = isNumeric;
	}

	public String getRequestId() {
		return this.requestId;
	}

	public void setRequestId(String requestId) {
		this.requestId = requestId;
	}

	public String getPropertyName() {
		return this.propertyName;
	}

	public void setPropertyName(String propertyName) {
		this.propertyName = propertyName;
	}

	public String getPropertyValue() {
		return this.propertyValue;
	}

	public void setPropertyValue(String propertyValue) {
		this.propertyValue = propertyValue;
	}

	public boolean isIsNumeric() {
		return this.isNumeric;
	}

	public void setIsNumeric(boolean isNumeric) {
		this.isNumeric = isNumeric;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TblRequestPropertyBackupId))
			return false;
		TblRequestPropertyBackupId castOther = (TblRequestPropertyBackupId) other;

		return ((this.getRequestId() == castOther.getRequestId()) || (this
				.getRequestId() != null && castOther.getRequestId() != null && this
				.getRequestId().equals(castOther.getRequestId())))
				&& ((this.getPropertyName() == castOther.getPropertyName()) || (this
						.getPropertyName() != null
						&& castOther.getPropertyName() != null && this
						.getPropertyName().equals(castOther.getPropertyName())))
				&& ((this.getPropertyValue() == castOther.getPropertyValue()) || (this
						.getPropertyValue() != null
						&& castOther.getPropertyValue() != null && this
						.getPropertyValue()
						.equals(castOther.getPropertyValue())))
				&& (this.isIsNumeric() == castOther.isIsNumeric());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getRequestId() == null ? 0 : this.getRequestId().hashCode());
		result = 37
				* result
				+ (getPropertyName() == null ? 0 : this.getPropertyName()
						.hashCode());
		result = 37
				* result
				+ (getPropertyValue() == null ? 0 : this.getPropertyValue()
						.hashCode());
		result = 37 * result + (this.isIsNumeric() ? 1 : 0);
		return result;
	}

}
