package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * TblRobotTagsId generated by hbm2java
 */
public class TblRobotTagsId implements java.io.Serializable {

	private long robotId;
	private String tag;

	public TblRobotTagsId() {
	}

	public TblRobotTagsId(long robotId, String tag) {
		this.robotId = robotId;
		this.tag = tag;
	}

	public long getRobotId() {
		return this.robotId;
	}

	public void setRobotId(long robotId) {
		this.robotId = robotId;
	}

	public String getTag() {
		return this.tag;
	}

	public void setTag(String tag) {
		this.tag = tag;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TblRobotTagsId))
			return false;
		TblRobotTagsId castOther = (TblRobotTagsId) other;

		return (this.getRobotId() == castOther.getRobotId())
				&& ((this.getTag() == castOther.getTag()) || (this.getTag() != null
						&& castOther.getTag() != null && this.getTag().equals(
						castOther.getTag())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getRobotId();
		result = 37 * result
				+ (getTag() == null ? 0 : this.getTag().hashCode());
		return result;
	}

}
