package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * TblRequestPropertyBackup generated by hbm2java
 */
public class TblRequestPropertyBackup implements java.io.Serializable {

	private TblRequestPropertyBackupId id;

	public TblRequestPropertyBackup() {
	}

	public TblRequestPropertyBackup(TblRequestPropertyBackupId id) {
		this.id = id;
	}

	public TblRequestPropertyBackupId getId() {
		return this.id;
	}

	public void setId(TblRequestPropertyBackupId id) {
		this.id = id;
	}

}
