package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * TblRtcSessionSignalCacheId generated by hbm2java
 */
public class TblRtcSessionSignalCacheId implements java.io.Serializable {

	private long rtcSessionId;
	private String type;
	private String data;

	public TblRtcSessionSignalCacheId() {
	}

	public TblRtcSessionSignalCacheId(long rtcSessionId, String type,
			String data) {
		this.rtcSessionId = rtcSessionId;
		this.type = type;
		this.data = data;
	}

	public long getRtcSessionId() {
		return this.rtcSessionId;
	}

	public void setRtcSessionId(long rtcSessionId) {
		this.rtcSessionId = rtcSessionId;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getData() {
		return this.data;
	}

	public void setData(String data) {
		this.data = data;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TblRtcSessionSignalCacheId))
			return false;
		TblRtcSessionSignalCacheId castOther = (TblRtcSessionSignalCacheId) other;

		return (this.getRtcSessionId() == castOther.getRtcSessionId())
				&& ((this.getType() == castOther.getType()) || (this.getType() != null
						&& castOther.getType() != null && this.getType()
						.equals(castOther.getType())))
				&& ((this.getData() == castOther.getData()) || (this.getData() != null
						&& castOther.getData() != null && this.getData()
						.equals(castOther.getData())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getRtcSessionId();
		result = 37 * result
				+ (getType() == null ? 0 : this.getType().hashCode());
		result = 37 * result
				+ (getData() == null ? 0 : this.getData().hashCode());
		return result;
	}

}
