package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * TblRobotStatus generated by hbm2java
 */
public class TblRobotStatus implements java.io.Serializable {

	private TblRobotStatusId id;
	private String wssSessionId;
	private boolean online;
	private String extraInfo;

	public TblRobotStatus() {
	}

	public TblRobotStatus(TblRobotStatusId id, boolean online) {
		this.id = id;
		this.online = online;
	}

	public TblRobotStatus(TblRobotStatusId id, String wssSessionId,
			boolean online, String extraInfo) {
		this.id = id;
		this.wssSessionId = wssSessionId;
		this.online = online;
		this.extraInfo = extraInfo;
	}

	public TblRobotStatusId getId() {
		return this.id;
	}

	public void setId(TblRobotStatusId id) {
		this.id = id;
	}

	public String getWssSessionId() {
		return this.wssSessionId;
	}

	public void setWssSessionId(String wssSessionId) {
		this.wssSessionId = wssSessionId;
	}

	public boolean isOnline() {
		return this.online;
	}

	public void setOnline(boolean online) {
		this.online = online;
	}

	public String getExtraInfo() {
		return this.extraInfo;
	}

	public void setExtraInfo(String extraInfo) {
		this.extraInfo = extraInfo;
	}

}
