package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * TblRuntimeDataBackup generated by hbm2java
 */
public class TblRuntimeDataBackup implements java.io.Serializable {

	private TblRuntimeDataBackupId id;

	public TblRuntimeDataBackup() {
	}

	public TblRuntimeDataBackup(TblRuntimeDataBackupId id) {
		this.id = id;
	}

	public TblRuntimeDataBackupId getId() {
		return this.id;
	}

	public void setId(TblRuntimeDataBackupId id) {
		this.id = id;
	}

}
