package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * TblRequestRecommendId generated by hbm2java
 */
public class TblRequestRecommendId implements java.io.Serializable {

	private String requestId;
	private Long recommendFlowId;
	private Long matchedDegree;
	private Long granularity;

	public TblRequestRecommendId() {
	}

	public TblRequestRecommendId(String requestId, Long recommendFlowId,
			Long matchedDegree, Long granularity) {
		this.requestId = requestId;
		this.recommendFlowId = recommendFlowId;
		this.matchedDegree = matchedDegree;
		this.granularity = granularity;
	}

	public String getRequestId() {
		return this.requestId;
	}

	public void setRequestId(String requestId) {
		this.requestId = requestId;
	}

	public Long getRecommendFlowId() {
		return this.recommendFlowId;
	}

	public void setRecommendFlowId(Long recommendFlowId) {
		this.recommendFlowId = recommendFlowId;
	}

	public Long getMatchedDegree() {
		return this.matchedDegree;
	}

	public void setMatchedDegree(Long matchedDegree) {
		this.matchedDegree = matchedDegree;
	}

	public Long getGranularity() {
		return this.granularity;
	}

	public void setGranularity(Long granularity) {
		this.granularity = granularity;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TblRequestRecommendId))
			return false;
		TblRequestRecommendId castOther = (TblRequestRecommendId) other;

		return ((this.getRequestId() == castOther.getRequestId()) || (this
				.getRequestId() != null && castOther.getRequestId() != null && this
				.getRequestId().equals(castOther.getRequestId())))
				&& ((this.getRecommendFlowId() == castOther
						.getRecommendFlowId()) || (this.getRecommendFlowId() != null
						&& castOther.getRecommendFlowId() != null && this
						.getRecommendFlowId().equals(
								castOther.getRecommendFlowId())))
				&& ((this.getMatchedDegree() == castOther.getMatchedDegree()) || (this
						.getMatchedDegree() != null
						&& castOther.getMatchedDegree() != null && this
						.getMatchedDegree()
						.equals(castOther.getMatchedDegree())))
				&& ((this.getGranularity() == castOther.getGranularity()) || (this
						.getGranularity() != null
						&& castOther.getGranularity() != null && this
						.getGranularity().equals(castOther.getGranularity())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getRequestId() == null ? 0 : this.getRequestId().hashCode());
		result = 37
				* result
				+ (getRecommendFlowId() == null ? 0 : this.getRecommendFlowId()
						.hashCode());
		result = 37
				* result
				+ (getMatchedDegree() == null ? 0 : this.getMatchedDegree()
						.hashCode());
		result = 37
				* result
				+ (getGranularity() == null ? 0 : this.getGranularity()
						.hashCode());
		return result;
	}

}
