package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * TblRobotAppVersionRequiredId generated by hbm2java
 */
public class TblRobotAppVersionRequiredId implements java.io.Serializable {

	private String dbVersion;
	private long robotAppId;
	private long versionCode;

	public TblRobotAppVersionRequiredId() {
	}

	public TblRobotAppVersionRequiredId(String dbVersion, long robotAppId,
			long versionCode) {
		this.dbVersion = dbVersion;
		this.robotAppId = robotAppId;
		this.versionCode = versionCode;
	}

	public String getDbVersion() {
		return this.dbVersion;
	}

	public void setDbVersion(String dbVersion) {
		this.dbVersion = dbVersion;
	}

	public long getRobotAppId() {
		return this.robotAppId;
	}

	public void setRobotAppId(long robotAppId) {
		this.robotAppId = robotAppId;
	}

	public long getVersionCode() {
		return this.versionCode;
	}

	public void setVersionCode(long versionCode) {
		this.versionCode = versionCode;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TblRobotAppVersionRequiredId))
			return false;
		TblRobotAppVersionRequiredId castOther = (TblRobotAppVersionRequiredId) other;

		return ((this.getDbVersion() == castOther.getDbVersion()) || (this
				.getDbVersion() != null && castOther.getDbVersion() != null && this
				.getDbVersion().equals(castOther.getDbVersion())))
				&& (this.getRobotAppId() == castOther.getRobotAppId())
				&& (this.getVersionCode() == castOther.getVersionCode());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getDbVersion() == null ? 0 : this.getDbVersion().hashCode());
		result = 37 * result + (int) this.getRobotAppId();
		result = 37 * result + (int) this.getVersionCode();
		return result;
	}

}
