package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * TblRobotStatusId generated by hbm2java
 */
public class TblRobotStatusId implements java.io.Serializable {

	private long robotId;
	private Date updateDatetime;

	public TblRobotStatusId() {
	}

	public TblRobotStatusId(long robotId, Date updateDatetime) {
		this.robotId = robotId;
		this.updateDatetime = updateDatetime;
	}

	public long getRobotId() {
		return this.robotId;
	}

	public void setRobotId(long robotId) {
		this.robotId = robotId;
	}

	public Date getUpdateDatetime() {
		return this.updateDatetime;
	}

	public void setUpdateDatetime(Date updateDatetime) {
		this.updateDatetime = updateDatetime;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TblRobotStatusId))
			return false;
		TblRobotStatusId castOther = (TblRobotStatusId) other;

		return (this.getRobotId() == castOther.getRobotId())
				&& ((this.getUpdateDatetime() == castOther.getUpdateDatetime()) || (this
						.getUpdateDatetime() != null
						&& castOther.getUpdateDatetime() != null && this
						.getUpdateDatetime().equals(
								castOther.getUpdateDatetime())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getRobotId();
		result = 37
				* result
				+ (getUpdateDatetime() == null ? 0 : this.getUpdateDatetime()
						.hashCode());
		return result;
	}

}
