package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * TblThirdPartyApiParamsValue generated by hbm2java
 */
public class TblThirdPartyApiParamsValue implements java.io.Serializable {

	private TblThirdPartyApiParamsValueId id;
	private TblThirdPartyApiParams tblThirdPartyApiParams;
	private EntThirdPartyApiParamsValue entThirdPartyApiParamsValue;
	private String paramValue;
	private String description;

	public TblThirdPartyApiParamsValue() {
	}

	public TblThirdPartyApiParamsValue(TblThirdPartyApiParamsValueId id,
			TblThirdPartyApiParams tblThirdPartyApiParams,
			EntThirdPartyApiParamsValue entThirdPartyApiParamsValue,
			String paramValue) {
		this.id = id;
		this.tblThirdPartyApiParams = tblThirdPartyApiParams;
		this.entThirdPartyApiParamsValue = entThirdPartyApiParamsValue;
		this.paramValue = paramValue;
	}

	public TblThirdPartyApiParamsValue(TblThirdPartyApiParamsValueId id,
			TblThirdPartyApiParams tblThirdPartyApiParams,
			EntThirdPartyApiParamsValue entThirdPartyApiParamsValue,
			String paramValue, String description) {
		this.id = id;
		this.tblThirdPartyApiParams = tblThirdPartyApiParams;
		this.entThirdPartyApiParamsValue = entThirdPartyApiParamsValue;
		this.paramValue = paramValue;
		this.description = description;
	}

	public TblThirdPartyApiParamsValueId getId() {
		return this.id;
	}

	public void setId(TblThirdPartyApiParamsValueId id) {
		this.id = id;
	}

	public TblThirdPartyApiParams getTblThirdPartyApiParams() {
		return this.tblThirdPartyApiParams;
	}

	public void setTblThirdPartyApiParams(
			TblThirdPartyApiParams tblThirdPartyApiParams) {
		this.tblThirdPartyApiParams = tblThirdPartyApiParams;
	}

	public EntThirdPartyApiParamsValue getEntThirdPartyApiParamsValue() {
		return this.entThirdPartyApiParamsValue;
	}

	public void setEntThirdPartyApiParamsValue(
			EntThirdPartyApiParamsValue entThirdPartyApiParamsValue) {
		this.entThirdPartyApiParamsValue = entThirdPartyApiParamsValue;
	}

	public String getParamValue() {
		return this.paramValue;
	}

	public void setParamValue(String paramValue) {
		this.paramValue = paramValue;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
