package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * TblThirdPartyApiParamsValueId generated by hbm2java
 */
public class TblThirdPartyApiParamsValueId implements java.io.Serializable {

	private long id;
	private long thirdPartyApiId;
	private String thirdPartyApiParamName;

	public TblThirdPartyApiParamsValueId() {
	}

	public TblThirdPartyApiParamsValueId(long id, long thirdPartyApiId,
			String thirdPartyApiParamName) {
		this.id = id;
		this.thirdPartyApiId = thirdPartyApiId;
		this.thirdPartyApiParamName = thirdPartyApiParamName;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public long getThirdPartyApiId() {
		return this.thirdPartyApiId;
	}

	public void setThirdPartyApiId(long thirdPartyApiId) {
		this.thirdPartyApiId = thirdPartyApiId;
	}

	public String getThirdPartyApiParamName() {
		return this.thirdPartyApiParamName;
	}

	public void setThirdPartyApiParamName(String thirdPartyApiParamName) {
		this.thirdPartyApiParamName = thirdPartyApiParamName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TblThirdPartyApiParamsValueId))
			return false;
		TblThirdPartyApiParamsValueId castOther = (TblThirdPartyApiParamsValueId) other;

		return (this.getId() == castOther.getId())
				&& (this.getThirdPartyApiId() == castOther.getThirdPartyApiId())
				&& ((this.getThirdPartyApiParamName() == castOther
						.getThirdPartyApiParamName()) || (this
						.getThirdPartyApiParamName() != null
						&& castOther.getThirdPartyApiParamName() != null && this
						.getThirdPartyApiParamName().equals(
								castOther.getThirdPartyApiParamName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getId();
		result = 37 * result + (int) this.getThirdPartyApiId();
		result = 37
				* result
				+ (getThirdPartyApiParamName() == null ? 0 : this
						.getThirdPartyApiParamName().hashCode());
		return result;
	}

}
