package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * TblThirdPartyApiParam generated by hbm2java
 */
public class TblThirdPartyApiParam implements java.io.Serializable {

	private TblThirdPartyApiParamId id;
	private EntThirdPartyApiParam entThirdPartyApiParam;
	private EntThirdPartyApi entThirdPartyApi;
	private String description;

	public TblThirdPartyApiParam() {
	}

	public TblThirdPartyApiParam(TblThirdPartyApiParamId id,
			EntThirdPartyApiParam entThirdPartyApiParam,
			EntThirdPartyApi entThirdPartyApi) {
		this.id = id;
		this.entThirdPartyApiParam = entThirdPartyApiParam;
		this.entThirdPartyApi = entThirdPartyApi;
	}

	public TblThirdPartyApiParam(TblThirdPartyApiParamId id,
			EntThirdPartyApiParam entThirdPartyApiParam,
			EntThirdPartyApi entThirdPartyApi, String description) {
		this.id = id;
		this.entThirdPartyApiParam = entThirdPartyApiParam;
		this.entThirdPartyApi = entThirdPartyApi;
		this.description = description;
	}

	public TblThirdPartyApiParamId getId() {
		return this.id;
	}

	public void setId(TblThirdPartyApiParamId id) {
		this.id = id;
	}

	public EntThirdPartyApiParam getEntThirdPartyApiParam() {
		return this.entThirdPartyApiParam;
	}

	public void setEntThirdPartyApiParam(
			EntThirdPartyApiParam entThirdPartyApiParam) {
		this.entThirdPartyApiParam = entThirdPartyApiParam;
	}

	public EntThirdPartyApi getEntThirdPartyApi() {
		return this.entThirdPartyApi;
	}

	public void setEntThirdPartyApi(EntThirdPartyApi entThirdPartyApi) {
		this.entThirdPartyApi = entThirdPartyApi;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
