package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * TblThirdPartyApiParamsId generated by hbm2java
 */
public class TblThirdPartyApiParamsId implements java.io.Serializable {

	private long thirdPartyApiId;
	private String paramName;

	public TblThirdPartyApiParamsId() {
	}

	public TblThirdPartyApiParamsId(long thirdPartyApiId, String paramName) {
		this.thirdPartyApiId = thirdPartyApiId;
		this.paramName = paramName;
	}

	public long getThirdPartyApiId() {
		return this.thirdPartyApiId;
	}

	public void setThirdPartyApiId(long thirdPartyApiId) {
		this.thirdPartyApiId = thirdPartyApiId;
	}

	public String getParamName() {
		return this.paramName;
	}

	public void setParamName(String paramName) {
		this.paramName = paramName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TblThirdPartyApiParamsId))
			return false;
		TblThirdPartyApiParamsId castOther = (TblThirdPartyApiParamsId) other;

		return (this.getThirdPartyApiId() == castOther.getThirdPartyApiId())
				&& ((this.getParamName() == castOther.getParamName()) || (this
						.getParamName() != null
						&& castOther.getParamName() != null && this
						.getParamName().equals(castOther.getParamName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getThirdPartyApiId();
		result = 37 * result
				+ (getParamName() == null ? 0 : this.getParamName().hashCode());
		return result;
	}

}
