package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * TblUserOfferSession generated by hbm2java
 */
public class TblUserOfferSession implements java.io.Serializable {

	private TblUserOfferSessionId id;

	public TblUserOfferSession() {
	}

	public TblUserOfferSession(TblUserOfferSessionId id) {
		this.id = id;
	}

	public TblUserOfferSessionId getId() {
		return this.id;
	}

	public void setId(TblUserOfferSessionId id) {
		this.id = id;
	}

}
