package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * TblUserGroupScene generated by hbm2java
 */
public class TblUserGroupScene implements java.io.Serializable {

	private long id;
	private EntUserGroup entUserGroup;
	private String name;
	private boolean enabled;
	private String description;
	private String tag;
	private Set tblCustomizedConfigForUserGroupScenes = new HashSet(0);

	public TblUserGroupScene() {
	}

	public TblUserGroupScene(long id, EntUserGroup entUserGroup, String name,
			boolean enabled, String description) {
		this.id = id;
		this.entUserGroup = entUserGroup;
		this.name = name;
		this.enabled = enabled;
		this.description = description;
	}

	public TblUserGroupScene(long id, EntUserGroup entUserGroup, String name,
			boolean enabled, String description, String tag,
			Set tblCustomizedConfigForUserGroupScenes) {
		this.id = id;
		this.entUserGroup = entUserGroup;
		this.name = name;
		this.enabled = enabled;
		this.description = description;
		this.tag = tag;
		this.tblCustomizedConfigForUserGroupScenes = tblCustomizedConfigForUserGroupScenes;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public EntUserGroup getEntUserGroup() {
		return this.entUserGroup;
	}

	public void setEntUserGroup(EntUserGroup entUserGroup) {
		this.entUserGroup = entUserGroup;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public boolean isEnabled() {
		return this.enabled;
	}

	public void setEnabled(boolean enabled) {
		this.enabled = enabled;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getTag() {
		return this.tag;
	}

	public void setTag(String tag) {
		this.tag = tag;
	}

	public Set getTblCustomizedConfigForUserGroupScenes() {
		return this.tblCustomizedConfigForUserGroupScenes;
	}

	public void setTblCustomizedConfigForUserGroupScenes(
			Set tblCustomizedConfigForUserGroupScenes) {
		this.tblCustomizedConfigForUserGroupScenes = tblCustomizedConfigForUserGroupScenes;
	}

}
