package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * TblUserStatus generated by hbm2java
 */
public class TblUserStatus implements java.io.Serializable {

	private TblUserStatusId id;
	private boolean online;
	private String extraInfo;
	private String wssSessionId;

	public TblUserStatus() {
	}

	public TblUserStatus(TblUserStatusId id, boolean online) {
		this.id = id;
		this.online = online;
	}

	public TblUserStatus(TblUserStatusId id, boolean online, String extraInfo,
			String wssSessionId) {
		this.id = id;
		this.online = online;
		this.extraInfo = extraInfo;
		this.wssSessionId = wssSessionId;
	}

	public TblUserStatusId getId() {
		return this.id;
	}

	public void setId(TblUserStatusId id) {
		this.id = id;
	}

	public boolean isOnline() {
		return this.online;
	}

	public void setOnline(boolean online) {
		this.online = online;
	}

	public String getExtraInfo() {
		return this.extraInfo;
	}

	public void setExtraInfo(String extraInfo) {
		this.extraInfo = extraInfo;
	}

	public String getWssSessionId() {
		return this.wssSessionId;
	}

	public void setWssSessionId(String wssSessionId) {
		this.wssSessionId = wssSessionId;
	}

}
