package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * TblVersionRequired generated by hbm2java
 */
public class TblVersionRequired implements java.io.Serializable {

	private String dbVersion;
	private EntDbVersion entDbVersion;
	private String requriedClientVersion;

	public TblVersionRequired() {
	}

	public TblVersionRequired(EntDbVersion entDbVersion,
			String requriedClientVersion) {
		this.entDbVersion = entDbVersion;
		this.requriedClientVersion = requriedClientVersion;
	}

	public String getDbVersion() {
		return this.dbVersion;
	}

	public void setDbVersion(String dbVersion) {
		this.dbVersion = dbVersion;
	}

	public EntDbVersion getEntDbVersion() {
		return this.entDbVersion;
	}

	public void setEntDbVersion(EntDbVersion entDbVersion) {
		this.entDbVersion = entDbVersion;
	}

	public String getRequriedClientVersion() {
		return this.requriedClientVersion;
	}

	public void setRequriedClientVersion(String requriedClientVersion) {
		this.requriedClientVersion = requriedClientVersion;
	}

}
