package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * TblVoiceGroup generated by hbm2java
 */
public class TblVoiceGroup implements java.io.Serializable {

	private TblVoiceGroupId id;
	private EntVoiceGroup entVoiceGroup;
	private EntVoice entVoice;
	private String description;

	public TblVoiceGroup() {
	}

	public TblVoiceGroup(TblVoiceGroupId id, EntVoiceGroup entVoiceGroup,
			EntVoice entVoice, String description) {
		this.id = id;
		this.entVoiceGroup = entVoiceGroup;
		this.entVoice = entVoice;
		this.description = description;
	}

	public TblVoiceGroupId getId() {
		return this.id;
	}

	public void setId(TblVoiceGroupId id) {
		this.id = id;
	}

	public EntVoiceGroup getEntVoiceGroup() {
		return this.entVoiceGroup;
	}

	public void setEntVoiceGroup(EntVoiceGroup entVoiceGroup) {
		this.entVoiceGroup = entVoiceGroup;
	}

	public EntVoice getEntVoice() {
		return this.entVoice;
	}

	public void setEntVoice(EntVoice entVoice) {
		this.entVoice = entVoice;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
