package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * TblWordGroupFlowToVoiceGroupRule generated by hbm2java
 */
public class TblWordGroupFlowToVoiceGroupRule implements java.io.Serializable {

	private TblWordGroupFlowToVoiceGroupRuleId id;
	private EntWordGroupFlow entWordGroupFlow;
	private EntVoiceGroup entVoiceGroup;
	private long id_1;
	private boolean useFlowOrder;
	private boolean useFullyMatch;
	private boolean enable;
	private String description;

	public TblWordGroupFlowToVoiceGroupRule() {
	}

	public TblWordGroupFlowToVoiceGroupRule(
			TblWordGroupFlowToVoiceGroupRuleId id,
			EntWordGroupFlow entWordGroupFlow, EntVoiceGroup entVoiceGroup,
			long id_1, boolean useFlowOrder, boolean useFullyMatch,
			boolean enable, String description) {
		this.id = id;
		this.entWordGroupFlow = entWordGroupFlow;
		this.entVoiceGroup = entVoiceGroup;
		this.id_1 = id_1;
		this.useFlowOrder = useFlowOrder;
		this.useFullyMatch = useFullyMatch;
		this.enable = enable;
		this.description = description;
	}

	public TblWordGroupFlowToVoiceGroupRuleId getId() {
		return this.id;
	}

	public void setId(TblWordGroupFlowToVoiceGroupRuleId id) {
		this.id = id;
	}

	public EntWordGroupFlow getEntWordGroupFlow() {
		return this.entWordGroupFlow;
	}

	public void setEntWordGroupFlow(EntWordGroupFlow entWordGroupFlow) {
		this.entWordGroupFlow = entWordGroupFlow;
	}

	public EntVoiceGroup getEntVoiceGroup() {
		return this.entVoiceGroup;
	}

	public void setEntVoiceGroup(EntVoiceGroup entVoiceGroup) {
		this.entVoiceGroup = entVoiceGroup;
	}

	public long getId_1() {
		return this.id_1;
	}

	public void setId_1(long id_1) {
		this.id_1 = id_1;
	}

	public boolean isUseFlowOrder() {
		return this.useFlowOrder;
	}

	public void setUseFlowOrder(boolean useFlowOrder) {
		this.useFlowOrder = useFlowOrder;
	}

	public boolean isUseFullyMatch() {
		return this.useFullyMatch;
	}

	public void setUseFullyMatch(boolean useFullyMatch) {
		this.useFullyMatch = useFullyMatch;
	}

	public boolean isEnable() {
		return this.enable;
	}

	public void setEnable(boolean enable) {
		this.enable = enable;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
