package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * TblWordGroupFlowId generated by hbm2java
 */
public class TblWordGroupFlowId implements java.io.Serializable {

	private long id;
	private long wordGroupId;

	public TblWordGroupFlowId() {
	}

	public TblWordGroupFlowId(long id, long wordGroupId) {
		this.id = id;
		this.wordGroupId = wordGroupId;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public long getWordGroupId() {
		return this.wordGroupId;
	}

	public void setWordGroupId(long wordGroupId) {
		this.wordGroupId = wordGroupId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TblWordGroupFlowId))
			return false;
		TblWordGroupFlowId castOther = (TblWordGroupFlowId) other;

		return (this.getId() == castOther.getId())
				&& (this.getWordGroupId() == castOther.getWordGroupId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getId();
		result = 37 * result + (int) this.getWordGroupId();
		return result;
	}

}
