package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * TblWordGroupFlowToVoiceGroupRuleOrignal generated by hbm2java
 */
public class TblWordGroupFlowToVoiceGroupRuleOrignal implements
		java.io.Serializable {

	private long id;
	private EntUser entUserByUpdateUserId;
	private EntWordGroupFlow entWordGroupFlow;
	private EntVoice entVoice;
	private EntUser entUserByCreateUserId;
	private String request;
	private Date createDatetime;
	private Date updateDatetime;
	private Long responseVoiceGroupId;
	private Date genDatetime;

	public TblWordGroupFlowToVoiceGroupRuleOrignal() {
	}

	public TblWordGroupFlowToVoiceGroupRuleOrignal(long id,
			EntUser entUserByUpdateUserId, EntVoice entVoice,
			EntUser entUserByCreateUserId, String request, Date createDatetime,
			Date updateDatetime) {
		this.id = id;
		this.entUserByUpdateUserId = entUserByUpdateUserId;
		this.entVoice = entVoice;
		this.entUserByCreateUserId = entUserByCreateUserId;
		this.request = request;
		this.createDatetime = createDatetime;
		this.updateDatetime = updateDatetime;
	}

	public TblWordGroupFlowToVoiceGroupRuleOrignal(long id,
			EntUser entUserByUpdateUserId, EntWordGroupFlow entWordGroupFlow,
			EntVoice entVoice, EntUser entUserByCreateUserId, String request,
			Date createDatetime, Date updateDatetime,
			Long responseVoiceGroupId, Date genDatetime) {
		this.id = id;
		this.entUserByUpdateUserId = entUserByUpdateUserId;
		this.entWordGroupFlow = entWordGroupFlow;
		this.entVoice = entVoice;
		this.entUserByCreateUserId = entUserByCreateUserId;
		this.request = request;
		this.createDatetime = createDatetime;
		this.updateDatetime = updateDatetime;
		this.responseVoiceGroupId = responseVoiceGroupId;
		this.genDatetime = genDatetime;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public EntUser getEntUserByUpdateUserId() {
		return this.entUserByUpdateUserId;
	}

	public void setEntUserByUpdateUserId(EntUser entUserByUpdateUserId) {
		this.entUserByUpdateUserId = entUserByUpdateUserId;
	}

	public EntWordGroupFlow getEntWordGroupFlow() {
		return this.entWordGroupFlow;
	}

	public void setEntWordGroupFlow(EntWordGroupFlow entWordGroupFlow) {
		this.entWordGroupFlow = entWordGroupFlow;
	}

	public EntVoice getEntVoice() {
		return this.entVoice;
	}

	public void setEntVoice(EntVoice entVoice) {
		this.entVoice = entVoice;
	}

	public EntUser getEntUserByCreateUserId() {
		return this.entUserByCreateUserId;
	}

	public void setEntUserByCreateUserId(EntUser entUserByCreateUserId) {
		this.entUserByCreateUserId = entUserByCreateUserId;
	}

	public String getRequest() {
		return this.request;
	}

	public void setRequest(String request) {
		this.request = request;
	}

	public Date getCreateDatetime() {
		return this.createDatetime;
	}

	public void setCreateDatetime(Date createDatetime) {
		this.createDatetime = createDatetime;
	}

	public Date getUpdateDatetime() {
		return this.updateDatetime;
	}

	public void setUpdateDatetime(Date updateDatetime) {
		this.updateDatetime = updateDatetime;
	}

	public Long getResponseVoiceGroupId() {
		return this.responseVoiceGroupId;
	}

	public void setResponseVoiceGroupId(Long responseVoiceGroupId) {
		this.responseVoiceGroupId = responseVoiceGroupId;
	}

	public Date getGenDatetime() {
		return this.genDatetime;
	}

	public void setGenDatetime(Date genDatetime) {
		this.genDatetime = genDatetime;
	}

}
