package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * TblWordGroupFlowToVoiceGroupRuleId generated by hbm2java
 */
public class TblWordGroupFlowToVoiceGroupRuleId implements java.io.Serializable {

	private long wordGroupFlowId;
	private long voiceGroupId;

	public TblWordGroupFlowToVoiceGroupRuleId() {
	}

	public TblWordGroupFlowToVoiceGroupRuleId(long wordGroupFlowId,
			long voiceGroupId) {
		this.wordGroupFlowId = wordGroupFlowId;
		this.voiceGroupId = voiceGroupId;
	}

	public long getWordGroupFlowId() {
		return this.wordGroupFlowId;
	}

	public void setWordGroupFlowId(long wordGroupFlowId) {
		this.wordGroupFlowId = wordGroupFlowId;
	}

	public long getVoiceGroupId() {
		return this.voiceGroupId;
	}

	public void setVoiceGroupId(long voiceGroupId) {
		this.voiceGroupId = voiceGroupId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TblWordGroupFlowToVoiceGroupRuleId))
			return false;
		TblWordGroupFlowToVoiceGroupRuleId castOther = (TblWordGroupFlowToVoiceGroupRuleId) other;

		return (this.getWordGroupFlowId() == castOther.getWordGroupFlowId())
				&& (this.getVoiceGroupId() == castOther.getVoiceGroupId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getWordGroupFlowId();
		result = 37 * result + (int) this.getVoiceGroupId();
		return result;
	}

}
