package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * TblWordGroupId generated by hbm2java
 */
public class TblWordGroupId implements java.io.Serializable {

	private long keyWordId;
	private long groupId;

	public TblWordGroupId() {
	}

	public TblWordGroupId(long keyWordId, long groupId) {
		this.keyWordId = keyWordId;
		this.groupId = groupId;
	}

	public long getKeyWordId() {
		return this.keyWordId;
	}

	public void setKeyWordId(long keyWordId) {
		this.keyWordId = keyWordId;
	}

	public long getGroupId() {
		return this.groupId;
	}

	public void setGroupId(long groupId) {
		this.groupId = groupId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TblWordGroupId))
			return false;
		TblWordGroupId castOther = (TblWordGroupId) other;

		return (this.getKeyWordId() == castOther.getKeyWordId())
				&& (this.getGroupId() == castOther.getGroupId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getKeyWordId();
		result = 37 * result + (int) this.getGroupId();
		return result;
	}

}
