package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * TblWordGroupFlow generated by hbm2java
 */
public class TblWordGroupFlow implements java.io.Serializable {

	private TblWordGroupFlowId id;
	private EntWordGroupFlow entWordGroupFlow;
	private EntWordGroup entWordGroup;
	private Long groupFlowOrder;
	private boolean useSound;
	private boolean inc1Exc0;
	private String description;

	public TblWordGroupFlow() {
	}

	public TblWordGroupFlow(TblWordGroupFlowId id,
			EntWordGroupFlow entWordGroupFlow, EntWordGroup entWordGroup,
			boolean useSound, boolean inc1Exc0) {
		this.id = id;
		this.entWordGroupFlow = entWordGroupFlow;
		this.entWordGroup = entWordGroup;
		this.useSound = useSound;
		this.inc1Exc0 = inc1Exc0;
	}

	public TblWordGroupFlow(TblWordGroupFlowId id,
			EntWordGroupFlow entWordGroupFlow, EntWordGroup entWordGroup,
			Long groupFlowOrder, boolean useSound, boolean inc1Exc0,
			String description) {
		this.id = id;
		this.entWordGroupFlow = entWordGroupFlow;
		this.entWordGroup = entWordGroup;
		this.groupFlowOrder = groupFlowOrder;
		this.useSound = useSound;
		this.inc1Exc0 = inc1Exc0;
		this.description = description;
	}

	public TblWordGroupFlowId getId() {
		return this.id;
	}

	public void setId(TblWordGroupFlowId id) {
		this.id = id;
	}

	public EntWordGroupFlow getEntWordGroupFlow() {
		return this.entWordGroupFlow;
	}

	public void setEntWordGroupFlow(EntWordGroupFlow entWordGroupFlow) {
		this.entWordGroupFlow = entWordGroupFlow;
	}

	public EntWordGroup getEntWordGroup() {
		return this.entWordGroup;
	}

	public void setEntWordGroup(EntWordGroup entWordGroup) {
		this.entWordGroup = entWordGroup;
	}

	public Long getGroupFlowOrder() {
		return this.groupFlowOrder;
	}

	public void setGroupFlowOrder(Long groupFlowOrder) {
		this.groupFlowOrder = groupFlowOrder;
	}

	public boolean isUseSound() {
		return this.useSound;
	}

	public void setUseSound(boolean useSound) {
		this.useSound = useSound;
	}

	public boolean isInc1Exc0() {
		return this.inc1Exc0;
	}

	public void setInc1Exc0(boolean inc1Exc0) {
		this.inc1Exc0 = inc1Exc0;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
