package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * TblWordGroup generated by hbm2java
 */
public class TblWordGroup implements java.io.Serializable {

	private TblWordGroupId id;
	private EntWordGroup entWordGroup;
	private EntKeyWords entKeyWords;
	private String description;

	public TblWordGroup() {
	}

	public TblWordGroup(TblWordGroupId id, EntWordGroup entWordGroup,
			EntKeyWords entKeyWords) {
		this.id = id;
		this.entWordGroup = entWordGroup;
		this.entKeyWords = entKeyWords;
	}

	public TblWordGroup(TblWordGroupId id, EntWordGroup entWordGroup,
			EntKeyWords entKeyWords, String description) {
		this.id = id;
		this.entWordGroup = entWordGroup;
		this.entKeyWords = entKeyWords;
		this.description = description;
	}

	public TblWordGroupId getId() {
		return this.id;
	}

	public void setId(TblWordGroupId id) {
		this.id = id;
	}

	public EntWordGroup getEntWordGroup() {
		return this.entWordGroup;
	}

	public void setEntWordGroup(EntWordGroup entWordGroup) {
		this.entWordGroup = entWordGroup;
	}

	public EntKeyWords getEntKeyWords() {
		return this.entKeyWords;
	}

	public void setEntKeyWords(EntKeyWords entKeyWords) {
		this.entKeyWords = entKeyWords;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
