package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * ViewVoice generated by hbm2java
 */
public class ViewVoice implements java.io.Serializable {

	private ViewVoiceId id;

	public ViewVoice() {
	}

	public ViewVoice(ViewVoiceId id) {
		this.id = id;
	}

	public ViewVoiceId getId() {
		return this.id;
	}

	public void setId(ViewVoiceId id) {
		this.id = id;
	}

}
