package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * ViewWordGroupFlow generated by hbm2java
 */
public class ViewWordGroupFlow implements java.io.Serializable {

	private ViewWordGroupFlowId id;

	public ViewWordGroupFlow() {
	}

	public ViewWordGroupFlow(ViewWordGroupFlowId id) {
		this.id = id;
	}

	public ViewWordGroupFlowId getId() {
		return this.id;
	}

	public void setId(ViewWordGroupFlowId id) {
		this.id = id;
	}

}
