package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * ViewOrderRoomId generated by hbm2java
 */
public class ViewOrderRoomId implements java.io.Serializable {

	private long roomId;
	private String roomName;
	private String orderDate;
	private String roomPosition;
	private String period;
	private String orderName;
	private String mobilePhone;
	private Date submitDatetime;
	private boolean night;

	public ViewOrderRoomId() {
	}

	public ViewOrderRoomId(long roomId, String roomName, String orderDate,
			String roomPosition, String period, String orderName,
			String mobilePhone, Date submitDatetime, boolean night) {
		this.roomId = roomId;
		this.roomName = roomName;
		this.orderDate = orderDate;
		this.roomPosition = roomPosition;
		this.period = period;
		this.orderName = orderName;
		this.mobilePhone = mobilePhone;
		this.submitDatetime = submitDatetime;
		this.night = night;
	}

	public long getRoomId() {
		return this.roomId;
	}

	public void setRoomId(long roomId) {
		this.roomId = roomId;
	}

	public String getRoomName() {
		return this.roomName;
	}

	public void setRoomName(String roomName) {
		this.roomName = roomName;
	}

	public String getOrderDate() {
		return this.orderDate;
	}

	public void setOrderDate(String orderDate) {
		this.orderDate = orderDate;
	}

	public String getRoomPosition() {
		return this.roomPosition;
	}

	public void setRoomPosition(String roomPosition) {
		this.roomPosition = roomPosition;
	}

	public String getPeriod() {
		return this.period;
	}

	public void setPeriod(String period) {
		this.period = period;
	}

	public String getOrderName() {
		return this.orderName;
	}

	public void setOrderName(String orderName) {
		this.orderName = orderName;
	}

	public String getMobilePhone() {
		return this.mobilePhone;
	}

	public void setMobilePhone(String mobilePhone) {
		this.mobilePhone = mobilePhone;
	}

	public Date getSubmitDatetime() {
		return this.submitDatetime;
	}

	public void setSubmitDatetime(Date submitDatetime) {
		this.submitDatetime = submitDatetime;
	}

	public boolean isNight() {
		return this.night;
	}

	public void setNight(boolean night) {
		this.night = night;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ViewOrderRoomId))
			return false;
		ViewOrderRoomId castOther = (ViewOrderRoomId) other;

		return (this.getRoomId() == castOther.getRoomId())
				&& ((this.getRoomName() == castOther.getRoomName()) || (this
						.getRoomName() != null
						&& castOther.getRoomName() != null && this
						.getRoomName().equals(castOther.getRoomName())))
				&& ((this.getOrderDate() == castOther.getOrderDate()) || (this
						.getOrderDate() != null
						&& castOther.getOrderDate() != null && this
						.getOrderDate().equals(castOther.getOrderDate())))
				&& ((this.getRoomPosition() == castOther.getRoomPosition()) || (this
						.getRoomPosition() != null
						&& castOther.getRoomPosition() != null && this
						.getRoomPosition().equals(castOther.getRoomPosition())))
				&& ((this.getPeriod() == castOther.getPeriod()) || (this
						.getPeriod() != null && castOther.getPeriod() != null && this
						.getPeriod().equals(castOther.getPeriod())))
				&& ((this.getOrderName() == castOther.getOrderName()) || (this
						.getOrderName() != null
						&& castOther.getOrderName() != null && this
						.getOrderName().equals(castOther.getOrderName())))
				&& ((this.getMobilePhone() == castOther.getMobilePhone()) || (this
						.getMobilePhone() != null
						&& castOther.getMobilePhone() != null && this
						.getMobilePhone().equals(castOther.getMobilePhone())))
				&& ((this.getSubmitDatetime() == castOther.getSubmitDatetime()) || (this
						.getSubmitDatetime() != null
						&& castOther.getSubmitDatetime() != null && this
						.getSubmitDatetime().equals(
								castOther.getSubmitDatetime())))
				&& (this.isNight() == castOther.isNight());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getRoomId();
		result = 37 * result
				+ (getRoomName() == null ? 0 : this.getRoomName().hashCode());
		result = 37 * result
				+ (getOrderDate() == null ? 0 : this.getOrderDate().hashCode());
		result = 37
				* result
				+ (getRoomPosition() == null ? 0 : this.getRoomPosition()
						.hashCode());
		result = 37 * result
				+ (getPeriod() == null ? 0 : this.getPeriod().hashCode());
		result = 37 * result
				+ (getOrderName() == null ? 0 : this.getOrderName().hashCode());
		result = 37
				* result
				+ (getMobilePhone() == null ? 0 : this.getMobilePhone()
						.hashCode());
		result = 37
				* result
				+ (getSubmitDatetime() == null ? 0 : this.getSubmitDatetime()
						.hashCode());
		result = 37 * result + (this.isNight() ? 1 : 0);
		return result;
	}

}
