package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * ViewThirdPartyParamValueSimple generated by hbm2java
 */
public class ViewThirdPartyParamValueSimple implements java.io.Serializable {

	private ViewThirdPartyParamValueSimpleId id;

	public ViewThirdPartyParamValueSimple() {
	}

	public ViewThirdPartyParamValueSimple(ViewThirdPartyParamValueSimpleId id) {
		this.id = id;
	}

	public ViewThirdPartyParamValueSimpleId getId() {
		return this.id;
	}

	public void setId(ViewThirdPartyParamValueSimpleId id) {
		this.id = id;
	}

}
