package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * ViewVoiceGroupId generated by hbm2java
 */
public class ViewVoiceGroupId implements java.io.Serializable {

	private long id;
	private Long voiceGroupId;
	private String voiceName;
	private String voicePath;
	private String voiceText;
	private String voiceCat;
	private String voiceDescription;
	private Long voiceCommand;
	private String voiceCommandParam;
	private String voiceThirdPartyApiName;
	private String voiceThirdPartyApiMethod;
	private String voiceThirdPartyApiHeaderParams;
	private String voiceThirdPartyApiUrl;
	private String voiceThirdPartyApiResultType;
	private Boolean voiceThirdPartyApiRunAtServer;
	private String voiceIncProp;
	private String voiceExcProp;
	private String voiceEmotion;
	private boolean voiceEnabled;

	public ViewVoiceGroupId() {
	}

	public ViewVoiceGroupId(long id, String voiceName, String voiceCat,
			String voiceDescription, boolean voiceEnabled) {
		this.id = id;
		this.voiceName = voiceName;
		this.voiceCat = voiceCat;
		this.voiceDescription = voiceDescription;
		this.voiceEnabled = voiceEnabled;
	}

	public ViewVoiceGroupId(long id, Long voiceGroupId, String voiceName,
			String voicePath, String voiceText, String voiceCat,
			String voiceDescription, Long voiceCommand,
			String voiceCommandParam, String voiceThirdPartyApiName,
			String voiceThirdPartyApiMethod,
			String voiceThirdPartyApiHeaderParams,
			String voiceThirdPartyApiUrl, String voiceThirdPartyApiResultType,
			Boolean voiceThirdPartyApiRunAtServer, String voiceIncProp,
			String voiceExcProp, String voiceEmotion, boolean voiceEnabled) {
		this.id = id;
		this.voiceGroupId = voiceGroupId;
		this.voiceName = voiceName;
		this.voicePath = voicePath;
		this.voiceText = voiceText;
		this.voiceCat = voiceCat;
		this.voiceDescription = voiceDescription;
		this.voiceCommand = voiceCommand;
		this.voiceCommandParam = voiceCommandParam;
		this.voiceThirdPartyApiName = voiceThirdPartyApiName;
		this.voiceThirdPartyApiMethod = voiceThirdPartyApiMethod;
		this.voiceThirdPartyApiHeaderParams = voiceThirdPartyApiHeaderParams;
		this.voiceThirdPartyApiUrl = voiceThirdPartyApiUrl;
		this.voiceThirdPartyApiResultType = voiceThirdPartyApiResultType;
		this.voiceThirdPartyApiRunAtServer = voiceThirdPartyApiRunAtServer;
		this.voiceIncProp = voiceIncProp;
		this.voiceExcProp = voiceExcProp;
		this.voiceEmotion = voiceEmotion;
		this.voiceEnabled = voiceEnabled;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Long getVoiceGroupId() {
		return this.voiceGroupId;
	}

	public void setVoiceGroupId(Long voiceGroupId) {
		this.voiceGroupId = voiceGroupId;
	}

	public String getVoiceName() {
		return this.voiceName;
	}

	public void setVoiceName(String voiceName) {
		this.voiceName = voiceName;
	}

	public String getVoicePath() {
		return this.voicePath;
	}

	public void setVoicePath(String voicePath) {
		this.voicePath = voicePath;
	}

	public String getVoiceText() {
		return this.voiceText;
	}

	public void setVoiceText(String voiceText) {
		this.voiceText = voiceText;
	}

	public String getVoiceCat() {
		return this.voiceCat;
	}

	public void setVoiceCat(String voiceCat) {
		this.voiceCat = voiceCat;
	}

	public String getVoiceDescription() {
		return this.voiceDescription;
	}

	public void setVoiceDescription(String voiceDescription) {
		this.voiceDescription = voiceDescription;
	}

	public Long getVoiceCommand() {
		return this.voiceCommand;
	}

	public void setVoiceCommand(Long voiceCommand) {
		this.voiceCommand = voiceCommand;
	}

	public String getVoiceCommandParam() {
		return this.voiceCommandParam;
	}

	public void setVoiceCommandParam(String voiceCommandParam) {
		this.voiceCommandParam = voiceCommandParam;
	}

	public String getVoiceThirdPartyApiName() {
		return this.voiceThirdPartyApiName;
	}

	public void setVoiceThirdPartyApiName(String voiceThirdPartyApiName) {
		this.voiceThirdPartyApiName = voiceThirdPartyApiName;
	}

	public String getVoiceThirdPartyApiMethod() {
		return this.voiceThirdPartyApiMethod;
	}

	public void setVoiceThirdPartyApiMethod(String voiceThirdPartyApiMethod) {
		this.voiceThirdPartyApiMethod = voiceThirdPartyApiMethod;
	}

	public String getVoiceThirdPartyApiHeaderParams() {
		return this.voiceThirdPartyApiHeaderParams;
	}

	public void setVoiceThirdPartyApiHeaderParams(
			String voiceThirdPartyApiHeaderParams) {
		this.voiceThirdPartyApiHeaderParams = voiceThirdPartyApiHeaderParams;
	}

	public String getVoiceThirdPartyApiUrl() {
		return this.voiceThirdPartyApiUrl;
	}

	public void setVoiceThirdPartyApiUrl(String voiceThirdPartyApiUrl) {
		this.voiceThirdPartyApiUrl = voiceThirdPartyApiUrl;
	}

	public String getVoiceThirdPartyApiResultType() {
		return this.voiceThirdPartyApiResultType;
	}

	public void setVoiceThirdPartyApiResultType(
			String voiceThirdPartyApiResultType) {
		this.voiceThirdPartyApiResultType = voiceThirdPartyApiResultType;
	}

	public Boolean getVoiceThirdPartyApiRunAtServer() {
		return this.voiceThirdPartyApiRunAtServer;
	}

	public void setVoiceThirdPartyApiRunAtServer(
			Boolean voiceThirdPartyApiRunAtServer) {
		this.voiceThirdPartyApiRunAtServer = voiceThirdPartyApiRunAtServer;
	}

	public String getVoiceIncProp() {
		return this.voiceIncProp;
	}

	public void setVoiceIncProp(String voiceIncProp) {
		this.voiceIncProp = voiceIncProp;
	}

	public String getVoiceExcProp() {
		return this.voiceExcProp;
	}

	public void setVoiceExcProp(String voiceExcProp) {
		this.voiceExcProp = voiceExcProp;
	}

	public String getVoiceEmotion() {
		return this.voiceEmotion;
	}

	public void setVoiceEmotion(String voiceEmotion) {
		this.voiceEmotion = voiceEmotion;
	}

	public boolean isVoiceEnabled() {
		return this.voiceEnabled;
	}

	public void setVoiceEnabled(boolean voiceEnabled) {
		this.voiceEnabled = voiceEnabled;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ViewVoiceGroupId))
			return false;
		ViewVoiceGroupId castOther = (ViewVoiceGroupId) other;

		return (this.getId() == castOther.getId())
				&& ((this.getVoiceGroupId() == castOther.getVoiceGroupId()) || (this
						.getVoiceGroupId() != null
						&& castOther.getVoiceGroupId() != null && this
						.getVoiceGroupId().equals(castOther.getVoiceGroupId())))
				&& ((this.getVoiceName() == castOther.getVoiceName()) || (this
						.getVoiceName() != null
						&& castOther.getVoiceName() != null && this
						.getVoiceName().equals(castOther.getVoiceName())))
				&& ((this.getVoicePath() == castOther.getVoicePath()) || (this
						.getVoicePath() != null
						&& castOther.getVoicePath() != null && this
						.getVoicePath().equals(castOther.getVoicePath())))
				&& ((this.getVoiceText() == castOther.getVoiceText()) || (this
						.getVoiceText() != null
						&& castOther.getVoiceText() != null && this
						.getVoiceText().equals(castOther.getVoiceText())))
				&& ((this.getVoiceCat() == castOther.getVoiceCat()) || (this
						.getVoiceCat() != null
						&& castOther.getVoiceCat() != null && this
						.getVoiceCat().equals(castOther.getVoiceCat())))
				&& ((this.getVoiceDescription() == castOther
						.getVoiceDescription()) || (this.getVoiceDescription() != null
						&& castOther.getVoiceDescription() != null && this
						.getVoiceDescription().equals(
								castOther.getVoiceDescription())))
				&& ((this.getVoiceCommand() == castOther.getVoiceCommand()) || (this
						.getVoiceCommand() != null
						&& castOther.getVoiceCommand() != null && this
						.getVoiceCommand().equals(castOther.getVoiceCommand())))
				&& ((this.getVoiceCommandParam() == castOther
						.getVoiceCommandParam()) || (this
						.getVoiceCommandParam() != null
						&& castOther.getVoiceCommandParam() != null && this
						.getVoiceCommandParam().equals(
								castOther.getVoiceCommandParam())))
				&& ((this.getVoiceThirdPartyApiName() == castOther
						.getVoiceThirdPartyApiName()) || (this
						.getVoiceThirdPartyApiName() != null
						&& castOther.getVoiceThirdPartyApiName() != null && this
						.getVoiceThirdPartyApiName().equals(
								castOther.getVoiceThirdPartyApiName())))
				&& ((this.getVoiceThirdPartyApiMethod() == castOther
						.getVoiceThirdPartyApiMethod()) || (this
						.getVoiceThirdPartyApiMethod() != null
						&& castOther.getVoiceThirdPartyApiMethod() != null && this
						.getVoiceThirdPartyApiMethod().equals(
								castOther.getVoiceThirdPartyApiMethod())))
				&& ((this.getVoiceThirdPartyApiHeaderParams() == castOther
						.getVoiceThirdPartyApiHeaderParams()) || (this
						.getVoiceThirdPartyApiHeaderParams() != null
						&& castOther.getVoiceThirdPartyApiHeaderParams() != null && this
						.getVoiceThirdPartyApiHeaderParams().equals(
								castOther.getVoiceThirdPartyApiHeaderParams())))
				&& ((this.getVoiceThirdPartyApiUrl() == castOther
						.getVoiceThirdPartyApiUrl()) || (this
						.getVoiceThirdPartyApiUrl() != null
						&& castOther.getVoiceThirdPartyApiUrl() != null && this
						.getVoiceThirdPartyApiUrl().equals(
								castOther.getVoiceThirdPartyApiUrl())))
				&& ((this.getVoiceThirdPartyApiResultType() == castOther
						.getVoiceThirdPartyApiResultType()) || (this
						.getVoiceThirdPartyApiResultType() != null
						&& castOther.getVoiceThirdPartyApiResultType() != null && this
						.getVoiceThirdPartyApiResultType().equals(
								castOther.getVoiceThirdPartyApiResultType())))
				&& ((this.getVoiceThirdPartyApiRunAtServer() == castOther
						.getVoiceThirdPartyApiRunAtServer()) || (this
						.getVoiceThirdPartyApiRunAtServer() != null
						&& castOther.getVoiceThirdPartyApiRunAtServer() != null && this
						.getVoiceThirdPartyApiRunAtServer().equals(
								castOther.getVoiceThirdPartyApiRunAtServer())))
				&& ((this.getVoiceIncProp() == castOther.getVoiceIncProp()) || (this
						.getVoiceIncProp() != null
						&& castOther.getVoiceIncProp() != null && this
						.getVoiceIncProp().equals(castOther.getVoiceIncProp())))
				&& ((this.getVoiceExcProp() == castOther.getVoiceExcProp()) || (this
						.getVoiceExcProp() != null
						&& castOther.getVoiceExcProp() != null && this
						.getVoiceExcProp().equals(castOther.getVoiceExcProp())))
				&& ((this.getVoiceEmotion() == castOther.getVoiceEmotion()) || (this
						.getVoiceEmotion() != null
						&& castOther.getVoiceEmotion() != null && this
						.getVoiceEmotion().equals(castOther.getVoiceEmotion())))
				&& (this.isVoiceEnabled() == castOther.isVoiceEnabled());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getId();
		result = 37
				* result
				+ (getVoiceGroupId() == null ? 0 : this.getVoiceGroupId()
						.hashCode());
		result = 37 * result
				+ (getVoiceName() == null ? 0 : this.getVoiceName().hashCode());
		result = 37 * result
				+ (getVoicePath() == null ? 0 : this.getVoicePath().hashCode());
		result = 37 * result
				+ (getVoiceText() == null ? 0 : this.getVoiceText().hashCode());
		result = 37 * result
				+ (getVoiceCat() == null ? 0 : this.getVoiceCat().hashCode());
		result = 37
				* result
				+ (getVoiceDescription() == null ? 0 : this
						.getVoiceDescription().hashCode());
		result = 37
				* result
				+ (getVoiceCommand() == null ? 0 : this.getVoiceCommand()
						.hashCode());
		result = 37
				* result
				+ (getVoiceCommandParam() == null ? 0 : this
						.getVoiceCommandParam().hashCode());
		result = 37
				* result
				+ (getVoiceThirdPartyApiName() == null ? 0 : this
						.getVoiceThirdPartyApiName().hashCode());
		result = 37
				* result
				+ (getVoiceThirdPartyApiMethod() == null ? 0 : this
						.getVoiceThirdPartyApiMethod().hashCode());
		result = 37
				* result
				+ (getVoiceThirdPartyApiHeaderParams() == null ? 0 : this
						.getVoiceThirdPartyApiHeaderParams().hashCode());
		result = 37
				* result
				+ (getVoiceThirdPartyApiUrl() == null ? 0 : this
						.getVoiceThirdPartyApiUrl().hashCode());
		result = 37
				* result
				+ (getVoiceThirdPartyApiResultType() == null ? 0 : this
						.getVoiceThirdPartyApiResultType().hashCode());
		result = 37
				* result
				+ (getVoiceThirdPartyApiRunAtServer() == null ? 0 : this
						.getVoiceThirdPartyApiRunAtServer().hashCode());
		result = 37
				* result
				+ (getVoiceIncProp() == null ? 0 : this.getVoiceIncProp()
						.hashCode());
		result = 37
				* result
				+ (getVoiceExcProp() == null ? 0 : this.getVoiceExcProp()
						.hashCode());
		result = 37
				* result
				+ (getVoiceEmotion() == null ? 0 : this.getVoiceEmotion()
						.hashCode());
		result = 37 * result + (this.isVoiceEnabled() ? 1 : 0);
		return result;
	}

}
