package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * ViewHuaqin2016ProivderConfrence generated by hbm2java
 */
public class ViewHuaqin2016ProivderConfrence implements java.io.Serializable {

	private ViewHuaqin2016ProivderConfrenceId id;

	public ViewHuaqin2016ProivderConfrence() {
	}

	public ViewHuaqin2016ProivderConfrence(ViewHuaqin2016ProivderConfrenceId id) {
		this.id = id;
	}

	public ViewHuaqin2016ProivderConfrenceId getId() {
		return this.id;
	}

	public void setId(ViewHuaqin2016ProivderConfrenceId id) {
		this.id = id;
	}

}
