package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * ViewRobotConfigWithOwner generated by hbm2java
 */
public class ViewRobotConfigWithOwner implements java.io.Serializable {

	private ViewRobotConfigWithOwnerId id;

	public ViewRobotConfigWithOwner() {
	}

	public ViewRobotConfigWithOwner(ViewRobotConfigWithOwnerId id) {
		this.id = id;
	}

	public ViewRobotConfigWithOwnerId getId() {
		return this.id;
	}

	public void setId(ViewRobotConfigWithOwnerId id) {
		this.id = id;
	}

}
