package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * ViewWordGroupFlowToVoiceGroupRule generated by hbm2java
 */
public class ViewWordGroupFlowToVoiceGroupRule implements java.io.Serializable {

	private ViewWordGroupFlowToVoiceGroupRuleId id;

	public ViewWordGroupFlowToVoiceGroupRule() {
	}

	public ViewWordGroupFlowToVoiceGroupRule(
			ViewWordGroupFlowToVoiceGroupRuleId id) {
		this.id = id;
	}

	public ViewWordGroupFlowToVoiceGroupRuleId getId() {
		return this.id;
	}

	public void setId(ViewWordGroupFlowToVoiceGroupRuleId id) {
		this.id = id;
	}

}
