package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * ViewRobotUserBindlist generated by hbm2java
 */
public class ViewRobotUserBindlist implements java.io.Serializable {

	private ViewRobotUserBindlistId id;

	public ViewRobotUserBindlist() {
	}

	public ViewRobotUserBindlist(ViewRobotUserBindlistId id) {
		this.id = id;
	}

	public ViewRobotUserBindlistId getId() {
		return this.id;
	}

	public void setId(ViewRobotUserBindlistId id) {
		this.id = id;
	}

}
