package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * ViewRobotAppBindListId generated by hbm2java
 */
public class ViewRobotAppBindListId implements java.io.Serializable {

	private String appOwner;
	private long appId;
	private String appPackageName;
	private String appName;
	private String description;
	private String robotImei;
	private String robotName;
	private long userGroupId;
	private String userGroupName;
	private Long lastestVersionCode;
	private String lastestVersionName;
	private String downloadUrl;
	private String releaseNote;
	private Date publishDatetime;
	private Boolean enable;

	public ViewRobotAppBindListId() {
	}

	public ViewRobotAppBindListId(String appOwner, long appId,
			String appPackageName, String appName, String description,
			String robotImei, String robotName, long userGroupId,
			String userGroupName) {
		this.appOwner = appOwner;
		this.appId = appId;
		this.appPackageName = appPackageName;
		this.appName = appName;
		this.description = description;
		this.robotImei = robotImei;
		this.robotName = robotName;
		this.userGroupId = userGroupId;
		this.userGroupName = userGroupName;
	}

	public ViewRobotAppBindListId(String appOwner, long appId,
			String appPackageName, String appName, String description,
			String robotImei, String robotName, long userGroupId,
			String userGroupName, Long lastestVersionCode,
			String lastestVersionName, String downloadUrl, String releaseNote,
			Date publishDatetime, Boolean enable) {
		this.appOwner = appOwner;
		this.appId = appId;
		this.appPackageName = appPackageName;
		this.appName = appName;
		this.description = description;
		this.robotImei = robotImei;
		this.robotName = robotName;
		this.userGroupId = userGroupId;
		this.userGroupName = userGroupName;
		this.lastestVersionCode = lastestVersionCode;
		this.lastestVersionName = lastestVersionName;
		this.downloadUrl = downloadUrl;
		this.releaseNote = releaseNote;
		this.publishDatetime = publishDatetime;
		this.enable = enable;
	}

	public String getAppOwner() {
		return this.appOwner;
	}

	public void setAppOwner(String appOwner) {
		this.appOwner = appOwner;
	}

	public long getAppId() {
		return this.appId;
	}

	public void setAppId(long appId) {
		this.appId = appId;
	}

	public String getAppPackageName() {
		return this.appPackageName;
	}

	public void setAppPackageName(String appPackageName) {
		this.appPackageName = appPackageName;
	}

	public String getAppName() {
		return this.appName;
	}

	public void setAppName(String appName) {
		this.appName = appName;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getRobotImei() {
		return this.robotImei;
	}

	public void setRobotImei(String robotImei) {
		this.robotImei = robotImei;
	}

	public String getRobotName() {
		return this.robotName;
	}

	public void setRobotName(String robotName) {
		this.robotName = robotName;
	}

	public long getUserGroupId() {
		return this.userGroupId;
	}

	public void setUserGroupId(long userGroupId) {
		this.userGroupId = userGroupId;
	}

	public String getUserGroupName() {
		return this.userGroupName;
	}

	public void setUserGroupName(String userGroupName) {
		this.userGroupName = userGroupName;
	}

	public Long getLastestVersionCode() {
		return this.lastestVersionCode;
	}

	public void setLastestVersionCode(Long lastestVersionCode) {
		this.lastestVersionCode = lastestVersionCode;
	}

	public String getLastestVersionName() {
		return this.lastestVersionName;
	}

	public void setLastestVersionName(String lastestVersionName) {
		this.lastestVersionName = lastestVersionName;
	}

	public String getDownloadUrl() {
		return this.downloadUrl;
	}

	public void setDownloadUrl(String downloadUrl) {
		this.downloadUrl = downloadUrl;
	}

	public String getReleaseNote() {
		return this.releaseNote;
	}

	public void setReleaseNote(String releaseNote) {
		this.releaseNote = releaseNote;
	}

	public Date getPublishDatetime() {
		return this.publishDatetime;
	}

	public void setPublishDatetime(Date publishDatetime) {
		this.publishDatetime = publishDatetime;
	}

	public Boolean getEnable() {
		return this.enable;
	}

	public void setEnable(Boolean enable) {
		this.enable = enable;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ViewRobotAppBindListId))
			return false;
		ViewRobotAppBindListId castOther = (ViewRobotAppBindListId) other;

		return ((this.getAppOwner() == castOther.getAppOwner()) || (this
				.getAppOwner() != null && castOther.getAppOwner() != null && this
				.getAppOwner().equals(castOther.getAppOwner())))
				&& (this.getAppId() == castOther.getAppId())
				&& ((this.getAppPackageName() == castOther.getAppPackageName()) || (this
						.getAppPackageName() != null
						&& castOther.getAppPackageName() != null && this
						.getAppPackageName().equals(
								castOther.getAppPackageName())))
				&& ((this.getAppName() == castOther.getAppName()) || (this
						.getAppName() != null && castOther.getAppName() != null && this
						.getAppName().equals(castOther.getAppName())))
				&& ((this.getDescription() == castOther.getDescription()) || (this
						.getDescription() != null
						&& castOther.getDescription() != null && this
						.getDescription().equals(castOther.getDescription())))
				&& ((this.getRobotImei() == castOther.getRobotImei()) || (this
						.getRobotImei() != null
						&& castOther.getRobotImei() != null && this
						.getRobotImei().equals(castOther.getRobotImei())))
				&& ((this.getRobotName() == castOther.getRobotName()) || (this
						.getRobotName() != null
						&& castOther.getRobotName() != null && this
						.getRobotName().equals(castOther.getRobotName())))
				&& (this.getUserGroupId() == castOther.getUserGroupId())
				&& ((this.getUserGroupName() == castOther.getUserGroupName()) || (this
						.getUserGroupName() != null
						&& castOther.getUserGroupName() != null && this
						.getUserGroupName()
						.equals(castOther.getUserGroupName())))
				&& ((this.getLastestVersionCode() == castOther
						.getLastestVersionCode()) || (this
						.getLastestVersionCode() != null
						&& castOther.getLastestVersionCode() != null && this
						.getLastestVersionCode().equals(
								castOther.getLastestVersionCode())))
				&& ((this.getLastestVersionName() == castOther
						.getLastestVersionName()) || (this
						.getLastestVersionName() != null
						&& castOther.getLastestVersionName() != null && this
						.getLastestVersionName().equals(
								castOther.getLastestVersionName())))
				&& ((this.getDownloadUrl() == castOther.getDownloadUrl()) || (this
						.getDownloadUrl() != null
						&& castOther.getDownloadUrl() != null && this
						.getDownloadUrl().equals(castOther.getDownloadUrl())))
				&& ((this.getReleaseNote() == castOther.getReleaseNote()) || (this
						.getReleaseNote() != null
						&& castOther.getReleaseNote() != null && this
						.getReleaseNote().equals(castOther.getReleaseNote())))
				&& ((this.getPublishDatetime() == castOther
						.getPublishDatetime()) || (this.getPublishDatetime() != null
						&& castOther.getPublishDatetime() != null && this
						.getPublishDatetime().equals(
								castOther.getPublishDatetime())))
				&& ((this.getEnable() == castOther.getEnable()) || (this
						.getEnable() != null && castOther.getEnable() != null && this
						.getEnable().equals(castOther.getEnable())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getAppOwner() == null ? 0 : this.getAppOwner().hashCode());
		result = 37 * result + (int) this.getAppId();
		result = 37
				* result
				+ (getAppPackageName() == null ? 0 : this.getAppPackageName()
						.hashCode());
		result = 37 * result
				+ (getAppName() == null ? 0 : this.getAppName().hashCode());
		result = 37
				* result
				+ (getDescription() == null ? 0 : this.getDescription()
						.hashCode());
		result = 37 * result
				+ (getRobotImei() == null ? 0 : this.getRobotImei().hashCode());
		result = 37 * result
				+ (getRobotName() == null ? 0 : this.getRobotName().hashCode());
		result = 37 * result + (int) this.getUserGroupId();
		result = 37
				* result
				+ (getUserGroupName() == null ? 0 : this.getUserGroupName()
						.hashCode());
		result = 37
				* result
				+ (getLastestVersionCode() == null ? 0 : this
						.getLastestVersionCode().hashCode());
		result = 37
				* result
				+ (getLastestVersionName() == null ? 0 : this
						.getLastestVersionName().hashCode());
		result = 37
				* result
				+ (getDownloadUrl() == null ? 0 : this.getDownloadUrl()
						.hashCode());
		result = 37
				* result
				+ (getReleaseNote() == null ? 0 : this.getReleaseNote()
						.hashCode());
		result = 37
				* result
				+ (getPublishDatetime() == null ? 0 : this.getPublishDatetime()
						.hashCode());
		result = 37 * result
				+ (getEnable() == null ? 0 : this.getEnable().hashCode());
		return result;
	}

}
