package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * ViewUserStatusLastestUpdatetimeId generated by hbm2java
 */
public class ViewUserStatusLastestUpdatetimeId implements java.io.Serializable {

	private long userId;
	private Date latestUpdateDatetime;

	public ViewUserStatusLastestUpdatetimeId() {
	}

	public ViewUserStatusLastestUpdatetimeId(long userId,
			Date latestUpdateDatetime) {
		this.userId = userId;
		this.latestUpdateDatetime = latestUpdateDatetime;
	}

	public long getUserId() {
		return this.userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	public Date getLatestUpdateDatetime() {
		return this.latestUpdateDatetime;
	}

	public void setLatestUpdateDatetime(Date latestUpdateDatetime) {
		this.latestUpdateDatetime = latestUpdateDatetime;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ViewUserStatusLastestUpdatetimeId))
			return false;
		ViewUserStatusLastestUpdatetimeId castOther = (ViewUserStatusLastestUpdatetimeId) other;

		return (this.getUserId() == castOther.getUserId())
				&& ((this.getLatestUpdateDatetime() == castOther
						.getLatestUpdateDatetime()) || (this
						.getLatestUpdateDatetime() != null
						&& castOther.getLatestUpdateDatetime() != null && this
						.getLatestUpdateDatetime().equals(
								castOther.getLatestUpdateDatetime())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getUserId();
		result = 37
				* result
				+ (getLatestUpdateDatetime() == null ? 0 : this
						.getLatestUpdateDatetime().hashCode());
		return result;
	}

}
