package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * ViewConfigUserGroup generated by hbm2java
 */
public class ViewConfigUserGroup implements java.io.Serializable {

	private ViewConfigUserGroupId id;

	public ViewConfigUserGroup() {
	}

	public ViewConfigUserGroup(ViewConfigUserGroupId id) {
		this.id = id;
	}

	public ViewConfigUserGroupId getId() {
		return this.id;
	}

	public void setId(ViewConfigUserGroupId id) {
		this.id = id;
	}

}
