package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * ViewRobotBelong generated by hbm2java
 */
public class ViewRobotBelong implements java.io.Serializable {

	private ViewRobotBelongId id;

	public ViewRobotBelong() {
	}

	public ViewRobotBelong(ViewRobotBelongId id) {
		this.id = id;
	}

	public ViewRobotBelongId getId() {
		return this.id;
	}

	public void setId(ViewRobotBelongId id) {
		this.id = id;
	}

}
