package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * ViewValue generated by hbm2java
 */
public class ViewValue implements java.io.Serializable {

	private String value;

	public ViewValue() {
	}

	public ViewValue(String value) {
		this.value = value;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
