package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * ViewKeyWordsSimpleId generated by hbm2java
 */
public class ViewKeyWordsSimpleId implements java.io.Serializable {

	private long id;
	private String kw;
	private long cat;
	private String sound;

	public ViewKeyWordsSimpleId() {
	}

	public ViewKeyWordsSimpleId(long id, String kw, long cat, String sound) {
		this.id = id;
		this.kw = kw;
		this.cat = cat;
		this.sound = sound;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getKw() {
		return this.kw;
	}

	public void setKw(String kw) {
		this.kw = kw;
	}

	public long getCat() {
		return this.cat;
	}

	public void setCat(long cat) {
		this.cat = cat;
	}

	public String getSound() {
		return this.sound;
	}

	public void setSound(String sound) {
		this.sound = sound;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ViewKeyWordsSimpleId))
			return false;
		ViewKeyWordsSimpleId castOther = (ViewKeyWordsSimpleId) other;

		return (this.getId() == castOther.getId())
				&& ((this.getKw() == castOther.getKw()) || (this.getKw() != null
						&& castOther.getKw() != null && this.getKw().equals(
						castOther.getKw())))
				&& (this.getCat() == castOther.getCat())
				&& ((this.getSound() == castOther.getSound()) || (this
						.getSound() != null && castOther.getSound() != null && this
						.getSound().equals(castOther.getSound())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getId();
		result = 37 * result + (getKw() == null ? 0 : this.getKw().hashCode());
		result = 37 * result + (int) this.getCat();
		result = 37 * result
				+ (getSound() == null ? 0 : this.getSound().hashCode());
		return result;
	}

}
