package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * ViewChatHistory generated by hbm2java
 */
public class ViewChatHistory implements java.io.Serializable {

	private ViewChatHistoryId id;

	public ViewChatHistory() {
	}

	public ViewChatHistory(ViewChatHistoryId id) {
		this.id = id;
	}

	public ViewChatHistoryId getId() {
		return this.id;
	}

	public void setId(ViewChatHistoryId id) {
		this.id = id;
	}

}
