package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * ViewEntity generated by hbm2java
 */
public class ViewEntity implements java.io.Serializable {

	private ViewEntityId id;

	public ViewEntity() {
	}

	public ViewEntity(ViewEntityId id) {
		this.id = id;
	}

	public ViewEntityId getId() {
		return this.id;
	}

	public void setId(ViewEntityId id) {
		this.id = id;
	}

}
