package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * ViewWordGroupFlowToVoiceGroupRuleSimpleId generated by hbm2java
 */
public class ViewWordGroupFlowToVoiceGroupRuleSimpleId implements
		java.io.Serializable {

	private String keyWord;
	private String voiceName;
	private String voicePath;
	private String voiceText;
	private String voiceCat;
	private String voiceDescription;
	private Long voiceCommand;
	private String voiceCommandParam;
	private boolean keyWordGroupInc1Exc0;
	private String voiceIncProp;
	private String voiceExcProp;
	private String voiceEmotion;
	private boolean enable;
	private Boolean voiceThirdPartyApiRunAtServer;
	private String voiceThirdPartyApiResultType;
	private String voiceThirdPartyApiUrl;
	private String voiceThirdPartyApiHeaderParams;
	private String voiceThirdPartyApiMethod;
	private String voiceThirdPartyApiName;

	public ViewWordGroupFlowToVoiceGroupRuleSimpleId() {
	}

	public ViewWordGroupFlowToVoiceGroupRuleSimpleId(String keyWord,
			String voiceName, String voiceCat, String voiceDescription,
			boolean keyWordGroupInc1Exc0, boolean enable) {
		this.keyWord = keyWord;
		this.voiceName = voiceName;
		this.voiceCat = voiceCat;
		this.voiceDescription = voiceDescription;
		this.keyWordGroupInc1Exc0 = keyWordGroupInc1Exc0;
		this.enable = enable;
	}

	public ViewWordGroupFlowToVoiceGroupRuleSimpleId(String keyWord,
			String voiceName, String voicePath, String voiceText,
			String voiceCat, String voiceDescription, Long voiceCommand,
			String voiceCommandParam, boolean keyWordGroupInc1Exc0,
			String voiceIncProp, String voiceExcProp, String voiceEmotion,
			boolean enable, Boolean voiceThirdPartyApiRunAtServer,
			String voiceThirdPartyApiResultType, String voiceThirdPartyApiUrl,
			String voiceThirdPartyApiHeaderParams,
			String voiceThirdPartyApiMethod, String voiceThirdPartyApiName) {
		this.keyWord = keyWord;
		this.voiceName = voiceName;
		this.voicePath = voicePath;
		this.voiceText = voiceText;
		this.voiceCat = voiceCat;
		this.voiceDescription = voiceDescription;
		this.voiceCommand = voiceCommand;
		this.voiceCommandParam = voiceCommandParam;
		this.keyWordGroupInc1Exc0 = keyWordGroupInc1Exc0;
		this.voiceIncProp = voiceIncProp;
		this.voiceExcProp = voiceExcProp;
		this.voiceEmotion = voiceEmotion;
		this.enable = enable;
		this.voiceThirdPartyApiRunAtServer = voiceThirdPartyApiRunAtServer;
		this.voiceThirdPartyApiResultType = voiceThirdPartyApiResultType;
		this.voiceThirdPartyApiUrl = voiceThirdPartyApiUrl;
		this.voiceThirdPartyApiHeaderParams = voiceThirdPartyApiHeaderParams;
		this.voiceThirdPartyApiMethod = voiceThirdPartyApiMethod;
		this.voiceThirdPartyApiName = voiceThirdPartyApiName;
	}

	public String getKeyWord() {
		return this.keyWord;
	}

	public void setKeyWord(String keyWord) {
		this.keyWord = keyWord;
	}

	public String getVoiceName() {
		return this.voiceName;
	}

	public void setVoiceName(String voiceName) {
		this.voiceName = voiceName;
	}

	public String getVoicePath() {
		return this.voicePath;
	}

	public void setVoicePath(String voicePath) {
		this.voicePath = voicePath;
	}

	public String getVoiceText() {
		return this.voiceText;
	}

	public void setVoiceText(String voiceText) {
		this.voiceText = voiceText;
	}

	public String getVoiceCat() {
		return this.voiceCat;
	}

	public void setVoiceCat(String voiceCat) {
		this.voiceCat = voiceCat;
	}

	public String getVoiceDescription() {
		return this.voiceDescription;
	}

	public void setVoiceDescription(String voiceDescription) {
		this.voiceDescription = voiceDescription;
	}

	public Long getVoiceCommand() {
		return this.voiceCommand;
	}

	public void setVoiceCommand(Long voiceCommand) {
		this.voiceCommand = voiceCommand;
	}

	public String getVoiceCommandParam() {
		return this.voiceCommandParam;
	}

	public void setVoiceCommandParam(String voiceCommandParam) {
		this.voiceCommandParam = voiceCommandParam;
	}

	public boolean isKeyWordGroupInc1Exc0() {
		return this.keyWordGroupInc1Exc0;
	}

	public void setKeyWordGroupInc1Exc0(boolean keyWordGroupInc1Exc0) {
		this.keyWordGroupInc1Exc0 = keyWordGroupInc1Exc0;
	}

	public String getVoiceIncProp() {
		return this.voiceIncProp;
	}

	public void setVoiceIncProp(String voiceIncProp) {
		this.voiceIncProp = voiceIncProp;
	}

	public String getVoiceExcProp() {
		return this.voiceExcProp;
	}

	public void setVoiceExcProp(String voiceExcProp) {
		this.voiceExcProp = voiceExcProp;
	}

	public String getVoiceEmotion() {
		return this.voiceEmotion;
	}

	public void setVoiceEmotion(String voiceEmotion) {
		this.voiceEmotion = voiceEmotion;
	}

	public boolean isEnable() {
		return this.enable;
	}

	public void setEnable(boolean enable) {
		this.enable = enable;
	}

	public Boolean getVoiceThirdPartyApiRunAtServer() {
		return this.voiceThirdPartyApiRunAtServer;
	}

	public void setVoiceThirdPartyApiRunAtServer(
			Boolean voiceThirdPartyApiRunAtServer) {
		this.voiceThirdPartyApiRunAtServer = voiceThirdPartyApiRunAtServer;
	}

	public String getVoiceThirdPartyApiResultType() {
		return this.voiceThirdPartyApiResultType;
	}

	public void setVoiceThirdPartyApiResultType(
			String voiceThirdPartyApiResultType) {
		this.voiceThirdPartyApiResultType = voiceThirdPartyApiResultType;
	}

	public String getVoiceThirdPartyApiUrl() {
		return this.voiceThirdPartyApiUrl;
	}

	public void setVoiceThirdPartyApiUrl(String voiceThirdPartyApiUrl) {
		this.voiceThirdPartyApiUrl = voiceThirdPartyApiUrl;
	}

	public String getVoiceThirdPartyApiHeaderParams() {
		return this.voiceThirdPartyApiHeaderParams;
	}

	public void setVoiceThirdPartyApiHeaderParams(
			String voiceThirdPartyApiHeaderParams) {
		this.voiceThirdPartyApiHeaderParams = voiceThirdPartyApiHeaderParams;
	}

	public String getVoiceThirdPartyApiMethod() {
		return this.voiceThirdPartyApiMethod;
	}

	public void setVoiceThirdPartyApiMethod(String voiceThirdPartyApiMethod) {
		this.voiceThirdPartyApiMethod = voiceThirdPartyApiMethod;
	}

	public String getVoiceThirdPartyApiName() {
		return this.voiceThirdPartyApiName;
	}

	public void setVoiceThirdPartyApiName(String voiceThirdPartyApiName) {
		this.voiceThirdPartyApiName = voiceThirdPartyApiName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ViewWordGroupFlowToVoiceGroupRuleSimpleId))
			return false;
		ViewWordGroupFlowToVoiceGroupRuleSimpleId castOther = (ViewWordGroupFlowToVoiceGroupRuleSimpleId) other;

		return ((this.getKeyWord() == castOther.getKeyWord()) || (this
				.getKeyWord() != null && castOther.getKeyWord() != null && this
				.getKeyWord().equals(castOther.getKeyWord())))
				&& ((this.getVoiceName() == castOther.getVoiceName()) || (this
						.getVoiceName() != null
						&& castOther.getVoiceName() != null && this
						.getVoiceName().equals(castOther.getVoiceName())))
				&& ((this.getVoicePath() == castOther.getVoicePath()) || (this
						.getVoicePath() != null
						&& castOther.getVoicePath() != null && this
						.getVoicePath().equals(castOther.getVoicePath())))
				&& ((this.getVoiceText() == castOther.getVoiceText()) || (this
						.getVoiceText() != null
						&& castOther.getVoiceText() != null && this
						.getVoiceText().equals(castOther.getVoiceText())))
				&& ((this.getVoiceCat() == castOther.getVoiceCat()) || (this
						.getVoiceCat() != null
						&& castOther.getVoiceCat() != null && this
						.getVoiceCat().equals(castOther.getVoiceCat())))
				&& ((this.getVoiceDescription() == castOther
						.getVoiceDescription()) || (this.getVoiceDescription() != null
						&& castOther.getVoiceDescription() != null && this
						.getVoiceDescription().equals(
								castOther.getVoiceDescription())))
				&& ((this.getVoiceCommand() == castOther.getVoiceCommand()) || (this
						.getVoiceCommand() != null
						&& castOther.getVoiceCommand() != null && this
						.getVoiceCommand().equals(castOther.getVoiceCommand())))
				&& ((this.getVoiceCommandParam() == castOther
						.getVoiceCommandParam()) || (this
						.getVoiceCommandParam() != null
						&& castOther.getVoiceCommandParam() != null && this
						.getVoiceCommandParam().equals(
								castOther.getVoiceCommandParam())))
				&& (this.isKeyWordGroupInc1Exc0() == castOther
						.isKeyWordGroupInc1Exc0())
				&& ((this.getVoiceIncProp() == castOther.getVoiceIncProp()) || (this
						.getVoiceIncProp() != null
						&& castOther.getVoiceIncProp() != null && this
						.getVoiceIncProp().equals(castOther.getVoiceIncProp())))
				&& ((this.getVoiceExcProp() == castOther.getVoiceExcProp()) || (this
						.getVoiceExcProp() != null
						&& castOther.getVoiceExcProp() != null && this
						.getVoiceExcProp().equals(castOther.getVoiceExcProp())))
				&& ((this.getVoiceEmotion() == castOther.getVoiceEmotion()) || (this
						.getVoiceEmotion() != null
						&& castOther.getVoiceEmotion() != null && this
						.getVoiceEmotion().equals(castOther.getVoiceEmotion())))
				&& (this.isEnable() == castOther.isEnable())
				&& ((this.getVoiceThirdPartyApiRunAtServer() == castOther
						.getVoiceThirdPartyApiRunAtServer()) || (this
						.getVoiceThirdPartyApiRunAtServer() != null
						&& castOther.getVoiceThirdPartyApiRunAtServer() != null && this
						.getVoiceThirdPartyApiRunAtServer().equals(
								castOther.getVoiceThirdPartyApiRunAtServer())))
				&& ((this.getVoiceThirdPartyApiResultType() == castOther
						.getVoiceThirdPartyApiResultType()) || (this
						.getVoiceThirdPartyApiResultType() != null
						&& castOther.getVoiceThirdPartyApiResultType() != null && this
						.getVoiceThirdPartyApiResultType().equals(
								castOther.getVoiceThirdPartyApiResultType())))
				&& ((this.getVoiceThirdPartyApiUrl() == castOther
						.getVoiceThirdPartyApiUrl()) || (this
						.getVoiceThirdPartyApiUrl() != null
						&& castOther.getVoiceThirdPartyApiUrl() != null && this
						.getVoiceThirdPartyApiUrl().equals(
								castOther.getVoiceThirdPartyApiUrl())))
				&& ((this.getVoiceThirdPartyApiHeaderParams() == castOther
						.getVoiceThirdPartyApiHeaderParams()) || (this
						.getVoiceThirdPartyApiHeaderParams() != null
						&& castOther.getVoiceThirdPartyApiHeaderParams() != null && this
						.getVoiceThirdPartyApiHeaderParams().equals(
								castOther.getVoiceThirdPartyApiHeaderParams())))
				&& ((this.getVoiceThirdPartyApiMethod() == castOther
						.getVoiceThirdPartyApiMethod()) || (this
						.getVoiceThirdPartyApiMethod() != null
						&& castOther.getVoiceThirdPartyApiMethod() != null && this
						.getVoiceThirdPartyApiMethod().equals(
								castOther.getVoiceThirdPartyApiMethod())))
				&& ((this.getVoiceThirdPartyApiName() == castOther
						.getVoiceThirdPartyApiName()) || (this
						.getVoiceThirdPartyApiName() != null
						&& castOther.getVoiceThirdPartyApiName() != null && this
						.getVoiceThirdPartyApiName().equals(
								castOther.getVoiceThirdPartyApiName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getKeyWord() == null ? 0 : this.getKeyWord().hashCode());
		result = 37 * result
				+ (getVoiceName() == null ? 0 : this.getVoiceName().hashCode());
		result = 37 * result
				+ (getVoicePath() == null ? 0 : this.getVoicePath().hashCode());
		result = 37 * result
				+ (getVoiceText() == null ? 0 : this.getVoiceText().hashCode());
		result = 37 * result
				+ (getVoiceCat() == null ? 0 : this.getVoiceCat().hashCode());
		result = 37
				* result
				+ (getVoiceDescription() == null ? 0 : this
						.getVoiceDescription().hashCode());
		result = 37
				* result
				+ (getVoiceCommand() == null ? 0 : this.getVoiceCommand()
						.hashCode());
		result = 37
				* result
				+ (getVoiceCommandParam() == null ? 0 : this
						.getVoiceCommandParam().hashCode());
		result = 37 * result + (this.isKeyWordGroupInc1Exc0() ? 1 : 0);
		result = 37
				* result
				+ (getVoiceIncProp() == null ? 0 : this.getVoiceIncProp()
						.hashCode());
		result = 37
				* result
				+ (getVoiceExcProp() == null ? 0 : this.getVoiceExcProp()
						.hashCode());
		result = 37
				* result
				+ (getVoiceEmotion() == null ? 0 : this.getVoiceEmotion()
						.hashCode());
		result = 37 * result + (this.isEnable() ? 1 : 0);
		result = 37
				* result
				+ (getVoiceThirdPartyApiRunAtServer() == null ? 0 : this
						.getVoiceThirdPartyApiRunAtServer().hashCode());
		result = 37
				* result
				+ (getVoiceThirdPartyApiResultType() == null ? 0 : this
						.getVoiceThirdPartyApiResultType().hashCode());
		result = 37
				* result
				+ (getVoiceThirdPartyApiUrl() == null ? 0 : this
						.getVoiceThirdPartyApiUrl().hashCode());
		result = 37
				* result
				+ (getVoiceThirdPartyApiHeaderParams() == null ? 0 : this
						.getVoiceThirdPartyApiHeaderParams().hashCode());
		result = 37
				* result
				+ (getVoiceThirdPartyApiMethod() == null ? 0 : this
						.getVoiceThirdPartyApiMethod().hashCode());
		result = 37
				* result
				+ (getVoiceThirdPartyApiName() == null ? 0 : this
						.getVoiceThirdPartyApiName().hashCode());
		return result;
	}

}
