package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * ViewThirdPartyParamsValue generated by hbm2java
 */
public class ViewThirdPartyParamsValue implements java.io.Serializable {

	private ViewThirdPartyParamsValueId id;

	public ViewThirdPartyParamsValue() {
	}

	public ViewThirdPartyParamsValue(ViewThirdPartyParamsValueId id) {
		this.id = id;
	}

	public ViewThirdPartyParamsValueId getId() {
		return this.id;
	}

	public void setId(ViewThirdPartyParamsValueId id) {
		this.id = id;
	}

}
