package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * ViewRobotUserBindlistId generated by hbm2java
 */
public class ViewRobotUserBindlistId implements java.io.Serializable {

	private long robotId;
	private String robotImei;
	private String robotName;
	private Date activateDatetime;
	private long activateUserId;
	private String activdateUserName;
	private long activdateUserId;
	private String activdateUserGroupName;
	private Boolean robotOnline;
	private String robotSessionId;
	private Date robotStatusUpdateTime;

	public ViewRobotUserBindlistId() {
	}

	public ViewRobotUserBindlistId(long robotId, String robotImei,
			String robotName, Date activateDatetime, long activateUserId,
			String activdateUserName, long activdateUserId,
			String activdateUserGroupName) {
		this.robotId = robotId;
		this.robotImei = robotImei;
		this.robotName = robotName;
		this.activateDatetime = activateDatetime;
		this.activateUserId = activateUserId;
		this.activdateUserName = activdateUserName;
		this.activdateUserId = activdateUserId;
		this.activdateUserGroupName = activdateUserGroupName;
	}

	public ViewRobotUserBindlistId(long robotId, String robotImei,
			String robotName, Date activateDatetime, long activateUserId,
			String activdateUserName, long activdateUserId,
			String activdateUserGroupName, Boolean robotOnline,
			String robotSessionId, Date robotStatusUpdateTime) {
		this.robotId = robotId;
		this.robotImei = robotImei;
		this.robotName = robotName;
		this.activateDatetime = activateDatetime;
		this.activateUserId = activateUserId;
		this.activdateUserName = activdateUserName;
		this.activdateUserId = activdateUserId;
		this.activdateUserGroupName = activdateUserGroupName;
		this.robotOnline = robotOnline;
		this.robotSessionId = robotSessionId;
		this.robotStatusUpdateTime = robotStatusUpdateTime;
	}

	public long getRobotId() {
		return this.robotId;
	}

	public void setRobotId(long robotId) {
		this.robotId = robotId;
	}

	public String getRobotImei() {
		return this.robotImei;
	}

	public void setRobotImei(String robotImei) {
		this.robotImei = robotImei;
	}

	public String getRobotName() {
		return this.robotName;
	}

	public void setRobotName(String robotName) {
		this.robotName = robotName;
	}

	public Date getActivateDatetime() {
		return this.activateDatetime;
	}

	public void setActivateDatetime(Date activateDatetime) {
		this.activateDatetime = activateDatetime;
	}

	public long getActivateUserId() {
		return this.activateUserId;
	}

	public void setActivateUserId(long activateUserId) {
		this.activateUserId = activateUserId;
	}

	public String getActivdateUserName() {
		return this.activdateUserName;
	}

	public void setActivdateUserName(String activdateUserName) {
		this.activdateUserName = activdateUserName;
	}

	public long getActivdateUserId() {
		return this.activdateUserId;
	}

	public void setActivdateUserId(long activdateUserId) {
		this.activdateUserId = activdateUserId;
	}

	public String getActivdateUserGroupName() {
		return this.activdateUserGroupName;
	}

	public void setActivdateUserGroupName(String activdateUserGroupName) {
		this.activdateUserGroupName = activdateUserGroupName;
	}

	public Boolean getRobotOnline() {
		return this.robotOnline;
	}

	public void setRobotOnline(Boolean robotOnline) {
		this.robotOnline = robotOnline;
	}

	public String getRobotSessionId() {
		return this.robotSessionId;
	}

	public void setRobotSessionId(String robotSessionId) {
		this.robotSessionId = robotSessionId;
	}

	public Date getRobotStatusUpdateTime() {
		return this.robotStatusUpdateTime;
	}

	public void setRobotStatusUpdateTime(Date robotStatusUpdateTime) {
		this.robotStatusUpdateTime = robotStatusUpdateTime;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ViewRobotUserBindlistId))
			return false;
		ViewRobotUserBindlistId castOther = (ViewRobotUserBindlistId) other;

		return (this.getRobotId() == castOther.getRobotId())
				&& ((this.getRobotImei() == castOther.getRobotImei()) || (this
						.getRobotImei() != null
						&& castOther.getRobotImei() != null && this
						.getRobotImei().equals(castOther.getRobotImei())))
				&& ((this.getRobotName() == castOther.getRobotName()) || (this
						.getRobotName() != null
						&& castOther.getRobotName() != null && this
						.getRobotName().equals(castOther.getRobotName())))
				&& ((this.getActivateDatetime() == castOther
						.getActivateDatetime()) || (this.getActivateDatetime() != null
						&& castOther.getActivateDatetime() != null && this
						.getActivateDatetime().equals(
								castOther.getActivateDatetime())))
				&& (this.getActivateUserId() == castOther.getActivateUserId())
				&& ((this.getActivdateUserName() == castOther
						.getActivdateUserName()) || (this
						.getActivdateUserName() != null
						&& castOther.getActivdateUserName() != null && this
						.getActivdateUserName().equals(
								castOther.getActivdateUserName())))
				&& (this.getActivdateUserId() == castOther.getActivdateUserId())
				&& ((this.getActivdateUserGroupName() == castOther
						.getActivdateUserGroupName()) || (this
						.getActivdateUserGroupName() != null
						&& castOther.getActivdateUserGroupName() != null && this
						.getActivdateUserGroupName().equals(
								castOther.getActivdateUserGroupName())))
				&& ((this.getRobotOnline() == castOther.getRobotOnline()) || (this
						.getRobotOnline() != null
						&& castOther.getRobotOnline() != null && this
						.getRobotOnline().equals(castOther.getRobotOnline())))
				&& ((this.getRobotSessionId() == castOther.getRobotSessionId()) || (this
						.getRobotSessionId() != null
						&& castOther.getRobotSessionId() != null && this
						.getRobotSessionId().equals(
								castOther.getRobotSessionId())))
				&& ((this.getRobotStatusUpdateTime() == castOther
						.getRobotStatusUpdateTime()) || (this
						.getRobotStatusUpdateTime() != null
						&& castOther.getRobotStatusUpdateTime() != null && this
						.getRobotStatusUpdateTime().equals(
								castOther.getRobotStatusUpdateTime())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getRobotId();
		result = 37 * result
				+ (getRobotImei() == null ? 0 : this.getRobotImei().hashCode());
		result = 37 * result
				+ (getRobotName() == null ? 0 : this.getRobotName().hashCode());
		result = 37
				* result
				+ (getActivateDatetime() == null ? 0 : this
						.getActivateDatetime().hashCode());
		result = 37 * result + (int) this.getActivateUserId();
		result = 37
				* result
				+ (getActivdateUserName() == null ? 0 : this
						.getActivdateUserName().hashCode());
		result = 37 * result + (int) this.getActivdateUserId();
		result = 37
				* result
				+ (getActivdateUserGroupName() == null ? 0 : this
						.getActivdateUserGroupName().hashCode());
		result = 37
				* result
				+ (getRobotOnline() == null ? 0 : this.getRobotOnline()
						.hashCode());
		result = 37
				* result
				+ (getRobotSessionId() == null ? 0 : this.getRobotSessionId()
						.hashCode());
		result = 37
				* result
				+ (getRobotStatusUpdateTime() == null ? 0 : this
						.getRobotStatusUpdateTime().hashCode());
		return result;
	}

}
