package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * ViewValidThirdPartyApiParamsValueId generated by hbm2java
 */
public class ViewValidThirdPartyApiParamsValueId implements
		java.io.Serializable {

	private long id;
	private long thirdPartyApiId;
	private String descirption;

	public ViewValidThirdPartyApiParamsValueId() {
	}

	public ViewValidThirdPartyApiParamsValueId(long id, long thirdPartyApiId) {
		this.id = id;
		this.thirdPartyApiId = thirdPartyApiId;
	}

	public ViewValidThirdPartyApiParamsValueId(long id, long thirdPartyApiId,
			String descirption) {
		this.id = id;
		this.thirdPartyApiId = thirdPartyApiId;
		this.descirption = descirption;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public long getThirdPartyApiId() {
		return this.thirdPartyApiId;
	}

	public void setThirdPartyApiId(long thirdPartyApiId) {
		this.thirdPartyApiId = thirdPartyApiId;
	}

	public String getDescirption() {
		return this.descirption;
	}

	public void setDescirption(String descirption) {
		this.descirption = descirption;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ViewValidThirdPartyApiParamsValueId))
			return false;
		ViewValidThirdPartyApiParamsValueId castOther = (ViewValidThirdPartyApiParamsValueId) other;

		return (this.getId() == castOther.getId())
				&& (this.getThirdPartyApiId() == castOther.getThirdPartyApiId())
				&& ((this.getDescirption() == castOther.getDescirption()) || (this
						.getDescirption() != null
						&& castOther.getDescirption() != null && this
						.getDescirption().equals(castOther.getDescirption())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getId();
		result = 37 * result + (int) this.getThirdPartyApiId();
		result = 37
				* result
				+ (getDescirption() == null ? 0 : this.getDescirption()
						.hashCode());
		return result;
	}

}
