package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * ViewValidThirdPartyApi generated by hbm2java
 */
public class ViewValidThirdPartyApi implements java.io.Serializable {

	private ViewValidThirdPartyApiId id;

	public ViewValidThirdPartyApi() {
	}

	public ViewValidThirdPartyApi(ViewValidThirdPartyApiId id) {
		this.id = id;
	}

	public ViewValidThirdPartyApiId getId() {
		return this.id;
	}

	public void setId(ViewValidThirdPartyApiId id) {
		this.id = id;
	}

}
