package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * ViewThirdPartyParamsValueId generated by hbm2java
 */
public class ViewThirdPartyParamsValueId implements java.io.Serializable {

	private long id;
	private String description;
	private long thirdPartyApiId;
	private String thirdPartyName;

	public ViewThirdPartyParamsValueId() {
	}

	public ViewThirdPartyParamsValueId(long id, long thirdPartyApiId,
			String thirdPartyName) {
		this.id = id;
		this.thirdPartyApiId = thirdPartyApiId;
		this.thirdPartyName = thirdPartyName;
	}

	public ViewThirdPartyParamsValueId(long id, String description,
			long thirdPartyApiId, String thirdPartyName) {
		this.id = id;
		this.description = description;
		this.thirdPartyApiId = thirdPartyApiId;
		this.thirdPartyName = thirdPartyName;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public long getThirdPartyApiId() {
		return this.thirdPartyApiId;
	}

	public void setThirdPartyApiId(long thirdPartyApiId) {
		this.thirdPartyApiId = thirdPartyApiId;
	}

	public String getThirdPartyName() {
		return this.thirdPartyName;
	}

	public void setThirdPartyName(String thirdPartyName) {
		this.thirdPartyName = thirdPartyName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ViewThirdPartyParamsValueId))
			return false;
		ViewThirdPartyParamsValueId castOther = (ViewThirdPartyParamsValueId) other;

		return (this.getId() == castOther.getId())
				&& ((this.getDescription() == castOther.getDescription()) || (this
						.getDescription() != null
						&& castOther.getDescription() != null && this
						.getDescription().equals(castOther.getDescription())))
				&& (this.getThirdPartyApiId() == castOther.getThirdPartyApiId())
				&& ((this.getThirdPartyName() == castOther.getThirdPartyName()) || (this
						.getThirdPartyName() != null
						&& castOther.getThirdPartyName() != null && this
						.getThirdPartyName().equals(
								castOther.getThirdPartyName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getId();
		result = 37
				* result
				+ (getDescription() == null ? 0 : this.getDescription()
						.hashCode());
		result = 37 * result + (int) this.getThirdPartyApiId();
		result = 37
				* result
				+ (getThirdPartyName() == null ? 0 : this.getThirdPartyName()
						.hashCode());
		return result;
	}

}
