package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * ViewRobotMaxPriorityConfig generated by hbm2java
 */
public class ViewRobotMaxPriorityConfig implements java.io.Serializable {

	private ViewRobotMaxPriorityConfigId id;

	public ViewRobotMaxPriorityConfig() {
	}

	public ViewRobotMaxPriorityConfig(ViewRobotMaxPriorityConfigId id) {
		this.id = id;
	}

	public ViewRobotMaxPriorityConfigId getId() {
		return this.id;
	}

	public void setId(ViewRobotMaxPriorityConfigId id) {
		this.id = id;
	}

}
