package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * ViewRobotBelongId generated by hbm2java
 */
public class ViewRobotBelongId implements java.io.Serializable {

	private long robotId;
	private String robotImei;
	private String robotName;
	private long userGroupId;
	private String userGroupName;

	public ViewRobotBelongId() {
	}

	public ViewRobotBelongId(long robotId, String robotImei, String robotName,
			long userGroupId, String userGroupName) {
		this.robotId = robotId;
		this.robotImei = robotImei;
		this.robotName = robotName;
		this.userGroupId = userGroupId;
		this.userGroupName = userGroupName;
	}

	public long getRobotId() {
		return this.robotId;
	}

	public void setRobotId(long robotId) {
		this.robotId = robotId;
	}

	public String getRobotImei() {
		return this.robotImei;
	}

	public void setRobotImei(String robotImei) {
		this.robotImei = robotImei;
	}

	public String getRobotName() {
		return this.robotName;
	}

	public void setRobotName(String robotName) {
		this.robotName = robotName;
	}

	public long getUserGroupId() {
		return this.userGroupId;
	}

	public void setUserGroupId(long userGroupId) {
		this.userGroupId = userGroupId;
	}

	public String getUserGroupName() {
		return this.userGroupName;
	}

	public void setUserGroupName(String userGroupName) {
		this.userGroupName = userGroupName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ViewRobotBelongId))
			return false;
		ViewRobotBelongId castOther = (ViewRobotBelongId) other;

		return (this.getRobotId() == castOther.getRobotId())
				&& ((this.getRobotImei() == castOther.getRobotImei()) || (this
						.getRobotImei() != null
						&& castOther.getRobotImei() != null && this
						.getRobotImei().equals(castOther.getRobotImei())))
				&& ((this.getRobotName() == castOther.getRobotName()) || (this
						.getRobotName() != null
						&& castOther.getRobotName() != null && this
						.getRobotName().equals(castOther.getRobotName())))
				&& (this.getUserGroupId() == castOther.getUserGroupId())
				&& ((this.getUserGroupName() == castOther.getUserGroupName()) || (this
						.getUserGroupName() != null
						&& castOther.getUserGroupName() != null && this
						.getUserGroupName()
						.equals(castOther.getUserGroupName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getRobotId();
		result = 37 * result
				+ (getRobotImei() == null ? 0 : this.getRobotImei().hashCode());
		result = 37 * result
				+ (getRobotName() == null ? 0 : this.getRobotName().hashCode());
		result = 37 * result + (int) this.getUserGroupId();
		result = 37
				* result
				+ (getUserGroupName() == null ? 0 : this.getUserGroupName()
						.hashCode());
		return result;
	}

}
