package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * ViewConfig generated by hbm2java
 */
public class ViewConfig implements java.io.Serializable {

	private ViewConfigId id;

	public ViewConfig() {
	}

	public ViewConfig(ViewConfigId id) {
		this.id = id;
	}

	public ViewConfigId getId() {
		return this.id;
	}

	public void setId(ViewConfigId id) {
		this.id = id;
	}

}
