package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * ViewVoiceGroup generated by hbm2java
 */
public class ViewVoiceGroup implements java.io.Serializable {

	private ViewVoiceGroupId id;

	public ViewVoiceGroup() {
	}

	public ViewVoiceGroup(ViewVoiceGroupId id) {
		this.id = id;
	}

	public ViewVoiceGroupId getId() {
		return this.id;
	}

	public void setId(ViewVoiceGroupId id) {
		this.id = id;
	}

}
