package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * ViewUserLastestStatus generated by hbm2java
 */
public class ViewUserLastestStatus implements java.io.Serializable {

	private ViewUserLastestStatusId id;

	public ViewUserLastestStatus() {
	}

	public ViewUserLastestStatus(ViewUserLastestStatusId id) {
		this.id = id;
	}

	public ViewUserLastestStatusId getId() {
		return this.id;
	}

	public void setId(ViewUserLastestStatusId id) {
		this.id = id;
	}

}
