package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * ViewRobotManualTalkCacheId generated by hbm2java
 */
public class ViewRobotManualTalkCacheId implements java.io.Serializable {

	private String imei;
	private String name;
	private Date activateDatetime;
	private long activateUserId;
	private boolean manualMode;
	private String description;
	private String voiceName;
	private String path;
	private String text;
	private String cat;
	private String voiceDescription;
	private Long command;
	private String commandParam;
	private String thirdPartyApiName;
	private String thirdPartyApiMethod;
	private String thirdPartyApiHeaderParams;
	private String thirdPartyApiUrl;
	private String thirdPartyApiResultType;
	private Boolean thirdPartyApiRunAtServer;
	private String incProp;
	private String excProp;
	private String emotion;
	private boolean enabled;
	private long robotId;
	private long voiceId;
	private Date createDatetime;

	public ViewRobotManualTalkCacheId() {
	}

	public ViewRobotManualTalkCacheId(String imei, String name,
			Date activateDatetime, long activateUserId, boolean manualMode,
			String voiceName, String cat, String voiceDescription,
			boolean enabled, long robotId, long voiceId, Date createDatetime) {
		this.imei = imei;
		this.name = name;
		this.activateDatetime = activateDatetime;
		this.activateUserId = activateUserId;
		this.manualMode = manualMode;
		this.voiceName = voiceName;
		this.cat = cat;
		this.voiceDescription = voiceDescription;
		this.enabled = enabled;
		this.robotId = robotId;
		this.voiceId = voiceId;
		this.createDatetime = createDatetime;
	}

	public ViewRobotManualTalkCacheId(String imei, String name,
			Date activateDatetime, long activateUserId, boolean manualMode,
			String description, String voiceName, String path, String text,
			String cat, String voiceDescription, Long command,
			String commandParam, String thirdPartyApiName,
			String thirdPartyApiMethod, String thirdPartyApiHeaderParams,
			String thirdPartyApiUrl, String thirdPartyApiResultType,
			Boolean thirdPartyApiRunAtServer, String incProp, String excProp,
			String emotion, boolean enabled, long robotId, long voiceId,
			Date createDatetime) {
		this.imei = imei;
		this.name = name;
		this.activateDatetime = activateDatetime;
		this.activateUserId = activateUserId;
		this.manualMode = manualMode;
		this.description = description;
		this.voiceName = voiceName;
		this.path = path;
		this.text = text;
		this.cat = cat;
		this.voiceDescription = voiceDescription;
		this.command = command;
		this.commandParam = commandParam;
		this.thirdPartyApiName = thirdPartyApiName;
		this.thirdPartyApiMethod = thirdPartyApiMethod;
		this.thirdPartyApiHeaderParams = thirdPartyApiHeaderParams;
		this.thirdPartyApiUrl = thirdPartyApiUrl;
		this.thirdPartyApiResultType = thirdPartyApiResultType;
		this.thirdPartyApiRunAtServer = thirdPartyApiRunAtServer;
		this.incProp = incProp;
		this.excProp = excProp;
		this.emotion = emotion;
		this.enabled = enabled;
		this.robotId = robotId;
		this.voiceId = voiceId;
		this.createDatetime = createDatetime;
	}

	public String getImei() {
		return this.imei;
	}

	public void setImei(String imei) {
		this.imei = imei;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getActivateDatetime() {
		return this.activateDatetime;
	}

	public void setActivateDatetime(Date activateDatetime) {
		this.activateDatetime = activateDatetime;
	}

	public long getActivateUserId() {
		return this.activateUserId;
	}

	public void setActivateUserId(long activateUserId) {
		this.activateUserId = activateUserId;
	}

	public boolean isManualMode() {
		return this.manualMode;
	}

	public void setManualMode(boolean manualMode) {
		this.manualMode = manualMode;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getVoiceName() {
		return this.voiceName;
	}

	public void setVoiceName(String voiceName) {
		this.voiceName = voiceName;
	}

	public String getPath() {
		return this.path;
	}

	public void setPath(String path) {
		this.path = path;
	}

	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

	public String getCat() {
		return this.cat;
	}

	public void setCat(String cat) {
		this.cat = cat;
	}

	public String getVoiceDescription() {
		return this.voiceDescription;
	}

	public void setVoiceDescription(String voiceDescription) {
		this.voiceDescription = voiceDescription;
	}

	public Long getCommand() {
		return this.command;
	}

	public void setCommand(Long command) {
		this.command = command;
	}

	public String getCommandParam() {
		return this.commandParam;
	}

	public void setCommandParam(String commandParam) {
		this.commandParam = commandParam;
	}

	public String getThirdPartyApiName() {
		return this.thirdPartyApiName;
	}

	public void setThirdPartyApiName(String thirdPartyApiName) {
		this.thirdPartyApiName = thirdPartyApiName;
	}

	public String getThirdPartyApiMethod() {
		return this.thirdPartyApiMethod;
	}

	public void setThirdPartyApiMethod(String thirdPartyApiMethod) {
		this.thirdPartyApiMethod = thirdPartyApiMethod;
	}

	public String getThirdPartyApiHeaderParams() {
		return this.thirdPartyApiHeaderParams;
	}

	public void setThirdPartyApiHeaderParams(String thirdPartyApiHeaderParams) {
		this.thirdPartyApiHeaderParams = thirdPartyApiHeaderParams;
	}

	public String getThirdPartyApiUrl() {
		return this.thirdPartyApiUrl;
	}

	public void setThirdPartyApiUrl(String thirdPartyApiUrl) {
		this.thirdPartyApiUrl = thirdPartyApiUrl;
	}

	public String getThirdPartyApiResultType() {
		return this.thirdPartyApiResultType;
	}

	public void setThirdPartyApiResultType(String thirdPartyApiResultType) {
		this.thirdPartyApiResultType = thirdPartyApiResultType;
	}

	public Boolean getThirdPartyApiRunAtServer() {
		return this.thirdPartyApiRunAtServer;
	}

	public void setThirdPartyApiRunAtServer(Boolean thirdPartyApiRunAtServer) {
		this.thirdPartyApiRunAtServer = thirdPartyApiRunAtServer;
	}

	public String getIncProp() {
		return this.incProp;
	}

	public void setIncProp(String incProp) {
		this.incProp = incProp;
	}

	public String getExcProp() {
		return this.excProp;
	}

	public void setExcProp(String excProp) {
		this.excProp = excProp;
	}

	public String getEmotion() {
		return this.emotion;
	}

	public void setEmotion(String emotion) {
		this.emotion = emotion;
	}

	public boolean isEnabled() {
		return this.enabled;
	}

	public void setEnabled(boolean enabled) {
		this.enabled = enabled;
	}

	public long getRobotId() {
		return this.robotId;
	}

	public void setRobotId(long robotId) {
		this.robotId = robotId;
	}

	public long getVoiceId() {
		return this.voiceId;
	}

	public void setVoiceId(long voiceId) {
		this.voiceId = voiceId;
	}

	public Date getCreateDatetime() {
		return this.createDatetime;
	}

	public void setCreateDatetime(Date createDatetime) {
		this.createDatetime = createDatetime;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ViewRobotManualTalkCacheId))
			return false;
		ViewRobotManualTalkCacheId castOther = (ViewRobotManualTalkCacheId) other;

		return ((this.getImei() == castOther.getImei()) || (this.getImei() != null
				&& castOther.getImei() != null && this.getImei().equals(
				castOther.getImei())))
				&& ((this.getName() == castOther.getName()) || (this.getName() != null
						&& castOther.getName() != null && this.getName()
						.equals(castOther.getName())))
				&& ((this.getActivateDatetime() == castOther
						.getActivateDatetime()) || (this.getActivateDatetime() != null
						&& castOther.getActivateDatetime() != null && this
						.getActivateDatetime().equals(
								castOther.getActivateDatetime())))
				&& (this.getActivateUserId() == castOther.getActivateUserId())
				&& (this.isManualMode() == castOther.isManualMode())
				&& ((this.getDescription() == castOther.getDescription()) || (this
						.getDescription() != null
						&& castOther.getDescription() != null && this
						.getDescription().equals(castOther.getDescription())))
				&& ((this.getVoiceName() == castOther.getVoiceName()) || (this
						.getVoiceName() != null
						&& castOther.getVoiceName() != null && this
						.getVoiceName().equals(castOther.getVoiceName())))
				&& ((this.getPath() == castOther.getPath()) || (this.getPath() != null
						&& castOther.getPath() != null && this.getPath()
						.equals(castOther.getPath())))
				&& ((this.getText() == castOther.getText()) || (this.getText() != null
						&& castOther.getText() != null && this.getText()
						.equals(castOther.getText())))
				&& ((this.getCat() == castOther.getCat()) || (this.getCat() != null
						&& castOther.getCat() != null && this.getCat().equals(
						castOther.getCat())))
				&& ((this.getVoiceDescription() == castOther
						.getVoiceDescription()) || (this.getVoiceDescription() != null
						&& castOther.getVoiceDescription() != null && this
						.getVoiceDescription().equals(
								castOther.getVoiceDescription())))
				&& ((this.getCommand() == castOther.getCommand()) || (this
						.getCommand() != null && castOther.getCommand() != null && this
						.getCommand().equals(castOther.getCommand())))
				&& ((this.getCommandParam() == castOther.getCommandParam()) || (this
						.getCommandParam() != null
						&& castOther.getCommandParam() != null && this
						.getCommandParam().equals(castOther.getCommandParam())))
				&& ((this.getThirdPartyApiName() == castOther
						.getThirdPartyApiName()) || (this
						.getThirdPartyApiName() != null
						&& castOther.getThirdPartyApiName() != null && this
						.getThirdPartyApiName().equals(
								castOther.getThirdPartyApiName())))
				&& ((this.getThirdPartyApiMethod() == castOther
						.getThirdPartyApiMethod()) || (this
						.getThirdPartyApiMethod() != null
						&& castOther.getThirdPartyApiMethod() != null && this
						.getThirdPartyApiMethod().equals(
								castOther.getThirdPartyApiMethod())))
				&& ((this.getThirdPartyApiHeaderParams() == castOther
						.getThirdPartyApiHeaderParams()) || (this
						.getThirdPartyApiHeaderParams() != null
						&& castOther.getThirdPartyApiHeaderParams() != null && this
						.getThirdPartyApiHeaderParams().equals(
								castOther.getThirdPartyApiHeaderParams())))
				&& ((this.getThirdPartyApiUrl() == castOther
						.getThirdPartyApiUrl()) || (this.getThirdPartyApiUrl() != null
						&& castOther.getThirdPartyApiUrl() != null && this
						.getThirdPartyApiUrl().equals(
								castOther.getThirdPartyApiUrl())))
				&& ((this.getThirdPartyApiResultType() == castOther
						.getThirdPartyApiResultType()) || (this
						.getThirdPartyApiResultType() != null
						&& castOther.getThirdPartyApiResultType() != null && this
						.getThirdPartyApiResultType().equals(
								castOther.getThirdPartyApiResultType())))
				&& ((this.getThirdPartyApiRunAtServer() == castOther
						.getThirdPartyApiRunAtServer()) || (this
						.getThirdPartyApiRunAtServer() != null
						&& castOther.getThirdPartyApiRunAtServer() != null && this
						.getThirdPartyApiRunAtServer().equals(
								castOther.getThirdPartyApiRunAtServer())))
				&& ((this.getIncProp() == castOther.getIncProp()) || (this
						.getIncProp() != null && castOther.getIncProp() != null && this
						.getIncProp().equals(castOther.getIncProp())))
				&& ((this.getExcProp() == castOther.getExcProp()) || (this
						.getExcProp() != null && castOther.getExcProp() != null && this
						.getExcProp().equals(castOther.getExcProp())))
				&& ((this.getEmotion() == castOther.getEmotion()) || (this
						.getEmotion() != null && castOther.getEmotion() != null && this
						.getEmotion().equals(castOther.getEmotion())))
				&& (this.isEnabled() == castOther.isEnabled())
				&& (this.getRobotId() == castOther.getRobotId())
				&& (this.getVoiceId() == castOther.getVoiceId())
				&& ((this.getCreateDatetime() == castOther.getCreateDatetime()) || (this
						.getCreateDatetime() != null
						&& castOther.getCreateDatetime() != null && this
						.getCreateDatetime().equals(
								castOther.getCreateDatetime())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getImei() == null ? 0 : this.getImei().hashCode());
		result = 37 * result
				+ (getName() == null ? 0 : this.getName().hashCode());
		result = 37
				* result
				+ (getActivateDatetime() == null ? 0 : this
						.getActivateDatetime().hashCode());
		result = 37 * result + (int) this.getActivateUserId();
		result = 37 * result + (this.isManualMode() ? 1 : 0);
		result = 37
				* result
				+ (getDescription() == null ? 0 : this.getDescription()
						.hashCode());
		result = 37 * result
				+ (getVoiceName() == null ? 0 : this.getVoiceName().hashCode());
		result = 37 * result
				+ (getPath() == null ? 0 : this.getPath().hashCode());
		result = 37 * result
				+ (getText() == null ? 0 : this.getText().hashCode());
		result = 37 * result
				+ (getCat() == null ? 0 : this.getCat().hashCode());
		result = 37
				* result
				+ (getVoiceDescription() == null ? 0 : this
						.getVoiceDescription().hashCode());
		result = 37 * result
				+ (getCommand() == null ? 0 : this.getCommand().hashCode());
		result = 37
				* result
				+ (getCommandParam() == null ? 0 : this.getCommandParam()
						.hashCode());
		result = 37
				* result
				+ (getThirdPartyApiName() == null ? 0 : this
						.getThirdPartyApiName().hashCode());
		result = 37
				* result
				+ (getThirdPartyApiMethod() == null ? 0 : this
						.getThirdPartyApiMethod().hashCode());
		result = 37
				* result
				+ (getThirdPartyApiHeaderParams() == null ? 0 : this
						.getThirdPartyApiHeaderParams().hashCode());
		result = 37
				* result
				+ (getThirdPartyApiUrl() == null ? 0 : this
						.getThirdPartyApiUrl().hashCode());
		result = 37
				* result
				+ (getThirdPartyApiResultType() == null ? 0 : this
						.getThirdPartyApiResultType().hashCode());
		result = 37
				* result
				+ (getThirdPartyApiRunAtServer() == null ? 0 : this
						.getThirdPartyApiRunAtServer().hashCode());
		result = 37 * result
				+ (getIncProp() == null ? 0 : this.getIncProp().hashCode());
		result = 37 * result
				+ (getExcProp() == null ? 0 : this.getExcProp().hashCode());
		result = 37 * result
				+ (getEmotion() == null ? 0 : this.getEmotion().hashCode());
		result = 37 * result + (this.isEnabled() ? 1 : 0);
		result = 37 * result + (int) this.getRobotId();
		result = 37 * result + (int) this.getVoiceId();
		result = 37
				* result
				+ (getCreateDatetime() == null ? 0 : this.getCreateDatetime()
						.hashCode());
		return result;
	}

}
