package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * ViewRequestProperty generated by hbm2java
 */
public class ViewRequestProperty implements java.io.Serializable {

	private ViewRequestPropertyId id;

	public ViewRequestProperty() {
	}

	public ViewRequestProperty(ViewRequestPropertyId id) {
		this.id = id;
	}

	public ViewRequestPropertyId getId() {
		return this.id;
	}

	public void setId(ViewRequestPropertyId id) {
		this.id = id;
	}

}
