package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * ViewWordGroupFlowToVoiceGroupRuleSimple generated by hbm2java
 */
public class ViewWordGroupFlowToVoiceGroupRuleSimple implements
		java.io.Serializable {

	private ViewWordGroupFlowToVoiceGroupRuleSimpleId id;

	public ViewWordGroupFlowToVoiceGroupRuleSimple() {
	}

	public ViewWordGroupFlowToVoiceGroupRuleSimple(
			ViewWordGroupFlowToVoiceGroupRuleSimpleId id) {
		this.id = id;
	}

	public ViewWordGroupFlowToVoiceGroupRuleSimpleId getId() {
		return this.id;
	}

	public void setId(ViewWordGroupFlowToVoiceGroupRuleSimpleId id) {
		this.id = id;
	}

}
