package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * ViewRobotAppLastestUpdatetimeId generated by hbm2java
 */
public class ViewRobotAppLastestUpdatetimeId implements java.io.Serializable {

	private long robotAppId;
	private Date latestPublishDatetime;

	public ViewRobotAppLastestUpdatetimeId() {
	}

	public ViewRobotAppLastestUpdatetimeId(long robotAppId,
			Date latestPublishDatetime) {
		this.robotAppId = robotAppId;
		this.latestPublishDatetime = latestPublishDatetime;
	}

	public long getRobotAppId() {
		return this.robotAppId;
	}

	public void setRobotAppId(long robotAppId) {
		this.robotAppId = robotAppId;
	}

	public Date getLatestPublishDatetime() {
		return this.latestPublishDatetime;
	}

	public void setLatestPublishDatetime(Date latestPublishDatetime) {
		this.latestPublishDatetime = latestPublishDatetime;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ViewRobotAppLastestUpdatetimeId))
			return false;
		ViewRobotAppLastestUpdatetimeId castOther = (ViewRobotAppLastestUpdatetimeId) other;

		return (this.getRobotAppId() == castOther.getRobotAppId())
				&& ((this.getLatestPublishDatetime() == castOther
						.getLatestPublishDatetime()) || (this
						.getLatestPublishDatetime() != null
						&& castOther.getLatestPublishDatetime() != null && this
						.getLatestPublishDatetime().equals(
								castOther.getLatestPublishDatetime())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getRobotAppId();
		result = 37
				* result
				+ (getLatestPublishDatetime() == null ? 0 : this
						.getLatestPublishDatetime().hashCode());
		return result;
	}

}
