package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * ViewRobotTagsId generated by hbm2java
 */
public class ViewRobotTagsId implements java.io.Serializable {

	private String imei;
	private long robotId;
	private String tag;

	public ViewRobotTagsId() {
	}

	public ViewRobotTagsId(String imei, long robotId) {
		this.imei = imei;
		this.robotId = robotId;
	}

	public ViewRobotTagsId(String imei, long robotId, String tag) {
		this.imei = imei;
		this.robotId = robotId;
		this.tag = tag;
	}

	public String getImei() {
		return this.imei;
	}

	public void setImei(String imei) {
		this.imei = imei;
	}

	public long getRobotId() {
		return this.robotId;
	}

	public void setRobotId(long robotId) {
		this.robotId = robotId;
	}

	public String getTag() {
		return this.tag;
	}

	public void setTag(String tag) {
		this.tag = tag;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ViewRobotTagsId))
			return false;
		ViewRobotTagsId castOther = (ViewRobotTagsId) other;

		return ((this.getImei() == castOther.getImei()) || (this.getImei() != null
				&& castOther.getImei() != null && this.getImei().equals(
				castOther.getImei())))
				&& (this.getRobotId() == castOther.getRobotId())
				&& ((this.getTag() == castOther.getTag()) || (this.getTag() != null
						&& castOther.getTag() != null && this.getTag().equals(
						castOther.getTag())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getImei() == null ? 0 : this.getImei().hashCode());
		result = 37 * result + (int) this.getRobotId();
		result = 37 * result
				+ (getTag() == null ? 0 : this.getTag().hashCode());
		return result;
	}

}
