package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * ViewRobotMaxPriorityConfigWithOwner generated by hbm2java
 */
public class ViewRobotMaxPriorityConfigWithOwner implements
		java.io.Serializable {

	private ViewRobotMaxPriorityConfigWithOwnerId id;

	public ViewRobotMaxPriorityConfigWithOwner() {
	}

	public ViewRobotMaxPriorityConfigWithOwner(
			ViewRobotMaxPriorityConfigWithOwnerId id) {
		this.id = id;
	}

	public ViewRobotMaxPriorityConfigWithOwnerId getId() {
		return this.id;
	}

	public void setId(ViewRobotMaxPriorityConfigWithOwnerId id) {
		this.id = id;
	}

}
