package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * ViewValidThirdPartyApiParams generated by hbm2java
 */
public class ViewValidThirdPartyApiParams implements java.io.Serializable {

	private ViewValidThirdPartyApiParamsId id;

	public ViewValidThirdPartyApiParams() {
	}

	public ViewValidThirdPartyApiParams(ViewValidThirdPartyApiParamsId id) {
		this.id = id;
	}

	public ViewValidThirdPartyApiParamsId getId() {
		return this.id;
	}

	public void setId(ViewValidThirdPartyApiParamsId id) {
		this.id = id;
	}

}
