package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * ViewThirdPartySimple generated by hbm2java
 */
public class ViewThirdPartySimple implements java.io.Serializable {

	private ViewThirdPartySimpleId id;

	public ViewThirdPartySimple() {
	}

	public ViewThirdPartySimple(ViewThirdPartySimpleId id) {
		this.id = id;
	}

	public ViewThirdPartySimpleId getId() {
		return this.id;
	}

	public void setId(ViewThirdPartySimpleId id) {
		this.id = id;
	}

}
