package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * ViewRobotConfigForEditor generated by hbm2java
 */
public class ViewRobotConfigForEditor implements java.io.Serializable {

	private ViewRobotConfigForEditorId id;

	public ViewRobotConfigForEditor() {
	}

	public ViewRobotConfigForEditor(ViewRobotConfigForEditorId id) {
		this.id = id;
	}

	public ViewRobotConfigForEditorId getId() {
		return this.id;
	}

	public void setId(ViewRobotConfigForEditorId id) {
		this.id = id;
	}

}
