package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * ViewRtcSessionStatusLastestUpdatetime generated by hbm2java
 */
public class ViewRtcSessionStatusLastestUpdatetime implements
		java.io.Serializable {

	private ViewRtcSessionStatusLastestUpdatetimeId id;

	public ViewRtcSessionStatusLastestUpdatetime() {
	}

	public ViewRtcSessionStatusLastestUpdatetime(
			ViewRtcSessionStatusLastestUpdatetimeId id) {
		this.id = id;
	}

	public ViewRtcSessionStatusLastestUpdatetimeId getId() {
		return this.id;
	}

	public void setId(ViewRtcSessionStatusLastestUpdatetimeId id) {
		this.id = id;
	}

}
