package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * ViewKeyWordGroup generated by hbm2java
 */
public class ViewKeyWordGroup implements java.io.Serializable {

	private ViewKeyWordGroupId id;

	public ViewKeyWordGroup() {
	}

	public ViewKeyWordGroup(ViewKeyWordGroupId id) {
		this.id = id;
	}

	public ViewKeyWordGroupId getId() {
		return this.id;
	}

	public void setId(ViewKeyWordGroupId id) {
		this.id = id;
	}

}
