package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * ViewRequestPropertyId generated by hbm2java
 */
public class ViewRequestPropertyId implements java.io.Serializable {

	private String requestId;
	private Date datetime;
	private String path;
	private String propertyName;
	private String propertyValue;
	private boolean isNumeric;

	public ViewRequestPropertyId() {
	}

	public ViewRequestPropertyId(String requestId, String path,
			String propertyName, String propertyValue, boolean isNumeric) {
		this.requestId = requestId;
		this.path = path;
		this.propertyName = propertyName;
		this.propertyValue = propertyValue;
		this.isNumeric = isNumeric;
	}

	public ViewRequestPropertyId(String requestId, Date datetime, String path,
			String propertyName, String propertyValue, boolean isNumeric) {
		this.requestId = requestId;
		this.datetime = datetime;
		this.path = path;
		this.propertyName = propertyName;
		this.propertyValue = propertyValue;
		this.isNumeric = isNumeric;
	}

	public String getRequestId() {
		return this.requestId;
	}

	public void setRequestId(String requestId) {
		this.requestId = requestId;
	}

	public Date getDatetime() {
		return this.datetime;
	}

	public void setDatetime(Date datetime) {
		this.datetime = datetime;
	}

	public String getPath() {
		return this.path;
	}

	public void setPath(String path) {
		this.path = path;
	}

	public String getPropertyName() {
		return this.propertyName;
	}

	public void setPropertyName(String propertyName) {
		this.propertyName = propertyName;
	}

	public String getPropertyValue() {
		return this.propertyValue;
	}

	public void setPropertyValue(String propertyValue) {
		this.propertyValue = propertyValue;
	}

	public boolean isIsNumeric() {
		return this.isNumeric;
	}

	public void setIsNumeric(boolean isNumeric) {
		this.isNumeric = isNumeric;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ViewRequestPropertyId))
			return false;
		ViewRequestPropertyId castOther = (ViewRequestPropertyId) other;

		return ((this.getRequestId() == castOther.getRequestId()) || (this
				.getRequestId() != null && castOther.getRequestId() != null && this
				.getRequestId().equals(castOther.getRequestId())))
				&& ((this.getDatetime() == castOther.getDatetime()) || (this
						.getDatetime() != null
						&& castOther.getDatetime() != null && this
						.getDatetime().equals(castOther.getDatetime())))
				&& ((this.getPath() == castOther.getPath()) || (this.getPath() != null
						&& castOther.getPath() != null && this.getPath()
						.equals(castOther.getPath())))
				&& ((this.getPropertyName() == castOther.getPropertyName()) || (this
						.getPropertyName() != null
						&& castOther.getPropertyName() != null && this
						.getPropertyName().equals(castOther.getPropertyName())))
				&& ((this.getPropertyValue() == castOther.getPropertyValue()) || (this
						.getPropertyValue() != null
						&& castOther.getPropertyValue() != null && this
						.getPropertyValue()
						.equals(castOther.getPropertyValue())))
				&& (this.isIsNumeric() == castOther.isIsNumeric());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getRequestId() == null ? 0 : this.getRequestId().hashCode());
		result = 37 * result
				+ (getDatetime() == null ? 0 : this.getDatetime().hashCode());
		result = 37 * result
				+ (getPath() == null ? 0 : this.getPath().hashCode());
		result = 37
				* result
				+ (getPropertyName() == null ? 0 : this.getPropertyName()
						.hashCode());
		result = 37
				* result
				+ (getPropertyValue() == null ? 0 : this.getPropertyValue()
						.hashCode());
		result = 37 * result + (this.isIsNumeric() ? 1 : 0);
		return result;
	}

}
