package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * ViewUserGroupScene generated by hbm2java
 */
public class ViewUserGroupScene implements java.io.Serializable {

	private ViewUserGroupSceneId id;

	public ViewUserGroupScene() {
	}

	public ViewUserGroupScene(ViewUserGroupSceneId id) {
		this.id = id;
	}

	public ViewUserGroupSceneId getId() {
		return this.id;
	}

	public void setId(ViewUserGroupSceneId id) {
		this.id = id;
	}

}
