package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * ViewRobotAppVersionRequired generated by hbm2java
 */
public class ViewRobotAppVersionRequired implements java.io.Serializable {

	private ViewRobotAppVersionRequiredId id;

	public ViewRobotAppVersionRequired() {
	}

	public ViewRobotAppVersionRequired(ViewRobotAppVersionRequiredId id) {
		this.id = id;
	}

	public ViewRobotAppVersionRequiredId getId() {
		return this.id;
	}

	public void setId(ViewRobotAppVersionRequiredId id) {
		this.id = id;
	}

}
