package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * ViewNvp generated by hbm2java
 */
public class ViewNvp implements java.io.Serializable {

	private ViewNvpId id;

	public ViewNvp() {
	}

	public ViewNvp(ViewNvpId id) {
		this.id = id;
	}

	public ViewNvpId getId() {
		return this.id;
	}

	public void setId(ViewNvpId id) {
		this.id = id;
	}

}
