package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * ViewRobotAppLastestVersionCodeId generated by hbm2java
 */
public class ViewRobotAppLastestVersionCodeId implements java.io.Serializable {

	private long robotAppId;
	private Long lastestVersionCode;

	public ViewRobotAppLastestVersionCodeId() {
	}

	public ViewRobotAppLastestVersionCodeId(long robotAppId) {
		this.robotAppId = robotAppId;
	}

	public ViewRobotAppLastestVersionCodeId(long robotAppId,
			Long lastestVersionCode) {
		this.robotAppId = robotAppId;
		this.lastestVersionCode = lastestVersionCode;
	}

	public long getRobotAppId() {
		return this.robotAppId;
	}

	public void setRobotAppId(long robotAppId) {
		this.robotAppId = robotAppId;
	}

	public Long getLastestVersionCode() {
		return this.lastestVersionCode;
	}

	public void setLastestVersionCode(Long lastestVersionCode) {
		this.lastestVersionCode = lastestVersionCode;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ViewRobotAppLastestVersionCodeId))
			return false;
		ViewRobotAppLastestVersionCodeId castOther = (ViewRobotAppLastestVersionCodeId) other;

		return (this.getRobotAppId() == castOther.getRobotAppId())
				&& ((this.getLastestVersionCode() == castOther
						.getLastestVersionCode()) || (this
						.getLastestVersionCode() != null
						&& castOther.getLastestVersionCode() != null && this
						.getLastestVersionCode().equals(
								castOther.getLastestVersionCode())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getRobotAppId();
		result = 37
				* result
				+ (getLastestVersionCode() == null ? 0 : this
						.getLastestVersionCode().hashCode());
		return result;
	}

}
