package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * ViewThirdPartyApiParamValueItemId generated by hbm2java
 */
public class ViewThirdPartyApiParamValueItemId implements java.io.Serializable {

	private long apiId;
	private String apiName;
	private long valueId;
	private String valueName;
	private long paramId;
	private String paramName;
	private String paramDescription;
	private String paramValue;
	private String description;

	public ViewThirdPartyApiParamValueItemId() {
	}

	public ViewThirdPartyApiParamValueItemId(long apiId, String apiName,
			long valueId, String valueName, long paramId, String paramName,
			String paramDescription, String paramValue) {
		this.apiId = apiId;
		this.apiName = apiName;
		this.valueId = valueId;
		this.valueName = valueName;
		this.paramId = paramId;
		this.paramName = paramName;
		this.paramDescription = paramDescription;
		this.paramValue = paramValue;
	}

	public ViewThirdPartyApiParamValueItemId(long apiId, String apiName,
			long valueId, String valueName, long paramId, String paramName,
			String paramDescription, String paramValue, String description) {
		this.apiId = apiId;
		this.apiName = apiName;
		this.valueId = valueId;
		this.valueName = valueName;
		this.paramId = paramId;
		this.paramName = paramName;
		this.paramDescription = paramDescription;
		this.paramValue = paramValue;
		this.description = description;
	}

	public long getApiId() {
		return this.apiId;
	}

	public void setApiId(long apiId) {
		this.apiId = apiId;
	}

	public String getApiName() {
		return this.apiName;
	}

	public void setApiName(String apiName) {
		this.apiName = apiName;
	}

	public long getValueId() {
		return this.valueId;
	}

	public void setValueId(long valueId) {
		this.valueId = valueId;
	}

	public String getValueName() {
		return this.valueName;
	}

	public void setValueName(String valueName) {
		this.valueName = valueName;
	}

	public long getParamId() {
		return this.paramId;
	}

	public void setParamId(long paramId) {
		this.paramId = paramId;
	}

	public String getParamName() {
		return this.paramName;
	}

	public void setParamName(String paramName) {
		this.paramName = paramName;
	}

	public String getParamDescription() {
		return this.paramDescription;
	}

	public void setParamDescription(String paramDescription) {
		this.paramDescription = paramDescription;
	}

	public String getParamValue() {
		return this.paramValue;
	}

	public void setParamValue(String paramValue) {
		this.paramValue = paramValue;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ViewThirdPartyApiParamValueItemId))
			return false;
		ViewThirdPartyApiParamValueItemId castOther = (ViewThirdPartyApiParamValueItemId) other;

		return (this.getApiId() == castOther.getApiId())
				&& ((this.getApiName() == castOther.getApiName()) || (this
						.getApiName() != null && castOther.getApiName() != null && this
						.getApiName().equals(castOther.getApiName())))
				&& (this.getValueId() == castOther.getValueId())
				&& ((this.getValueName() == castOther.getValueName()) || (this
						.getValueName() != null
						&& castOther.getValueName() != null && this
						.getValueName().equals(castOther.getValueName())))
				&& (this.getParamId() == castOther.getParamId())
				&& ((this.getParamName() == castOther.getParamName()) || (this
						.getParamName() != null
						&& castOther.getParamName() != null && this
						.getParamName().equals(castOther.getParamName())))
				&& ((this.getParamDescription() == castOther
						.getParamDescription()) || (this.getParamDescription() != null
						&& castOther.getParamDescription() != null && this
						.getParamDescription().equals(
								castOther.getParamDescription())))
				&& ((this.getParamValue() == castOther.getParamValue()) || (this
						.getParamValue() != null
						&& castOther.getParamValue() != null && this
						.getParamValue().equals(castOther.getParamValue())))
				&& ((this.getDescription() == castOther.getDescription()) || (this
						.getDescription() != null
						&& castOther.getDescription() != null && this
						.getDescription().equals(castOther.getDescription())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getApiId();
		result = 37 * result
				+ (getApiName() == null ? 0 : this.getApiName().hashCode());
		result = 37 * result + (int) this.getValueId();
		result = 37 * result
				+ (getValueName() == null ? 0 : this.getValueName().hashCode());
		result = 37 * result + (int) this.getParamId();
		result = 37 * result
				+ (getParamName() == null ? 0 : this.getParamName().hashCode());
		result = 37
				* result
				+ (getParamDescription() == null ? 0 : this
						.getParamDescription().hashCode());
		result = 37
				* result
				+ (getParamValue() == null ? 0 : this.getParamValue()
						.hashCode());
		result = 37
				* result
				+ (getDescription() == null ? 0 : this.getDescription()
						.hashCode());
		return result;
	}

}
