package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * ViewBizMenutreeId generated by hbm2java
 */
public class ViewBizMenutreeId implements java.io.Serializable {

	private String menuEntryName;
	private long menuId;
	private String menuLabel;
	private String menuExtra;
	private Long parentMenuId;
	private long menuSeq;
	private String action;
	private String actionUri;
	private String actionType;
	private String actionExtra;
	private String actionPackageName;
	private String actionClassName;

	public ViewBizMenutreeId() {
	}

	public ViewBizMenutreeId(String menuEntryName, long menuId,
			String menuLabel, long menuSeq) {
		this.menuEntryName = menuEntryName;
		this.menuId = menuId;
		this.menuLabel = menuLabel;
		this.menuSeq = menuSeq;
	}

	public ViewBizMenutreeId(String menuEntryName, long menuId,
			String menuLabel, String menuExtra, Long parentMenuId,
			long menuSeq, String action, String actionUri, String actionType,
			String actionExtra, String actionPackageName, String actionClassName) {
		this.menuEntryName = menuEntryName;
		this.menuId = menuId;
		this.menuLabel = menuLabel;
		this.menuExtra = menuExtra;
		this.parentMenuId = parentMenuId;
		this.menuSeq = menuSeq;
		this.action = action;
		this.actionUri = actionUri;
		this.actionType = actionType;
		this.actionExtra = actionExtra;
		this.actionPackageName = actionPackageName;
		this.actionClassName = actionClassName;
	}

	public String getMenuEntryName() {
		return this.menuEntryName;
	}

	public void setMenuEntryName(String menuEntryName) {
		this.menuEntryName = menuEntryName;
	}

	public long getMenuId() {
		return this.menuId;
	}

	public void setMenuId(long menuId) {
		this.menuId = menuId;
	}

	public String getMenuLabel() {
		return this.menuLabel;
	}

	public void setMenuLabel(String menuLabel) {
		this.menuLabel = menuLabel;
	}

	public String getMenuExtra() {
		return this.menuExtra;
	}

	public void setMenuExtra(String menuExtra) {
		this.menuExtra = menuExtra;
	}

	public Long getParentMenuId() {
		return this.parentMenuId;
	}

	public void setParentMenuId(Long parentMenuId) {
		this.parentMenuId = parentMenuId;
	}

	public long getMenuSeq() {
		return this.menuSeq;
	}

	public void setMenuSeq(long menuSeq) {
		this.menuSeq = menuSeq;
	}

	public String getAction() {
		return this.action;
	}

	public void setAction(String action) {
		this.action = action;
	}

	public String getActionUri() {
		return this.actionUri;
	}

	public void setActionUri(String actionUri) {
		this.actionUri = actionUri;
	}

	public String getActionType() {
		return this.actionType;
	}

	public void setActionType(String actionType) {
		this.actionType = actionType;
	}

	public String getActionExtra() {
		return this.actionExtra;
	}

	public void setActionExtra(String actionExtra) {
		this.actionExtra = actionExtra;
	}

	public String getActionPackageName() {
		return this.actionPackageName;
	}

	public void setActionPackageName(String actionPackageName) {
		this.actionPackageName = actionPackageName;
	}

	public String getActionClassName() {
		return this.actionClassName;
	}

	public void setActionClassName(String actionClassName) {
		this.actionClassName = actionClassName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ViewBizMenutreeId))
			return false;
		ViewBizMenutreeId castOther = (ViewBizMenutreeId) other;

		return ((this.getMenuEntryName() == castOther.getMenuEntryName()) || (this
				.getMenuEntryName() != null
				&& castOther.getMenuEntryName() != null && this
				.getMenuEntryName().equals(castOther.getMenuEntryName())))
				&& (this.getMenuId() == castOther.getMenuId())
				&& ((this.getMenuLabel() == castOther.getMenuLabel()) || (this
						.getMenuLabel() != null
						&& castOther.getMenuLabel() != null && this
						.getMenuLabel().equals(castOther.getMenuLabel())))
				&& ((this.getMenuExtra() == castOther.getMenuExtra()) || (this
						.getMenuExtra() != null
						&& castOther.getMenuExtra() != null && this
						.getMenuExtra().equals(castOther.getMenuExtra())))
				&& ((this.getParentMenuId() == castOther.getParentMenuId()) || (this
						.getParentMenuId() != null
						&& castOther.getParentMenuId() != null && this
						.getParentMenuId().equals(castOther.getParentMenuId())))
				&& (this.getMenuSeq() == castOther.getMenuSeq())
				&& ((this.getAction() == castOther.getAction()) || (this
						.getAction() != null && castOther.getAction() != null && this
						.getAction().equals(castOther.getAction())))
				&& ((this.getActionUri() == castOther.getActionUri()) || (this
						.getActionUri() != null
						&& castOther.getActionUri() != null && this
						.getActionUri().equals(castOther.getActionUri())))
				&& ((this.getActionType() == castOther.getActionType()) || (this
						.getActionType() != null
						&& castOther.getActionType() != null && this
						.getActionType().equals(castOther.getActionType())))
				&& ((this.getActionExtra() == castOther.getActionExtra()) || (this
						.getActionExtra() != null
						&& castOther.getActionExtra() != null && this
						.getActionExtra().equals(castOther.getActionExtra())))
				&& ((this.getActionPackageName() == castOther
						.getActionPackageName()) || (this
						.getActionPackageName() != null
						&& castOther.getActionPackageName() != null && this
						.getActionPackageName().equals(
								castOther.getActionPackageName())))
				&& ((this.getActionClassName() == castOther
						.getActionClassName()) || (this.getActionClassName() != null
						&& castOther.getActionClassName() != null && this
						.getActionClassName().equals(
								castOther.getActionClassName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getMenuEntryName() == null ? 0 : this.getMenuEntryName()
						.hashCode());
		result = 37 * result + (int) this.getMenuId();
		result = 37 * result
				+ (getMenuLabel() == null ? 0 : this.getMenuLabel().hashCode());
		result = 37 * result
				+ (getMenuExtra() == null ? 0 : this.getMenuExtra().hashCode());
		result = 37
				* result
				+ (getParentMenuId() == null ? 0 : this.getParentMenuId()
						.hashCode());
		result = 37 * result + (int) this.getMenuSeq();
		result = 37 * result
				+ (getAction() == null ? 0 : this.getAction().hashCode());
		result = 37 * result
				+ (getActionUri() == null ? 0 : this.getActionUri().hashCode());
		result = 37
				* result
				+ (getActionType() == null ? 0 : this.getActionType()
						.hashCode());
		result = 37
				* result
				+ (getActionExtra() == null ? 0 : this.getActionExtra()
						.hashCode());
		result = 37
				* result
				+ (getActionPackageName() == null ? 0 : this
						.getActionPackageName().hashCode());
		result = 37
				* result
				+ (getActionClassName() == null ? 0 : this.getActionClassName()
						.hashCode());
		return result;
	}

}
