package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * ViewTodayChatTimelineId generated by hbm2java
 */
public class ViewTodayChatTimelineId implements java.io.Serializable {

	private long id;
	private String request;
	private String requestEpSn;
	private String requestModel;
	private String requestClientIp;
	private String requestClientVersion;
	private String requestAddr;
	private String response1;
	private String kind;
	private String text;
	private String source;
	private Long execMillsecs;
	private Date dateTime;

	public ViewTodayChatTimelineId() {
	}

	public ViewTodayChatTimelineId(long id, String request,
			String requestClientIp, String requestClientVersion,
			String requestAddr, String response1, String text, String source,
			Date dateTime) {
		this.id = id;
		this.request = request;
		this.requestClientIp = requestClientIp;
		this.requestClientVersion = requestClientVersion;
		this.requestAddr = requestAddr;
		this.response1 = response1;
		this.text = text;
		this.source = source;
		this.dateTime = dateTime;
	}

	public ViewTodayChatTimelineId(long id, String request, String requestEpSn,
			String requestModel, String requestClientIp,
			String requestClientVersion, String requestAddr, String response1,
			String kind, String text, String source, Long execMillsecs,
			Date dateTime) {
		this.id = id;
		this.request = request;
		this.requestEpSn = requestEpSn;
		this.requestModel = requestModel;
		this.requestClientIp = requestClientIp;
		this.requestClientVersion = requestClientVersion;
		this.requestAddr = requestAddr;
		this.response1 = response1;
		this.kind = kind;
		this.text = text;
		this.source = source;
		this.execMillsecs = execMillsecs;
		this.dateTime = dateTime;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getRequest() {
		return this.request;
	}

	public void setRequest(String request) {
		this.request = request;
	}

	public String getRequestEpSn() {
		return this.requestEpSn;
	}

	public void setRequestEpSn(String requestEpSn) {
		this.requestEpSn = requestEpSn;
	}

	public String getRequestModel() {
		return this.requestModel;
	}

	public void setRequestModel(String requestModel) {
		this.requestModel = requestModel;
	}

	public String getRequestClientIp() {
		return this.requestClientIp;
	}

	public void setRequestClientIp(String requestClientIp) {
		this.requestClientIp = requestClientIp;
	}

	public String getRequestClientVersion() {
		return this.requestClientVersion;
	}

	public void setRequestClientVersion(String requestClientVersion) {
		this.requestClientVersion = requestClientVersion;
	}

	public String getRequestAddr() {
		return this.requestAddr;
	}

	public void setRequestAddr(String requestAddr) {
		this.requestAddr = requestAddr;
	}

	public String getResponse1() {
		return this.response1;
	}

	public void setResponse1(String response1) {
		this.response1 = response1;
	}

	public String getKind() {
		return this.kind;
	}

	public void setKind(String kind) {
		this.kind = kind;
	}

	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

	public String getSource() {
		return this.source;
	}

	public void setSource(String source) {
		this.source = source;
	}

	public Long getExecMillsecs() {
		return this.execMillsecs;
	}

	public void setExecMillsecs(Long execMillsecs) {
		this.execMillsecs = execMillsecs;
	}

	public Date getDateTime() {
		return this.dateTime;
	}

	public void setDateTime(Date dateTime) {
		this.dateTime = dateTime;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ViewTodayChatTimelineId))
			return false;
		ViewTodayChatTimelineId castOther = (ViewTodayChatTimelineId) other;

		return (this.getId() == castOther.getId())
				&& ((this.getRequest() == castOther.getRequest()) || (this
						.getRequest() != null && castOther.getRequest() != null && this
						.getRequest().equals(castOther.getRequest())))
				&& ((this.getRequestEpSn() == castOther.getRequestEpSn()) || (this
						.getRequestEpSn() != null
						&& castOther.getRequestEpSn() != null && this
						.getRequestEpSn().equals(castOther.getRequestEpSn())))
				&& ((this.getRequestModel() == castOther.getRequestModel()) || (this
						.getRequestModel() != null
						&& castOther.getRequestModel() != null && this
						.getRequestModel().equals(castOther.getRequestModel())))
				&& ((this.getRequestClientIp() == castOther
						.getRequestClientIp()) || (this.getRequestClientIp() != null
						&& castOther.getRequestClientIp() != null && this
						.getRequestClientIp().equals(
								castOther.getRequestClientIp())))
				&& ((this.getRequestClientVersion() == castOther
						.getRequestClientVersion()) || (this
						.getRequestClientVersion() != null
						&& castOther.getRequestClientVersion() != null && this
						.getRequestClientVersion().equals(
								castOther.getRequestClientVersion())))
				&& ((this.getRequestAddr() == castOther.getRequestAddr()) || (this
						.getRequestAddr() != null
						&& castOther.getRequestAddr() != null && this
						.getRequestAddr().equals(castOther.getRequestAddr())))
				&& ((this.getResponse1() == castOther.getResponse1()) || (this
						.getResponse1() != null
						&& castOther.getResponse1() != null && this
						.getResponse1().equals(castOther.getResponse1())))
				&& ((this.getKind() == castOther.getKind()) || (this.getKind() != null
						&& castOther.getKind() != null && this.getKind()
						.equals(castOther.getKind())))
				&& ((this.getText() == castOther.getText()) || (this.getText() != null
						&& castOther.getText() != null && this.getText()
						.equals(castOther.getText())))
				&& ((this.getSource() == castOther.getSource()) || (this
						.getSource() != null && castOther.getSource() != null && this
						.getSource().equals(castOther.getSource())))
				&& ((this.getExecMillsecs() == castOther.getExecMillsecs()) || (this
						.getExecMillsecs() != null
						&& castOther.getExecMillsecs() != null && this
						.getExecMillsecs().equals(castOther.getExecMillsecs())))
				&& ((this.getDateTime() == castOther.getDateTime()) || (this
						.getDateTime() != null
						&& castOther.getDateTime() != null && this
						.getDateTime().equals(castOther.getDateTime())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getId();
		result = 37 * result
				+ (getRequest() == null ? 0 : this.getRequest().hashCode());
		result = 37
				* result
				+ (getRequestEpSn() == null ? 0 : this.getRequestEpSn()
						.hashCode());
		result = 37
				* result
				+ (getRequestModel() == null ? 0 : this.getRequestModel()
						.hashCode());
		result = 37
				* result
				+ (getRequestClientIp() == null ? 0 : this.getRequestClientIp()
						.hashCode());
		result = 37
				* result
				+ (getRequestClientVersion() == null ? 0 : this
						.getRequestClientVersion().hashCode());
		result = 37
				* result
				+ (getRequestAddr() == null ? 0 : this.getRequestAddr()
						.hashCode());
		result = 37 * result
				+ (getResponse1() == null ? 0 : this.getResponse1().hashCode());
		result = 37 * result
				+ (getKind() == null ? 0 : this.getKind().hashCode());
		result = 37 * result
				+ (getText() == null ? 0 : this.getText().hashCode());
		result = 37 * result
				+ (getSource() == null ? 0 : this.getSource().hashCode());
		result = 37
				* result
				+ (getExecMillsecs() == null ? 0 : this.getExecMillsecs()
						.hashCode());
		result = 37 * result
				+ (getDateTime() == null ? 0 : this.getDateTime().hashCode());
		return result;
	}

}
