package org.sgpro.db;

// Generated 2017-6-12 14:40:11 by Hibernate Tools 4.0.0

/**
 * ViewThirdPartyApiParamValueSimple generated by hbm2java
 */
public class ViewThirdPartyApiParamValueSimple implements java.io.Serializable {

	private ViewThirdPartyApiParamValueSimpleId id;

	public ViewThirdPartyApiParamValueSimple() {
	}

	public ViewThirdPartyApiParamValueSimple(
			ViewThirdPartyApiParamValueSimpleId id) {
		this.id = id;
	}

	public ViewThirdPartyApiParamValueSimpleId getId() {
		return this.id;
	}

	public void setId(ViewThirdPartyApiParamValueSimpleId id) {
		this.id = id;
	}

}
