package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * ViewThirdPartyParamSimple generated by hbm2java
 */
public class ViewThirdPartyParamSimple implements java.io.Serializable {

	private ViewThirdPartyParamSimpleId id;

	public ViewThirdPartyParamSimple() {
	}

	public ViewThirdPartyParamSimple(ViewThirdPartyParamSimpleId id) {
		this.id = id;
	}

	public ViewThirdPartyParamSimpleId getId() {
		return this.id;
	}

	public void setId(ViewThirdPartyParamSimpleId id) {
		this.id = id;
	}

}
