package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * ViewUserGroupBindRobotSnId generated by hbm2java
 */
public class ViewUserGroupBindRobotSnId implements java.io.Serializable {

	private String robotSn;
	private long userGroupId;

	public ViewUserGroupBindRobotSnId() {
	}

	public ViewUserGroupBindRobotSnId(String robotSn, long userGroupId) {
		this.robotSn = robotSn;
		this.userGroupId = userGroupId;
	}

	public String getRobotSn() {
		return this.robotSn;
	}

	public void setRobotSn(String robotSn) {
		this.robotSn = robotSn;
	}

	public long getUserGroupId() {
		return this.userGroupId;
	}

	public void setUserGroupId(long userGroupId) {
		this.userGroupId = userGroupId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ViewUserGroupBindRobotSnId))
			return false;
		ViewUserGroupBindRobotSnId castOther = (ViewUserGroupBindRobotSnId) other;

		return ((this.getRobotSn() == castOther.getRobotSn()) || (this
				.getRobotSn() != null && castOther.getRobotSn() != null && this
				.getRobotSn().equals(castOther.getRobotSn())))
				&& (this.getUserGroupId() == castOther.getUserGroupId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getRobotSn() == null ? 0 : this.getRobotSn().hashCode());
		result = 37 * result + (int) this.getUserGroupId();
		return result;
	}

}
