package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * ViewRobotConfigForAppId generated by hbm2java
 */
public class ViewRobotConfigForAppId implements java.io.Serializable {

	private String name;
	private String value;
	private String robotImei;

	public ViewRobotConfigForAppId() {
	}

	public ViewRobotConfigForAppId(String name, String value, String robotImei) {
		this.name = name;
		this.value = value;
		this.robotImei = robotImei;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	public String getRobotImei() {
		return this.robotImei;
	}

	public void setRobotImei(String robotImei) {
		this.robotImei = robotImei;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ViewRobotConfigForAppId))
			return false;
		ViewRobotConfigForAppId castOther = (ViewRobotConfigForAppId) other;

		return ((this.getName() == castOther.getName()) || (this.getName() != null
				&& castOther.getName() != null && this.getName().equals(
				castOther.getName())))
				&& ((this.getValue() == castOther.getValue()) || (this
						.getValue() != null && castOther.getValue() != null && this
						.getValue().equals(castOther.getValue())))
				&& ((this.getRobotImei() == castOther.getRobotImei()) || (this
						.getRobotImei() != null
						&& castOther.getRobotImei() != null && this
						.getRobotImei().equals(castOther.getRobotImei())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getName() == null ? 0 : this.getName().hashCode());
		result = 37 * result
				+ (getValue() == null ? 0 : this.getValue().hashCode());
		result = 37 * result
				+ (getRobotImei() == null ? 0 : this.getRobotImei().hashCode());
		return result;
	}

}
