package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * ViewRobotStatusLastestUpdatetimeId generated by hbm2java
 */
public class ViewRobotStatusLastestUpdatetimeId implements java.io.Serializable {

	private long robotId;
	private Date latestUpdateDatetime;

	public ViewRobotStatusLastestUpdatetimeId() {
	}

	public ViewRobotStatusLastestUpdatetimeId(long robotId,
			Date latestUpdateDatetime) {
		this.robotId = robotId;
		this.latestUpdateDatetime = latestUpdateDatetime;
	}

	public long getRobotId() {
		return this.robotId;
	}

	public void setRobotId(long robotId) {
		this.robotId = robotId;
	}

	public Date getLatestUpdateDatetime() {
		return this.latestUpdateDatetime;
	}

	public void setLatestUpdateDatetime(Date latestUpdateDatetime) {
		this.latestUpdateDatetime = latestUpdateDatetime;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ViewRobotStatusLastestUpdatetimeId))
			return false;
		ViewRobotStatusLastestUpdatetimeId castOther = (ViewRobotStatusLastestUpdatetimeId) other;

		return (this.getRobotId() == castOther.getRobotId())
				&& ((this.getLatestUpdateDatetime() == castOther
						.getLatestUpdateDatetime()) || (this
						.getLatestUpdateDatetime() != null
						&& castOther.getLatestUpdateDatetime() != null && this
						.getLatestUpdateDatetime().equals(
								castOther.getLatestUpdateDatetime())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getRobotId();
		result = 37
				* result
				+ (getLatestUpdateDatetime() == null ? 0 : this
						.getLatestUpdateDatetime().hashCode());
		return result;
	}

}
