package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * ViewVoiceSimple generated by hbm2java
 */
public class ViewVoiceSimple implements java.io.Serializable {

	private ViewVoiceSimpleId id;

	public ViewVoiceSimple() {
	}

	public ViewVoiceSimple(ViewVoiceSimpleId id) {
		this.id = id;
	}

	public ViewVoiceSimpleId getId() {
		return this.id;
	}

	public void setId(ViewVoiceSimpleId id) {
		this.id = id;
	}

}
