package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * ViewTodayChatTimeline generated by hbm2java
 */
public class ViewTodayChatTimeline implements java.io.Serializable {

	private ViewTodayChatTimelineId id;

	public ViewTodayChatTimeline() {
	}

	public ViewTodayChatTimeline(ViewTodayChatTimelineId id) {
		this.id = id;
	}

	public ViewTodayChatTimelineId getId() {
		return this.id;
	}

	public void setId(ViewTodayChatTimelineId id) {
		this.id = id;
	}

}
