package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * ViewRobotConfigForEditorMain generated by hbm2java
 */
public class ViewRobotConfigForEditorMain implements java.io.Serializable {

	private ViewRobotConfigForEditorMainId id;

	public ViewRobotConfigForEditorMain() {
	}

	public ViewRobotConfigForEditorMain(ViewRobotConfigForEditorMainId id) {
		this.id = id;
	}

	public ViewRobotConfigForEditorMainId getId() {
		return this.id;
	}

	public void setId(ViewRobotConfigForEditorMainId id) {
		this.id = id;
	}

}
