package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * ViewWordGroupFlowToVoiceGroupRuleOrignalV2 generated by hbm2java
 */
public class ViewWordGroupFlowToVoiceGroupRuleOrignalV2 implements
		java.io.Serializable {

	private ViewWordGroupFlowToVoiceGroupRuleOrignalV2Id id;

	public ViewWordGroupFlowToVoiceGroupRuleOrignalV2() {
	}

	public ViewWordGroupFlowToVoiceGroupRuleOrignalV2(
			ViewWordGroupFlowToVoiceGroupRuleOrignalV2Id id) {
		this.id = id;
	}

	public ViewWordGroupFlowToVoiceGroupRuleOrignalV2Id getId() {
		return this.id;
	}

	public void setId(ViewWordGroupFlowToVoiceGroupRuleOrignalV2Id id) {
		this.id = id;
	}

}
