package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * ViewEndpointLatestStatusId generated by hbm2java
 */
public class ViewEndpointLatestStatusId implements java.io.Serializable {

	private long endPointId;
	private String endPointName;
	private Date updateDatetime;
	private String wssSessionId;
	private Boolean online;
	private String extraInfo;
	private Boolean isRobot;

	public ViewEndpointLatestStatusId() {
	}

	public ViewEndpointLatestStatusId(long endPointId, String endPointName,
			Date updateDatetime) {
		this.endPointId = endPointId;
		this.endPointName = endPointName;
		this.updateDatetime = updateDatetime;
	}

	public ViewEndpointLatestStatusId(long endPointId, String endPointName,
			Date updateDatetime, String wssSessionId, Boolean online,
			String extraInfo, Boolean isRobot) {
		this.endPointId = endPointId;
		this.endPointName = endPointName;
		this.updateDatetime = updateDatetime;
		this.wssSessionId = wssSessionId;
		this.online = online;
		this.extraInfo = extraInfo;
		this.isRobot = isRobot;
	}

	public long getEndPointId() {
		return this.endPointId;
	}

	public void setEndPointId(long endPointId) {
		this.endPointId = endPointId;
	}

	public String getEndPointName() {
		return this.endPointName;
	}

	public void setEndPointName(String endPointName) {
		this.endPointName = endPointName;
	}

	public Date getUpdateDatetime() {
		return this.updateDatetime;
	}

	public void setUpdateDatetime(Date updateDatetime) {
		this.updateDatetime = updateDatetime;
	}

	public String getWssSessionId() {
		return this.wssSessionId;
	}

	public void setWssSessionId(String wssSessionId) {
		this.wssSessionId = wssSessionId;
	}

	public Boolean getOnline() {
		return this.online;
	}

	public void setOnline(Boolean online) {
		this.online = online;
	}

	public String getExtraInfo() {
		return this.extraInfo;
	}

	public void setExtraInfo(String extraInfo) {
		this.extraInfo = extraInfo;
	}

	public Boolean getIsRobot() {
		return this.isRobot;
	}

	public void setIsRobot(Boolean isRobot) {
		this.isRobot = isRobot;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ViewEndpointLatestStatusId))
			return false;
		ViewEndpointLatestStatusId castOther = (ViewEndpointLatestStatusId) other;

		return (this.getEndPointId() == castOther.getEndPointId())
				&& ((this.getEndPointName() == castOther.getEndPointName()) || (this
						.getEndPointName() != null
						&& castOther.getEndPointName() != null && this
						.getEndPointName().equals(castOther.getEndPointName())))
				&& ((this.getUpdateDatetime() == castOther.getUpdateDatetime()) || (this
						.getUpdateDatetime() != null
						&& castOther.getUpdateDatetime() != null && this
						.getUpdateDatetime().equals(
								castOther.getUpdateDatetime())))
				&& ((this.getWssSessionId() == castOther.getWssSessionId()) || (this
						.getWssSessionId() != null
						&& castOther.getWssSessionId() != null && this
						.getWssSessionId().equals(castOther.getWssSessionId())))
				&& ((this.getOnline() == castOther.getOnline()) || (this
						.getOnline() != null && castOther.getOnline() != null && this
						.getOnline().equals(castOther.getOnline())))
				&& ((this.getExtraInfo() == castOther.getExtraInfo()) || (this
						.getExtraInfo() != null
						&& castOther.getExtraInfo() != null && this
						.getExtraInfo().equals(castOther.getExtraInfo())))
				&& ((this.getIsRobot() == castOther.getIsRobot()) || (this
						.getIsRobot() != null && castOther.getIsRobot() != null && this
						.getIsRobot().equals(castOther.getIsRobot())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getEndPointId();
		result = 37
				* result
				+ (getEndPointName() == null ? 0 : this.getEndPointName()
						.hashCode());
		result = 37
				* result
				+ (getUpdateDatetime() == null ? 0 : this.getUpdateDatetime()
						.hashCode());
		result = 37
				* result
				+ (getWssSessionId() == null ? 0 : this.getWssSessionId()
						.hashCode());
		result = 37 * result
				+ (getOnline() == null ? 0 : this.getOnline().hashCode());
		result = 37 * result
				+ (getExtraInfo() == null ? 0 : this.getExtraInfo().hashCode());
		result = 37 * result
				+ (getIsRobot() == null ? 0 : this.getIsRobot().hashCode());
		return result;
	}

}
