package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * ViewKeyWordsSimple generated by hbm2java
 */
public class ViewKeyWordsSimple implements java.io.Serializable {

	private ViewKeyWordsSimpleId id;

	public ViewKeyWordsSimple() {
	}

	public ViewKeyWordsSimple(ViewKeyWordsSimpleId id) {
		this.id = id;
	}

	public ViewKeyWordsSimpleId getId() {
		return this.id;
	}

	public void setId(ViewKeyWordsSimpleId id) {
		this.id = id;
	}

}
