package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * ViewConfigModuleBitMask generated by hbm2java
 */
public class ViewConfigModuleBitMask implements java.io.Serializable {

	private ViewConfigModuleBitMaskId id;

	public ViewConfigModuleBitMask() {
	}

	public ViewConfigModuleBitMask(ViewConfigModuleBitMaskId id) {
		this.id = id;
	}

	public ViewConfigModuleBitMaskId getId() {
		return this.id;
	}

	public void setId(ViewConfigModuleBitMaskId id) {
		this.id = id;
	}

}
