package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * ViewRobotAppLastestVersionCode generated by hbm2java
 */
public class ViewRobotAppLastestVersionCode implements java.io.Serializable {

	private ViewRobotAppLastestVersionCodeId id;

	public ViewRobotAppLastestVersionCode() {
	}

	public ViewRobotAppLastestVersionCode(ViewRobotAppLastestVersionCodeId id) {
		this.id = id;
	}

	public ViewRobotAppLastestVersionCodeId getId() {
		return this.id;
	}

	public void setId(ViewRobotAppLastestVersionCodeId id) {
		this.id = id;
	}

}
