package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * ViewRobotAppLastestUpdatetime generated by hbm2java
 */
public class ViewRobotAppLastestUpdatetime implements java.io.Serializable {

	private ViewRobotAppLastestUpdatetimeId id;

	public ViewRobotAppLastestUpdatetime() {
	}

	public ViewRobotAppLastestUpdatetime(ViewRobotAppLastestUpdatetimeId id) {
		this.id = id;
	}

	public ViewRobotAppLastestUpdatetimeId getId() {
		return this.id;
	}

	public void setId(ViewRobotAppLastestUpdatetimeId id) {
		this.id = id;
	}

}
