package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * ViewOrderRoom generated by hbm2java
 */
public class ViewOrderRoom implements java.io.Serializable {

	private ViewOrderRoomId id;

	public ViewOrderRoom() {
	}

	public ViewOrderRoom(ViewOrderRoomId id) {
		this.id = id;
	}

	public ViewOrderRoomId getId() {
		return this.id;
	}

	public void setId(ViewOrderRoomId id) {
		this.id = id;
	}

}
