package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * ViewEndpointLatestStatus generated by hbm2java
 */
public class ViewEndpointLatestStatus implements java.io.Serializable {

	private ViewEndpointLatestStatusId id;

	public ViewEndpointLatestStatus() {
	}

	public ViewEndpointLatestStatus(ViewEndpointLatestStatusId id) {
		this.id = id;
	}

	public ViewEndpointLatestStatusId getId() {
		return this.id;
	}

	public void setId(ViewEndpointLatestStatusId id) {
		this.id = id;
	}

}
