package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * ViewUserGroupSceneId generated by hbm2java
 */
public class ViewUserGroupSceneId implements java.io.Serializable {

	private long id;
	private String name;
	private long userGroupId;
	private String userGroupName;

	public ViewUserGroupSceneId() {
	}

	public ViewUserGroupSceneId(long id, String name, long userGroupId,
			String userGroupName) {
		this.id = id;
		this.name = name;
		this.userGroupId = userGroupId;
		this.userGroupName = userGroupName;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public long getUserGroupId() {
		return this.userGroupId;
	}

	public void setUserGroupId(long userGroupId) {
		this.userGroupId = userGroupId;
	}

	public String getUserGroupName() {
		return this.userGroupName;
	}

	public void setUserGroupName(String userGroupName) {
		this.userGroupName = userGroupName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ViewUserGroupSceneId))
			return false;
		ViewUserGroupSceneId castOther = (ViewUserGroupSceneId) other;

		return (this.getId() == castOther.getId())
				&& ((this.getName() == castOther.getName()) || (this.getName() != null
						&& castOther.getName() != null && this.getName()
						.equals(castOther.getName())))
				&& (this.getUserGroupId() == castOther.getUserGroupId())
				&& ((this.getUserGroupName() == castOther.getUserGroupName()) || (this
						.getUserGroupName() != null
						&& castOther.getUserGroupName() != null && this
						.getUserGroupName()
						.equals(castOther.getUserGroupName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getId();
		result = 37 * result
				+ (getName() == null ? 0 : this.getName().hashCode());
		result = 37 * result + (int) this.getUserGroupId();
		result = 37
				* result
				+ (getUserGroupName() == null ? 0 : this.getUserGroupName()
						.hashCode());
		return result;
	}

}
