package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * ViewFlowVoiceRule generated by hbm2java
 */
public class ViewFlowVoiceRule implements java.io.Serializable {

	private ViewFlowVoiceRuleId id;

	public ViewFlowVoiceRule() {
	}

	public ViewFlowVoiceRule(ViewFlowVoiceRuleId id) {
		this.id = id;
	}

	public ViewFlowVoiceRuleId getId() {
		return this.id;
	}

	public void setId(ViewFlowVoiceRuleId id) {
		this.id = id;
	}

}
