package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * ViewRobotStatusLastestUpdatetime generated by hbm2java
 */
public class ViewRobotStatusLastestUpdatetime implements java.io.Serializable {

	private ViewRobotStatusLastestUpdatetimeId id;

	public ViewRobotStatusLastestUpdatetime() {
	}

	public ViewRobotStatusLastestUpdatetime(
			ViewRobotStatusLastestUpdatetimeId id) {
		this.id = id;
	}

	public ViewRobotStatusLastestUpdatetimeId getId() {
		return this.id;
	}

	public void setId(ViewRobotStatusLastestUpdatetimeId id) {
		this.id = id;
	}

}
