package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * ViewRobotLatestStatusDrop generated by hbm2java
 */
public class ViewRobotLatestStatusDrop implements java.io.Serializable {

	private ViewRobotLatestStatusDropId id;

	public ViewRobotLatestStatusDrop() {
	}

	public ViewRobotLatestStatusDrop(ViewRobotLatestStatusDropId id) {
		this.id = id;
	}

	public ViewRobotLatestStatusDropId getId() {
		return this.id;
	}

	public void setId(ViewRobotLatestStatusDropId id) {
		this.id = id;
	}

}
