package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * ViewUserStatusLastestUpdatetime generated by hbm2java
 */
public class ViewUserStatusLastestUpdatetime implements java.io.Serializable {

	private ViewUserStatusLastestUpdatetimeId id;

	public ViewUserStatusLastestUpdatetime() {
	}

	public ViewUserStatusLastestUpdatetime(ViewUserStatusLastestUpdatetimeId id) {
		this.id = id;
	}

	public ViewUserStatusLastestUpdatetimeId getId() {
		return this.id;
	}

	public void setId(ViewUserStatusLastestUpdatetimeId id) {
		this.id = id;
	}

}
