package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * ViewRobotAppBindList generated by hbm2java
 */
public class ViewRobotAppBindList implements java.io.Serializable {

	private ViewRobotAppBindListId id;

	public ViewRobotAppBindList() {
	}

	public ViewRobotAppBindList(ViewRobotAppBindListId id) {
		this.id = id;
	}

	public ViewRobotAppBindListId getId() {
		return this.id;
	}

	public void setId(ViewRobotAppBindListId id) {
		this.id = id;
	}

}
