package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * ViewRobotAppLastestVersion generated by hbm2java
 */
public class ViewRobotAppLastestVersion implements java.io.Serializable {

	private ViewRobotAppLastestVersionId id;

	public ViewRobotAppLastestVersion() {
	}

	public ViewRobotAppLastestVersion(ViewRobotAppLastestVersionId id) {
		this.id = id;
	}

	public ViewRobotAppLastestVersionId getId() {
		return this.id;
	}

	public void setId(ViewRobotAppLastestVersionId id) {
		this.id = id;
	}

}
