package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * ViewHuaqin2016ProivderConfrenceId generated by hbm2java
 */
public class ViewHuaqin2016ProivderConfrenceId implements java.io.Serializable {

	private String name;
	private String unamePinyin;
	private String companyName;
	private String companyCname;
	private String cnamePinyin;
	private String companyFullName;
	private long mettingRowNum;
	private long mettingColNum;
	private String dinnerNo;

	public ViewHuaqin2016ProivderConfrenceId() {
	}

	public ViewHuaqin2016ProivderConfrenceId(String name, String companyName,
			String companyFullName, long mettingRowNum, long mettingColNum,
			String dinnerNo) {
		this.name = name;
		this.companyName = companyName;
		this.companyFullName = companyFullName;
		this.mettingRowNum = mettingRowNum;
		this.mettingColNum = mettingColNum;
		this.dinnerNo = dinnerNo;
	}

	public ViewHuaqin2016ProivderConfrenceId(String name, String unamePinyin,
			String companyName, String companyCname, String cnamePinyin,
			String companyFullName, long mettingRowNum, long mettingColNum,
			String dinnerNo) {
		this.name = name;
		this.unamePinyin = unamePinyin;
		this.companyName = companyName;
		this.companyCname = companyCname;
		this.cnamePinyin = cnamePinyin;
		this.companyFullName = companyFullName;
		this.mettingRowNum = mettingRowNum;
		this.mettingColNum = mettingColNum;
		this.dinnerNo = dinnerNo;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getUnamePinyin() {
		return this.unamePinyin;
	}

	public void setUnamePinyin(String unamePinyin) {
		this.unamePinyin = unamePinyin;
	}

	public String getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	public String getCompanyCname() {
		return this.companyCname;
	}

	public void setCompanyCname(String companyCname) {
		this.companyCname = companyCname;
	}

	public String getCnamePinyin() {
		return this.cnamePinyin;
	}

	public void setCnamePinyin(String cnamePinyin) {
		this.cnamePinyin = cnamePinyin;
	}

	public String getCompanyFullName() {
		return this.companyFullName;
	}

	public void setCompanyFullName(String companyFullName) {
		this.companyFullName = companyFullName;
	}

	public long getMettingRowNum() {
		return this.mettingRowNum;
	}

	public void setMettingRowNum(long mettingRowNum) {
		this.mettingRowNum = mettingRowNum;
	}

	public long getMettingColNum() {
		return this.mettingColNum;
	}

	public void setMettingColNum(long mettingColNum) {
		this.mettingColNum = mettingColNum;
	}

	public String getDinnerNo() {
		return this.dinnerNo;
	}

	public void setDinnerNo(String dinnerNo) {
		this.dinnerNo = dinnerNo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ViewHuaqin2016ProivderConfrenceId))
			return false;
		ViewHuaqin2016ProivderConfrenceId castOther = (ViewHuaqin2016ProivderConfrenceId) other;

		return ((this.getName() == castOther.getName()) || (this.getName() != null
				&& castOther.getName() != null && this.getName().equals(
				castOther.getName())))
				&& ((this.getUnamePinyin() == castOther.getUnamePinyin()) || (this
						.getUnamePinyin() != null
						&& castOther.getUnamePinyin() != null && this
						.getUnamePinyin().equals(castOther.getUnamePinyin())))
				&& ((this.getCompanyName() == castOther.getCompanyName()) || (this
						.getCompanyName() != null
						&& castOther.getCompanyName() != null && this
						.getCompanyName().equals(castOther.getCompanyName())))
				&& ((this.getCompanyCname() == castOther.getCompanyCname()) || (this
						.getCompanyCname() != null
						&& castOther.getCompanyCname() != null && this
						.getCompanyCname().equals(castOther.getCompanyCname())))
				&& ((this.getCnamePinyin() == castOther.getCnamePinyin()) || (this
						.getCnamePinyin() != null
						&& castOther.getCnamePinyin() != null && this
						.getCnamePinyin().equals(castOther.getCnamePinyin())))
				&& ((this.getCompanyFullName() == castOther
						.getCompanyFullName()) || (this.getCompanyFullName() != null
						&& castOther.getCompanyFullName() != null && this
						.getCompanyFullName().equals(
								castOther.getCompanyFullName())))
				&& (this.getMettingRowNum() == castOther.getMettingRowNum())
				&& (this.getMettingColNum() == castOther.getMettingColNum())
				&& ((this.getDinnerNo() == castOther.getDinnerNo()) || (this
						.getDinnerNo() != null
						&& castOther.getDinnerNo() != null && this
						.getDinnerNo().equals(castOther.getDinnerNo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getName() == null ? 0 : this.getName().hashCode());
		result = 37
				* result
				+ (getUnamePinyin() == null ? 0 : this.getUnamePinyin()
						.hashCode());
		result = 37
				* result
				+ (getCompanyName() == null ? 0 : this.getCompanyName()
						.hashCode());
		result = 37
				* result
				+ (getCompanyCname() == null ? 0 : this.getCompanyCname()
						.hashCode());
		result = 37
				* result
				+ (getCnamePinyin() == null ? 0 : this.getCnamePinyin()
						.hashCode());
		result = 37
				* result
				+ (getCompanyFullName() == null ? 0 : this.getCompanyFullName()
						.hashCode());
		result = 37 * result + (int) this.getMettingRowNum();
		result = 37 * result + (int) this.getMettingColNum();
		result = 37 * result
				+ (getDinnerNo() == null ? 0 : this.getDinnerNo().hashCode());
		return result;
	}

}
