package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * ViewRobotTags generated by hbm2java
 */
public class ViewRobotTags implements java.io.Serializable {

	private ViewRobotTagsId id;

	public ViewRobotTags() {
	}

	public ViewRobotTags(ViewRobotTagsId id) {
		this.id = id;
	}

	public ViewRobotTagsId getId() {
		return this.id;
	}

	public void setId(ViewRobotTagsId id) {
		this.id = id;
	}

}
