package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * ViewValidThirdPartyApiParamsValue generated by hbm2java
 */
public class ViewValidThirdPartyApiParamsValue implements java.io.Serializable {

	private ViewValidThirdPartyApiParamsValueId id;

	public ViewValidThirdPartyApiParamsValue() {
	}

	public ViewValidThirdPartyApiParamsValue(
			ViewValidThirdPartyApiParamsValueId id) {
		this.id = id;
	}

	public ViewValidThirdPartyApiParamsValueId getId() {
		return this.id;
	}

	public void setId(ViewValidThirdPartyApiParamsValueId id) {
		this.id = id;
	}

}
