package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * ViewWordGroupFlowToVoiceGroupRuleOrignal generated by hbm2java
 */
public class ViewWordGroupFlowToVoiceGroupRuleOrignal implements
		java.io.Serializable {

	private ViewWordGroupFlowToVoiceGroupRuleOrignalId id;

	public ViewWordGroupFlowToVoiceGroupRuleOrignal() {
	}

	public ViewWordGroupFlowToVoiceGroupRuleOrignal(
			ViewWordGroupFlowToVoiceGroupRuleOrignalId id) {
		this.id = id;
	}

	public ViewWordGroupFlowToVoiceGroupRuleOrignalId getId() {
		return this.id;
	}

	public void setId(ViewWordGroupFlowToVoiceGroupRuleOrignalId id) {
		this.id = id;
	}

}
