package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * ViewVoiceGroupSimple generated by hbm2java
 */
public class ViewVoiceGroupSimple implements java.io.Serializable {

	private ViewVoiceGroupSimpleId id;

	public ViewVoiceGroupSimple() {
	}

	public ViewVoiceGroupSimple(ViewVoiceGroupSimpleId id) {
		this.id = id;
	}

	public ViewVoiceGroupSimpleId getId() {
		return this.id;
	}

	public void setId(ViewVoiceGroupSimpleId id) {
		this.id = id;
	}

}
