package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * ViewWordGroup generated by hbm2java
 */
public class ViewWordGroup implements java.io.Serializable {

	private ViewWordGroupId id;

	public ViewWordGroup() {
	}

	public ViewWordGroup(ViewWordGroupId id) {
		this.id = id;
	}

	public ViewWordGroupId getId() {
		return this.id;
	}

	public void setId(ViewWordGroupId id) {
		this.id = id;
	}

}
