package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * ViewRobotManualTalkCache generated by hbm2java
 */
public class ViewRobotManualTalkCache implements java.io.Serializable {

	private ViewRobotManualTalkCacheId id;

	public ViewRobotManualTalkCache() {
	}

	public ViewRobotManualTalkCache(ViewRobotManualTalkCacheId id) {
		this.id = id;
	}

	public ViewRobotManualTalkCacheId getId() {
		return this.id;
	}

	public void setId(ViewRobotManualTalkCacheId id) {
		this.id = id;
	}

}
