package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * ViewRtcSessionStatus generated by hbm2java
 */
public class ViewRtcSessionStatus implements java.io.Serializable {

	private ViewRtcSessionStatusId id;

	public ViewRtcSessionStatus() {
	}

	public ViewRtcSessionStatus(ViewRtcSessionStatusId id) {
		this.id = id;
	}

	public ViewRtcSessionStatusId getId() {
		return this.id;
	}

	public void setId(ViewRtcSessionStatusId id) {
		this.id = id;
	}

}
