package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * ViewRobotAppVersionRequiredId generated by hbm2java
 */
public class ViewRobotAppVersionRequiredId implements java.io.Serializable {

	private String dbVersion;
	private long appId;
	private String appName;
	private String robotImei;
	private long requriedVersionCode;
	private String requriedVersionName;
	private Long lastestVersionCode;
	private String lastestVersionName;

	public ViewRobotAppVersionRequiredId() {
	}

	public ViewRobotAppVersionRequiredId(String dbVersion, long appId,
			String appName, String robotImei, long requriedVersionCode,
			String requriedVersionName) {
		this.dbVersion = dbVersion;
		this.appId = appId;
		this.appName = appName;
		this.robotImei = robotImei;
		this.requriedVersionCode = requriedVersionCode;
		this.requriedVersionName = requriedVersionName;
	}

	public ViewRobotAppVersionRequiredId(String dbVersion, long appId,
			String appName, String robotImei, long requriedVersionCode,
			String requriedVersionName, Long lastestVersionCode,
			String lastestVersionName) {
		this.dbVersion = dbVersion;
		this.appId = appId;
		this.appName = appName;
		this.robotImei = robotImei;
		this.requriedVersionCode = requriedVersionCode;
		this.requriedVersionName = requriedVersionName;
		this.lastestVersionCode = lastestVersionCode;
		this.lastestVersionName = lastestVersionName;
	}

	public String getDbVersion() {
		return this.dbVersion;
	}

	public void setDbVersion(String dbVersion) {
		this.dbVersion = dbVersion;
	}

	public long getAppId() {
		return this.appId;
	}

	public void setAppId(long appId) {
		this.appId = appId;
	}

	public String getAppName() {
		return this.appName;
	}

	public void setAppName(String appName) {
		this.appName = appName;
	}

	public String getRobotImei() {
		return this.robotImei;
	}

	public void setRobotImei(String robotImei) {
		this.robotImei = robotImei;
	}

	public long getRequriedVersionCode() {
		return this.requriedVersionCode;
	}

	public void setRequriedVersionCode(long requriedVersionCode) {
		this.requriedVersionCode = requriedVersionCode;
	}

	public String getRequriedVersionName() {
		return this.requriedVersionName;
	}

	public void setRequriedVersionName(String requriedVersionName) {
		this.requriedVersionName = requriedVersionName;
	}

	public Long getLastestVersionCode() {
		return this.lastestVersionCode;
	}

	public void setLastestVersionCode(Long lastestVersionCode) {
		this.lastestVersionCode = lastestVersionCode;
	}

	public String getLastestVersionName() {
		return this.lastestVersionName;
	}

	public void setLastestVersionName(String lastestVersionName) {
		this.lastestVersionName = lastestVersionName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ViewRobotAppVersionRequiredId))
			return false;
		ViewRobotAppVersionRequiredId castOther = (ViewRobotAppVersionRequiredId) other;

		return ((this.getDbVersion() == castOther.getDbVersion()) || (this
				.getDbVersion() != null && castOther.getDbVersion() != null && this
				.getDbVersion().equals(castOther.getDbVersion())))
				&& (this.getAppId() == castOther.getAppId())
				&& ((this.getAppName() == castOther.getAppName()) || (this
						.getAppName() != null && castOther.getAppName() != null && this
						.getAppName().equals(castOther.getAppName())))
				&& ((this.getRobotImei() == castOther.getRobotImei()) || (this
						.getRobotImei() != null
						&& castOther.getRobotImei() != null && this
						.getRobotImei().equals(castOther.getRobotImei())))
				&& (this.getRequriedVersionCode() == castOther
						.getRequriedVersionCode())
				&& ((this.getRequriedVersionName() == castOther
						.getRequriedVersionName()) || (this
						.getRequriedVersionName() != null
						&& castOther.getRequriedVersionName() != null && this
						.getRequriedVersionName().equals(
								castOther.getRequriedVersionName())))
				&& ((this.getLastestVersionCode() == castOther
						.getLastestVersionCode()) || (this
						.getLastestVersionCode() != null
						&& castOther.getLastestVersionCode() != null && this
						.getLastestVersionCode().equals(
								castOther.getLastestVersionCode())))
				&& ((this.getLastestVersionName() == castOther
						.getLastestVersionName()) || (this
						.getLastestVersionName() != null
						&& castOther.getLastestVersionName() != null && this
						.getLastestVersionName().equals(
								castOther.getLastestVersionName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getDbVersion() == null ? 0 : this.getDbVersion().hashCode());
		result = 37 * result + (int) this.getAppId();
		result = 37 * result
				+ (getAppName() == null ? 0 : this.getAppName().hashCode());
		result = 37 * result
				+ (getRobotImei() == null ? 0 : this.getRobotImei().hashCode());
		result = 37 * result + (int) this.getRequriedVersionCode();
		result = 37
				* result
				+ (getRequriedVersionName() == null ? 0 : this
						.getRequriedVersionName().hashCode());
		result = 37
				* result
				+ (getLastestVersionCode() == null ? 0 : this
						.getLastestVersionCode().hashCode());
		result = 37
				* result
				+ (getLastestVersionName() == null ? 0 : this
						.getLastestVersionName().hashCode());
		return result;
	}

}
