package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * ViewRtcSessionStatusLastestUpdatetimeId generated by hbm2java
 */
public class ViewRtcSessionStatusLastestUpdatetimeId implements
		java.io.Serializable {

	private long rtcSessionId;
	private Date latestUpdateDatetime;

	public ViewRtcSessionStatusLastestUpdatetimeId() {
	}

	public ViewRtcSessionStatusLastestUpdatetimeId(long rtcSessionId,
			Date latestUpdateDatetime) {
		this.rtcSessionId = rtcSessionId;
		this.latestUpdateDatetime = latestUpdateDatetime;
	}

	public long getRtcSessionId() {
		return this.rtcSessionId;
	}

	public void setRtcSessionId(long rtcSessionId) {
		this.rtcSessionId = rtcSessionId;
	}

	public Date getLatestUpdateDatetime() {
		return this.latestUpdateDatetime;
	}

	public void setLatestUpdateDatetime(Date latestUpdateDatetime) {
		this.latestUpdateDatetime = latestUpdateDatetime;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ViewRtcSessionStatusLastestUpdatetimeId))
			return false;
		ViewRtcSessionStatusLastestUpdatetimeId castOther = (ViewRtcSessionStatusLastestUpdatetimeId) other;

		return (this.getRtcSessionId() == castOther.getRtcSessionId())
				&& ((this.getLatestUpdateDatetime() == castOther
						.getLatestUpdateDatetime()) || (this
						.getLatestUpdateDatetime() != null
						&& castOther.getLatestUpdateDatetime() != null && this
						.getLatestUpdateDatetime().equals(
								castOther.getLatestUpdateDatetime())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getRtcSessionId();
		result = 37
				* result
				+ (getLatestUpdateDatetime() == null ? 0 : this
						.getLatestUpdateDatetime().hashCode());
		return result;
	}

}
