package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * ViewRobotConfig generated by hbm2java
 */
public class ViewRobotConfig implements java.io.Serializable {

	private ViewRobotConfigId id;

	public ViewRobotConfig() {
	}

	public ViewRobotConfig(ViewRobotConfigId id) {
		this.id = id;
	}

	public ViewRobotConfigId getId() {
		return this.id;
	}

	public void setId(ViewRobotConfigId id) {
		this.id = id;
	}

}
