package org.sgpro.db;

// Generated 2017-6-21 11:12:45 by Hibernate Tools 4.0.0

/**
 * ViewRobotConfigForApp generated by hbm2java
 */
public class ViewRobotConfigForApp implements java.io.Serializable {

	private ViewRobotConfigForAppId id;

	public ViewRobotConfigForApp() {
	}

	public ViewRobotConfigForApp(ViewRobotConfigForAppId id) {
		this.id = id;
	}

	public ViewRobotConfigForAppId getId() {
		return this.id;
	}

	public void setId(ViewRobotConfigForAppId id) {
		this.id = id;
	}

}
